package com.discord.tti_manager;

import java.util.ArrayList;
import java.util.List;
import kotlin.Metadata;
import kotlin.jvm.internal.Intrinsics;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes3.dex */
@Metadata(d1 = {"\u0000>\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0003\n\u0002\u0010!\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u000b\n\u0002\b\u0005\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0010\u000e\n\u0000\n\u0002\u0010\t\n\u0002\b\u0004\bÆ\u0002\u0018\u00002\u00020\u0001:\u0001\u0019B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003J&\u0010\r\u001a\"\u0012\f\u0012\n \u000f*\u0004\u0018\u00010\u00060\u00060\u000ej\u0010\u0012\f\u0012\n \u000f*\u0004\u0018\u00010\u00060\u0006`\u0010J.\u0010\u0011\u001a\u00020\u00122\u0006\u0010\u0013\u001a\u00020\u00142\b\b\u0002\u0010\u0015\u001a\u00020\u00162\n\b\u0002\u0010\u0017\u001a\u0004\u0018\u00010\u00142\b\b\u0002\u0010\u0018\u001a\u00020\bR\u0014\u0010\u0004\u001a\b\u0012\u0004\u0012\u00020\u00060\u0005X\u0082\u0004¢\u0006\u0002\n\u0000R\u001a\u0010\u0007\u001a\u00020\bX\u0086\u000e¢\u0006\u000e\n\u0000\u001a\u0004\b\t\u0010\n\"\u0004\b\u000b\u0010\f¨\u0006\u001a"}, d2 = {"Lcom/discord/tti_manager/TTIMetrics;", "", "<init>", "()V", "timings", "", "Lcom/discord/tti_manager/TTIMetrics$Timing;", "loggedTTI", "", "getLoggedTTI", "()Z", "setLoggedTTI", "(Z)V", "getTimings", "Ljava/util/ArrayList;", "kotlin.jvm.PlatformType", "Lkotlin/collections/ArrayList;", "record", "", "label", "", "timestamp", "", "tag", "autoGenerated", "Timing", "tti_manager_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
public final class TTIMetrics {
    private static boolean loggedTTI;

    @NotNull
    public static final TTIMetrics INSTANCE = new TTIMetrics();

    @NotNull
    private static final List<Timing> timings = new ArrayList();

    @Metadata(d1 = {"\u0000(\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\n\u0002\u0010\u000e\n\u0000\n\u0002\u0010\t\n\u0002\b\u0002\n\u0002\u0010\u000b\n\u0002\b\u0011\n\u0002\u0010\b\n\u0002\b\u0002\b\u0086\b\u0018\u00002\u00020\u0001B)\u0012\u0006\u0010\u0002\u001a\u00020\u0003\u0012\u0006\u0010\u0004\u001a\u00020\u0005\u0012\b\u0010\u0006\u001a\u0004\u0018\u00010\u0003\u0012\u0006\u0010\u0007\u001a\u00020\b¢\u0006\u0004\b\t\u0010\nJ\t\u0010\u0012\u001a\u00020\u0003HÆ\u0003J\t\u0010\u0013\u001a\u00020\u0005HÆ\u0003J\u000b\u0010\u0014\u001a\u0004\u0018\u00010\u0003HÆ\u0003J\t\u0010\u0015\u001a\u00020\bHÆ\u0003J3\u0010\u0016\u001a\u00020\u00002\b\b\u0002\u0010\u0002\u001a\u00020\u00032\b\b\u0002\u0010\u0004\u001a\u00020\u00052\n\b\u0002\u0010\u0006\u001a\u0004\u0018\u00010\u00032\b\b\u0002\u0010\u0007\u001a\u00020\bHÆ\u0001J\u0013\u0010\u0017\u001a\u00020\b2\b\u0010\u0018\u001a\u0004\u0018\u00010\u0001HÖ\u0003J\t\u0010\u0019\u001a\u00020\u001aHÖ\u0001J\t\u0010\u001b\u001a\u00020\u0003HÖ\u0001R\u0011\u0010\u0002\u001a\u00020\u0003¢\u0006\b\n\u0000\u001a\u0004\b\u000b\u0010\fR\u0011\u0010\u0004\u001a\u00020\u0005¢\u0006\b\n\u0000\u001a\u0004\b\r\u0010\u000eR\u0013\u0010\u0006\u001a\u0004\u0018\u00010\u0003¢\u0006\b\n\u0000\u001a\u0004\b\u000f\u0010\fR\u0011\u0010\u0007\u001a\u00020\b¢\u0006\b\n\u0000\u001a\u0004\b\u0010\u0010\u0011¨\u0006\u001c"}, d2 = {"Lcom/discord/tti_manager/TTIMetrics$Timing;", "", "label", "", "timestamp", "", "tag", "autoGenerated", "", "<init>", "(Ljava/lang/String;JLjava/lang/String;Z)V", "getLabel", "()Ljava/lang/String;", "getTimestamp", "()J", "getTag", "getAutoGenerated", "()Z", "component1", "component2", "component3", "component4", "copy", "equals", "other", "hashCode", "", "toString", "tti_manager_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
    public static final /* data */ class Timing {
        private final boolean autoGenerated;

        @NotNull
        private final String label;
        private final String tag;
        private final long timestamp;

        public Timing(@NotNull String label, long j, String str, boolean z5) {
            Intrinsics.checkNotNullParameter(label, "label");
            this.label = label;
            this.timestamp = j;
            this.tag = str;
            this.autoGenerated = z5;
        }

        public static /* synthetic */ Timing copy$default(Timing timing, String str, long j, String str2, boolean z5, int i7, Object obj) {
            if ((i7 & 1) != 0) {
                str = timing.label;
            }
            if ((i7 & 2) != 0) {
                j = timing.timestamp;
            }
            if ((i7 & 4) != 0) {
                str2 = timing.tag;
            }
            if ((i7 & 8) != 0) {
                z5 = timing.autoGenerated;
            }
            return timing.copy(str, j, str2, z5);
        }

        @NotNull
        /* JADX INFO: renamed from: component1, reason: from getter */
        public final String getLabel() {
            return this.label;
        }

        /* JADX INFO: renamed from: component2, reason: from getter */
        public final long getTimestamp() {
            return this.timestamp;
        }

        /* JADX INFO: renamed from: component3, reason: from getter */
        public final String getTag() {
            return this.tag;
        }

        /* JADX INFO: renamed from: component4, reason: from getter */
        public final boolean getAutoGenerated() {
            return this.autoGenerated;
        }

        @NotNull
        public final Timing copy(@NotNull String label, long timestamp, String tag, boolean autoGenerated) {
            Intrinsics.checkNotNullParameter(label, "label");
            return new Timing(label, timestamp, tag, autoGenerated);
        }

        public boolean equals(Object other) {
            if (this == other) {
                return true;
            }
            if (!(other instanceof Timing)) {
                return false;
            }
            Timing timing = (Timing) other;
            return Intrinsics.areEqual(this.label, timing.label) && this.timestamp == timing.timestamp && Intrinsics.areEqual(this.tag, timing.tag) && this.autoGenerated == timing.autoGenerated;
        }

        public final boolean getAutoGenerated() {
            return this.autoGenerated;
        }

        @NotNull
        public final String getLabel() {
            return this.label;
        }

        public final String getTag() {
            return this.tag;
        }

        public final long getTimestamp() {
            return this.timestamp;
        }

        public int hashCode() {
            int iH = com.discord.chat.presentation.list.a.h(this.timestamp, this.label.hashCode() * 31, 31);
            String str = this.tag;
            return Boolean.hashCode(this.autoGenerated) + ((iH + (str == null ? 0 : str.hashCode())) * 31);
        }

        @NotNull
        public String toString() {
            return "Timing(label=" + this.label + ", timestamp=" + this.timestamp + ", tag=" + this.tag + ", autoGenerated=" + this.autoGenerated + ")";
        }
    }

    private TTIMetrics() {
    }

    public static /* synthetic */ void record$default(TTIMetrics tTIMetrics, String str, long j, String str2, boolean z5, int i7, Object obj) {
        if ((i7 & 2) != 0) {
            j = System.currentTimeMillis();
        }
        long j5 = j;
        if ((i7 & 4) != 0) {
            str2 = null;
        }
        String str3 = str2;
        if ((i7 & 8) != 0) {
            z5 = false;
        }
        tTIMetrics.record(str, j5, str3, z5);
    }

    public final synchronized boolean getLoggedTTI() {
        return loggedTTI;
    }

    @NotNull
    public final synchronized ArrayList<Timing> getTimings() {
        return new ArrayList<>(timings);
    }

    public final synchronized void record(@NotNull String label, long timestamp, String tag, boolean autoGenerated) {
        Intrinsics.checkNotNullParameter(label, "label");
        timings.add(new Timing(label, timestamp, tag, autoGenerated));
    }

    public final synchronized void setLoggedTTI(boolean z5) {
        loggedTTI = z5;
    }
}
