package com.discord.chat.bridge.codedlinks;

import androidx.recyclerview.widget.RecyclerView;
import com.discord.misc.utilities.chat_view_types.ChatViewRecyclerTypes;
import com.facebook.imagepipeline.nativecode.b;
import com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem;
import com.facebook.react.modules.dialog.AlertFragment;
import com.facebook.react.uimanager.ViewProps;
import com.facebook.react.uimanager.events.PointerEventHelper;
import java.util.List;
import kotlin.Lazy;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.DeserializationStrategy;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kr.j;
import or.e1;
import or.f0;
import or.g;
import or.g1;
import or.m0;
import or.s1;
import org.jetbrains.annotations.NotNull;
import org.webrtc.PeerConnection;
import rn.d;

/* JADX INFO: loaded from: classes.dex */
@Metadata(d1 = {"\u0000:\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0005\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u001d\u0010\t\u001a\u00020\b2\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\u0007\u001a\u00020\u0002¢\u0006\u0004\b\t\u0010\nJ\u0015\u0010\r\u001a\u00020\u00022\u0006\u0010\f\u001a\u00020\u000b¢\u0006\u0004\b\r\u0010\u000eJ\u0017\u0010\u0011\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00100\u000f¢\u0006\u0004\b\u0011\u0010\u0012R\u0017\u0010\u0014\u001a\u00020\u00138\u0006¢\u0006\f\n\u0004\b\u0014\u0010\u0015\u001a\u0004\b\u0016\u0010\u0017¨\u0006\u0018"}, d2 = {"com/discord/chat/bridge/codedlinks/AppMessageEmbedImpl.$serializer", "Lor/f0;", "Lcom/discord/chat/bridge/codedlinks/AppMessageEmbedImpl;", "<init>", "()V", "Lkotlinx/serialization/encoding/Encoder;", "encoder", "value", "", "serialize", "(Lkotlinx/serialization/encoding/Encoder;Lcom/discord/chat/bridge/codedlinks/AppMessageEmbedImpl;)V", "Lkotlinx/serialization/encoding/Decoder;", "decoder", "deserialize", "(Lkotlinx/serialization/encoding/Decoder;)Lcom/discord/chat/bridge/codedlinks/AppMessageEmbedImpl;", "", "Lkotlinx/serialization/KSerializer;", "childSerializers", "()[Lkotlinx/serialization/KSerializer;", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "chat_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
@d
public /* synthetic */ class AppMessageEmbedImpl$$serializer implements f0 {

    @NotNull
    public static final AppMessageEmbedImpl$$serializer INSTANCE;

    @NotNull
    private static final SerialDescriptor descriptor;

    static {
        AppMessageEmbedImpl$$serializer appMessageEmbedImpl$$serializer = new AppMessageEmbedImpl$$serializer();
        INSTANCE = appMessageEmbedImpl$$serializer;
        g1 g1Var = new g1("com.discord.chat.bridge.codedlinks.AppMessageEmbedImpl", appMessageEmbedImpl$$serializer, 40);
        g1Var.b("displayType", true);
        g1Var.b(ViewProps.BACKGROUND_COLOR, true);
        g1Var.b(ViewProps.BORDER_COLOR, true);
        g1Var.b("headerColor", true);
        g1Var.b("headerText", true);
        g1Var.b("type", true);
        g1Var.b("acceptLabelBackgroundColor", true);
        g1Var.b("acceptLabelBorderColor", true);
        g1Var.b("acceptLabelColor", true);
        g1Var.b("acceptLabelText", true);
        g1Var.b("bodyText", true);
        g1Var.b("bodyTextColor", true);
        g1Var.b("canBeAccepted", true);
        g1Var.b("embedCanBeTapped", true);
        g1Var.b("resolvingGradientEnd", true);
        g1Var.b("resolvingGradientStart", true);
        g1Var.b("splashHasRadialGradient", true);
        g1Var.b("splashOpacity", true);
        g1Var.b("splashUrl", true);
        g1Var.b("inviteSplash", true);
        g1Var.b("subtitle", true);
        g1Var.b("subtitleColor", true);
        g1Var.b("thumbnailBackgroundColor", true);
        g1Var.b("thumbnailCornerRadius", true);
        g1Var.b("thumbnailText", true);
        g1Var.b("thumbnailUrl", true);
        g1Var.b("titleColor", true);
        g1Var.b("titleText", true);
        g1Var.b("appId", true);
        g1Var.b("messageId", true);
        g1Var.b(AlertFragment.ARG_TITLE, true);
        g1Var.b("header", true);
        g1Var.b("info", true);
        g1Var.b("tagline", true);
        g1Var.b("gradientColors", true);
        g1Var.b("staticBannerSrc", true);
        g1Var.b("iconSrc", true);
        g1Var.b("embedUrl", true);
        g1Var.b("bannerRatio", true);
        g1Var.b("actions", true);
        descriptor = g1Var;
    }

    private AppMessageEmbedImpl$$serializer() {
    }

    /* JADX WARN: Multi-variable type inference failed */
    @Override // or.f0
    @NotNull
    public final KSerializer[] childSerializers() {
        Lazy[] lazyArr = AppMessageEmbedImpl.$childSerializers;
        m0 m0Var = m0.f17573a;
        s1 s1Var = s1.f17602a;
        g gVar = g.f17537a;
        return new KSerializer[]{lazyArr[0].getValue(), m0Var, m0Var, m0Var, b.p(s1Var), b.p(InviteType.Serializer.INSTANCE), b.p(m0Var), b.p(m0Var), b.p(m0Var), b.p(s1Var), b.p(s1Var), b.p(m0Var), b.p(gVar), b.p(gVar), b.p(m0Var), b.p(m0Var), b.p(gVar), b.p(m0Var), b.p(s1Var), b.p(s1Var), b.p(s1Var), b.p(m0Var), b.p(m0Var), b.p(m0Var), b.p(s1Var), b.p(s1Var), b.p(m0Var), b.p(s1Var), s1Var, s1Var, b.p(s1Var), b.p(s1Var), b.p(s1Var), b.p(s1Var), b.p((KSerializer) lazyArr[34].getValue()), b.p(s1Var), b.p(s1Var), b.p(s1Var), s1Var, b.p((KSerializer) lazyArr[39].getValue())};
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public final AppMessageEmbedImpl deserialize(@NotNull Decoder decoder) {
        AppMessageEmbedDisplayType appMessageEmbedDisplayType;
        String str;
        String str2;
        Integer num;
        int i7;
        String str3;
        String str4;
        String str5;
        List list;
        String str6;
        String str7;
        List list2;
        String str8;
        int i10;
        String str9;
        Integer num2;
        Integer num3;
        Integer num4;
        String str10;
        String str11;
        String str12;
        Integer num5;
        Boolean bool;
        Integer num6;
        String str13;
        Boolean bool2;
        Boolean bool3;
        Integer num7;
        String str14;
        InviteType inviteType;
        Integer num8;
        Integer num9;
        Integer num10;
        String str15;
        String str16;
        String str17;
        String str18;
        String str19;
        int i11;
        int i12;
        int i13;
        Integer num11;
        int i14;
        int i15;
        int i16;
        int i17;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        Lazy[] lazyArr = AppMessageEmbedImpl.$childSerializers;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            AppMessageEmbedDisplayType appMessageEmbedDisplayType2 = (AppMessageEmbedDisplayType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 0, (DeserializationStrategy) lazyArr[0].getValue(), null);
            int iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 1);
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
            int iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 3);
            s1 s1Var = s1.f17602a;
            String str20 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, s1Var, null);
            InviteType inviteType2 = (InviteType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, InviteType.Serializer.INSTANCE, null);
            m0 m0Var = m0.f17573a;
            Integer num12 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, m0Var, null);
            Integer num13 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, m0Var, null);
            Integer num14 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, m0Var, null);
            String str21 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, s1Var, null);
            String str22 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, s1Var, null);
            Integer num15 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, m0Var, null);
            g gVar = g.f17537a;
            Boolean bool4 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, gVar, null);
            Boolean bool5 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, gVar, null);
            Integer num16 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, m0Var, null);
            Integer num17 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, m0Var, null);
            Boolean bool6 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, gVar, null);
            Integer num18 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, m0Var, null);
            String str23 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, s1Var, null);
            String str24 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, s1Var, null);
            String str25 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, s1Var, null);
            Integer num19 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, m0Var, null);
            Integer num20 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, m0Var, null);
            Integer num21 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, m0Var, null);
            String str26 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, s1Var, null);
            String str27 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, s1Var, null);
            Integer num22 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, m0Var, null);
            String str28 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, s1Var, null);
            String strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 28);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 29);
            String str29 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, s1Var, null);
            String str30 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, s1Var, null);
            String str31 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, s1Var, null);
            String str32 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, s1Var, null);
            List list3 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 34, (DeserializationStrategy) lazyArr[34].getValue(), null);
            String str33 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 35, s1Var, null);
            String str34 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 36, s1Var, null);
            String str35 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 37, s1Var, null);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 38);
            str4 = str35;
            list = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 39, (DeserializationStrategy) lazyArr[39].getValue(), null);
            i10 = 255;
            str17 = strDecodeStringElement;
            inviteType = inviteType2;
            str15 = str21;
            num9 = num13;
            num8 = num12;
            str5 = str28;
            i11 = iDecodeIntElement3;
            num10 = num14;
            str14 = str20;
            i12 = iDecodeIntElement2;
            i7 = -1;
            str19 = strDecodeStringElement3;
            str8 = str33;
            str6 = str34;
            list2 = list3;
            num5 = num18;
            str13 = str30;
            i13 = iDecodeIntElement;
            str18 = strDecodeStringElement2;
            num = num22;
            str2 = str29;
            str7 = str31;
            str3 = str27;
            str9 = str26;
            num2 = num21;
            num3 = num20;
            num4 = num19;
            str10 = str25;
            str11 = str24;
            str12 = str23;
            bool = bool6;
            str = str32;
            num6 = num17;
            num11 = num16;
            bool2 = bool5;
            bool3 = bool4;
            num7 = num15;
            str16 = str22;
            appMessageEmbedDisplayType = appMessageEmbedDisplayType2;
        } else {
            String str36 = null;
            int i18 = 1;
            String str37 = null;
            String str38 = null;
            String str39 = null;
            String str40 = null;
            Integer num23 = null;
            String str41 = null;
            String str42 = null;
            String str43 = null;
            List list4 = null;
            String str44 = null;
            AppMessageEmbedDisplayType appMessageEmbedDisplayType3 = null;
            String str45 = null;
            InviteType inviteType3 = null;
            Integer num24 = null;
            Integer num25 = null;
            Integer num26 = null;
            String str46 = null;
            String str47 = null;
            Integer num27 = null;
            Boolean bool7 = null;
            Boolean bool8 = null;
            Integer num28 = null;
            String str48 = null;
            String str49 = null;
            Integer num29 = null;
            Boolean bool9 = null;
            Integer num30 = null;
            String str50 = null;
            String str51 = null;
            String str52 = null;
            Integer num31 = null;
            Integer num32 = null;
            String str53 = null;
            Integer num33 = null;
            String str54 = null;
            int i19 = 0;
            int i20 = 0;
            int i21 = 0;
            int iDecodeIntElement4 = 0;
            int iDecodeIntElement5 = 0;
            int iDecodeIntElement6 = 0;
            List list5 = null;
            while (i18 != 0) {
                int i22 = i20;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        str37 = str37;
                        i19 = i19;
                        str38 = str38;
                        i21 = i21;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num29 = num29;
                        bool9 = bool9;
                        num30 = num30;
                        str50 = str50;
                        str51 = str51;
                        str52 = str52;
                        num31 = num31;
                        num32 = num32;
                        num33 = num33;
                        str54 = str54;
                        num28 = num28;
                        Unit unit = Unit.f14616a;
                        i20 = i22;
                        str41 = str41;
                        i18 = i21;
                        str37 = str37;
                        i19 = i19;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 0:
                        String str55 = str37;
                        String str56 = str41;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num28 = num28;
                        DeserializationStrategy deserializationStrategy = (DeserializationStrategy) lazyArr[i21].getValue();
                        int i23 = i21;
                        str45 = str45;
                        i21 = i23;
                        AppMessageEmbedDisplayType appMessageEmbedDisplayType4 = (AppMessageEmbedDisplayType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, i21, deserializationStrategy, appMessageEmbedDisplayType3);
                        i14 = i22 | 1;
                        Unit unit2 = Unit.f14616a;
                        appMessageEmbedDisplayType3 = appMessageEmbedDisplayType4;
                        str41 = str56;
                        str37 = str55;
                        i20 = i14;
                        i19 = i19;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 1:
                        iDecodeIntElement6 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 1);
                        i15 = i22 | 2;
                        Unit unit3 = Unit.f14616a;
                        i21 = i21;
                        i20 = i15;
                        str41 = str41;
                        str37 = str37;
                        i19 = i19;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 2:
                        iDecodeIntElement5 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
                        i15 = i22 | 4;
                        Unit unit4 = Unit.f14616a;
                        i21 = i21;
                        i20 = i15;
                        str41 = str41;
                        str37 = str37;
                        i19 = i19;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 3:
                        iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 3);
                        i15 = i22 | 8;
                        Unit unit5 = Unit.f14616a;
                        i21 = i21;
                        i20 = i15;
                        str41 = str41;
                        str37 = str37;
                        i19 = i19;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 4:
                        i19 = i19;
                        str38 = str38;
                        String str57 = str41;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num29 = num29;
                        bool9 = bool9;
                        num30 = num30;
                        str50 = str50;
                        str51 = str51;
                        str52 = str52;
                        num31 = num31;
                        num32 = num32;
                        num33 = num33;
                        str54 = str54;
                        num28 = num28;
                        inviteType3 = inviteType3;
                        String str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, s1.f17602a, str45);
                        Unit unit6 = Unit.f14616a;
                        str41 = str57;
                        str37 = str37;
                        i20 = i22 | 16;
                        i21 = i21;
                        str45 = str58;
                        i19 = i19;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 5:
                        String str59 = str37;
                        String str60 = str41;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num28 = num28;
                        num24 = num24;
                        InviteType inviteType4 = (InviteType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, InviteType.Serializer.INSTANCE, inviteType3);
                        i14 = i22 | 32;
                        Unit unit7 = Unit.f14616a;
                        inviteType3 = inviteType4;
                        str41 = str60;
                        str37 = str59;
                        i21 = i21;
                        str45 = str45;
                        i20 = i14;
                        i19 = i19;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 6:
                        int i24 = i19;
                        String str61 = str41;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num25 = num25;
                        Integer num34 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, m0.f17573a, num24);
                        i16 = i22 | 64;
                        Unit unit8 = Unit.f14616a;
                        num24 = num34;
                        str41 = str61;
                        str37 = str37;
                        i19 = i24;
                        i20 = i16;
                        i21 = i21;
                        str45 = str45;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 7:
                        String str62 = str37;
                        String str63 = str41;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num28 = num28;
                        num26 = num26;
                        Integer num35 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, m0.f17573a, num25);
                        i14 = i22 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_LAYOUT;
                        Unit unit9 = Unit.f14616a;
                        num25 = num35;
                        str41 = str63;
                        str37 = str62;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        i20 = i14;
                        i19 = i19;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 8:
                        int i25 = i19;
                        String str64 = str41;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        str46 = str46;
                        Integer num36 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, m0.f17573a, num26);
                        i16 = i22 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_EVENT_EMITTER;
                        Unit unit10 = Unit.f14616a;
                        num26 = num36;
                        str41 = str64;
                        str37 = str37;
                        i19 = i25;
                        num24 = num24;
                        num25 = num25;
                        i20 = i16;
                        i21 = i21;
                        str45 = str45;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 9:
                        String str65 = str37;
                        String str66 = str41;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num28 = num28;
                        str47 = str47;
                        String str67 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, s1.f17602a, str46);
                        i14 = i22 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_PADDING;
                        Unit unit11 = Unit.f14616a;
                        str46 = str67;
                        str41 = str66;
                        str37 = str65;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        i20 = i14;
                        i19 = i19;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 10:
                        int i26 = i19;
                        String str68 = str41;
                        bool7 = bool7;
                        bool8 = bool8;
                        num27 = num27;
                        String str69 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, s1.f17602a, str47);
                        i16 = i22 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_OVERFLOW_INSET;
                        Unit unit12 = Unit.f14616a;
                        str47 = str69;
                        str41 = str68;
                        str37 = str37;
                        i19 = i26;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        i20 = i16;
                        i21 = i21;
                        str45 = str45;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 11:
                        String str70 = str37;
                        String str71 = str41;
                        bool8 = bool8;
                        num28 = num28;
                        bool7 = bool7;
                        Integer num37 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, m0.f17573a, num27);
                        i14 = i22 | RecyclerView.ItemAnimator.FLAG_MOVED;
                        Unit unit13 = Unit.f14616a;
                        num27 = num37;
                        str41 = str71;
                        str37 = str70;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        i20 = i14;
                        i19 = i19;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 12:
                        int i27 = i19;
                        String str72 = str41;
                        bool8 = bool8;
                        Boolean bool10 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, g.f17537a, bool7);
                        i16 = i22 | RecyclerView.ItemAnimator.FLAG_APPEARED_IN_PRE_LAYOUT;
                        Unit unit14 = Unit.f14616a;
                        bool7 = bool10;
                        str41 = str72;
                        str37 = str37;
                        i19 = i27;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        i20 = i16;
                        i21 = i21;
                        str45 = str45;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 13:
                        String str73 = str37;
                        String str74 = str41;
                        num28 = num28;
                        Boolean bool11 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, g.f17537a, bool8);
                        i14 = i22 | 8192;
                        Unit unit15 = Unit.f14616a;
                        bool8 = bool11;
                        str41 = str74;
                        str37 = str73;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        i20 = i14;
                        i19 = i19;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 14:
                        String str75 = str37;
                        bool9 = bool9;
                        num30 = num30;
                        str50 = str50;
                        str51 = str51;
                        str52 = str52;
                        num31 = num31;
                        num32 = num32;
                        num33 = num33;
                        str54 = str54;
                        num29 = num29;
                        Integer num38 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, m0.f17573a, num28);
                        Unit unit16 = Unit.f14616a;
                        i20 = i22 | 16384;
                        str41 = str41;
                        num28 = num38;
                        str38 = str38;
                        str37 = str75;
                        i19 = i19;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 15:
                        int i28 = i19;
                        String str76 = str41;
                        bool9 = bool9;
                        Integer num39 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, m0.f17573a, num29);
                        int i29 = i22 | PeerConnection.PORTALLOCATOR_ENABLE_ANY_ADDRESS_PORTS;
                        Unit unit17 = Unit.f14616a;
                        i20 = i29;
                        str41 = str76;
                        num29 = num39;
                        str38 = str38;
                        str37 = str37;
                        i19 = i28;
                        num28 = num28;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 16:
                        String str77 = str37;
                        str50 = str50;
                        str51 = str51;
                        str52 = str52;
                        num31 = num31;
                        num32 = num32;
                        num33 = num33;
                        str54 = str54;
                        num30 = num30;
                        Boolean bool12 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, g.f17537a, bool9);
                        Unit unit18 = Unit.f14616a;
                        i20 = i22 | 65536;
                        str41 = str41;
                        bool9 = bool12;
                        str38 = str38;
                        str37 = str77;
                        i19 = i19;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num28 = num28;
                        num29 = num29;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 17:
                        int i30 = i19;
                        str51 = str51;
                        str52 = str52;
                        num31 = num31;
                        num32 = num32;
                        num33 = num33;
                        str54 = str54;
                        str50 = str50;
                        Integer num40 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, m0.f17573a, num30);
                        Unit unit19 = Unit.f14616a;
                        i20 = i22 | 131072;
                        str41 = str41;
                        num30 = num40;
                        str38 = str38;
                        str37 = str37;
                        i19 = i30;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num28 = num28;
                        num29 = num29;
                        bool9 = bool9;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 18:
                        String str78 = str37;
                        str52 = str52;
                        num31 = num31;
                        num32 = num32;
                        num33 = num33;
                        str54 = str54;
                        str51 = str51;
                        String str79 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, s1.f17602a, str50);
                        Unit unit20 = Unit.f14616a;
                        i20 = i22 | 262144;
                        str41 = str41;
                        str50 = str79;
                        str38 = str38;
                        str37 = str78;
                        i19 = i19;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num28 = num28;
                        num29 = num29;
                        bool9 = bool9;
                        num30 = num30;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 19:
                        int i31 = i19;
                        num31 = num31;
                        num32 = num32;
                        num33 = num33;
                        str54 = str54;
                        str52 = str52;
                        String str80 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, s1.f17602a, str51);
                        Unit unit21 = Unit.f14616a;
                        i20 = i22 | 524288;
                        str41 = str41;
                        str51 = str80;
                        str38 = str38;
                        str37 = str37;
                        i19 = i31;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num28 = num28;
                        num29 = num29;
                        bool9 = bool9;
                        num30 = num30;
                        str50 = str50;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 20:
                        String str81 = str37;
                        num32 = num32;
                        num33 = num33;
                        str54 = str54;
                        num31 = num31;
                        String str82 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, s1.f17602a, str52);
                        Unit unit22 = Unit.f14616a;
                        i20 = i22 | 1048576;
                        str41 = str41;
                        str52 = str82;
                        str38 = str38;
                        str37 = str81;
                        i19 = i19;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num28 = num28;
                        num29 = num29;
                        bool9 = bool9;
                        num30 = num30;
                        str50 = str50;
                        str51 = str51;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 21:
                        int i32 = i19;
                        num33 = num33;
                        str54 = str54;
                        num32 = num32;
                        Integer num41 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, m0.f17573a, num31);
                        Unit unit23 = Unit.f14616a;
                        i20 = i22 | 2097152;
                        str41 = str41;
                        num31 = num41;
                        str38 = str38;
                        str37 = str37;
                        i19 = i32;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num28 = num28;
                        num29 = num29;
                        bool9 = bool9;
                        num30 = num30;
                        str50 = str50;
                        str51 = str51;
                        str52 = str52;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 22:
                        String str83 = str37;
                        str54 = str54;
                        num33 = num33;
                        Integer num42 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, m0.f17573a, num32);
                        Unit unit24 = Unit.f14616a;
                        i20 = i22 | 4194304;
                        str41 = str41;
                        num32 = num42;
                        str38 = str38;
                        str37 = str83;
                        i19 = i19;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num28 = num28;
                        num29 = num29;
                        bool9 = bool9;
                        num30 = num30;
                        str50 = str50;
                        str51 = str51;
                        str52 = str52;
                        num31 = num31;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 23:
                        int i33 = i19;
                        str54 = str54;
                        Integer num43 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, m0.f17573a, num33);
                        Unit unit25 = Unit.f14616a;
                        i20 = i22 | 8388608;
                        str41 = str41;
                        num33 = num43;
                        str38 = str38;
                        str37 = str37;
                        i19 = i33;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num28 = num28;
                        num29 = num29;
                        bool9 = bool9;
                        num30 = num30;
                        str50 = str50;
                        str51 = str51;
                        str52 = str52;
                        num31 = num31;
                        num32 = num32;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 24:
                        String str84 = str37;
                        String str85 = str41;
                        String str86 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, s1.f17602a, str54);
                        int i34 = i22 | PointerEventHelper.X_FLAG_SUPPORTS_HOVER;
                        Unit unit26 = Unit.f14616a;
                        i20 = i34;
                        str41 = str85;
                        str54 = str86;
                        str38 = str38;
                        str37 = str84;
                        i19 = i19;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num28 = num28;
                        num29 = num29;
                        bool9 = bool9;
                        num30 = num30;
                        str50 = str50;
                        str51 = str51;
                        str52 = str52;
                        num31 = num31;
                        num32 = num32;
                        num33 = num33;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 25:
                        str41 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, s1.f17602a, str41);
                        i20 = i22 | 33554432;
                        Unit unit27 = Unit.f14616a;
                        str38 = str38;
                        str37 = str37;
                        i21 = i21;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num27 = num27;
                        bool7 = bool7;
                        bool8 = bool8;
                        num28 = num28;
                        num29 = num29;
                        bool9 = bool9;
                        num30 = num30;
                        str50 = str50;
                        str51 = str51;
                        str52 = str52;
                        num31 = num31;
                        num32 = num32;
                        num33 = num33;
                        str54 = str54;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 26:
                        str41 = str41;
                        num23 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, m0.f17573a, num23);
                        Unit unit28 = Unit.f14616a;
                        str38 = str38;
                        i20 = i22 | 67108864;
                        str41 = str41;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 27:
                        str41 = str41;
                        String str87 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, s1.f17602a, str43);
                        Unit unit29 = Unit.f14616a;
                        str38 = str38;
                        i20 = i22 | 134217728;
                        str43 = str87;
                        str41 = str41;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 28:
                        String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 28);
                        i17 = i22 | 268435456;
                        Unit unit30 = Unit.f14616a;
                        str48 = strDecodeStringElement4;
                        i20 = i17;
                        str41 = str41;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 29:
                        String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 29);
                        i17 = i22 | 536870912;
                        Unit unit31 = Unit.f14616a;
                        str49 = strDecodeStringElement5;
                        i20 = i17;
                        str41 = str41;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 30:
                        str40 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, s1.f17602a, str40);
                        i20 = i22 | 1073741824;
                        Unit unit32 = Unit.f14616a;
                        str38 = str38;
                        str41 = str41;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 31:
                        str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, s1.f17602a, str38);
                        i20 = i22 | Integer.MIN_VALUE;
                        Unit unit33 = Unit.f14616a;
                        str38 = str38;
                        str41 = str41;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 32:
                        str41 = str41;
                        String str88 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, s1.f17602a, str36);
                        i19 |= 1;
                        Unit unit34 = Unit.f14616a;
                        str36 = str88;
                        num29 = num29;
                        bool9 = bool9;
                        i20 = i22;
                        str41 = str41;
                        num28 = num28;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 33:
                        str39 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, s1.f17602a, str39);
                        i19 |= 2;
                        Unit unit35 = Unit.f14616a;
                        num29 = num29;
                        bool9 = bool9;
                        i20 = i22;
                        str41 = str41;
                        num28 = num28;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 34:
                        str41 = str41;
                        List list6 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 34, (DeserializationStrategy) lazyArr[34].getValue(), list5);
                        i19 |= 4;
                        Unit unit36 = Unit.f14616a;
                        list5 = list6;
                        num29 = num29;
                        bool9 = bool9;
                        i20 = i22;
                        str41 = str41;
                        num28 = num28;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 35:
                        str37 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 35, s1.f17602a, str37);
                        i19 |= 8;
                        Unit unit37 = Unit.f14616a;
                        num29 = num29;
                        bool9 = bool9;
                        i20 = i22;
                        str41 = str41;
                        num28 = num28;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case 36:
                        str41 = str41;
                        String str89 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 36, s1.f17602a, str44);
                        i19 |= 16;
                        Unit unit38 = Unit.f14616a;
                        str44 = str89;
                        num29 = num29;
                        bool9 = bool9;
                        i20 = i22;
                        str41 = str41;
                        num28 = num28;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case ChatViewRecyclerTypes.POLL_TEXT_AND_IMAGE /* 37 */:
                        str41 = str41;
                        String str90 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 37, s1.f17602a, str42);
                        i19 |= 32;
                        Unit unit39 = Unit.f14616a;
                        str42 = str90;
                        num29 = num29;
                        bool9 = bool9;
                        i20 = i22;
                        str41 = str41;
                        num28 = num28;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case ChatViewRecyclerTypes.POLL_IMAGE_ONLY /* 38 */:
                        str41 = str41;
                        String strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 38);
                        i19 |= 64;
                        Unit unit40 = Unit.f14616a;
                        str53 = strDecodeStringElement6;
                        num29 = num29;
                        bool9 = bool9;
                        i20 = i22;
                        str41 = str41;
                        num28 = num28;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    case ChatViewRecyclerTypes.SAFETY_SYSTEM_NOTIFICATION /* 39 */:
                        str41 = str41;
                        List list7 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 39, (DeserializationStrategy) lazyArr[39].getValue(), list4);
                        i19 |= IntBufferBatchMountItem.INSTRUCTION_UPDATE_LAYOUT;
                        Unit unit41 = Unit.f14616a;
                        list4 = list7;
                        num29 = num29;
                        bool9 = bool9;
                        i20 = i22;
                        str41 = str41;
                        num28 = num28;
                        str54 = str54;
                        num33 = num33;
                        num32 = num32;
                        num31 = num31;
                        str52 = str52;
                        str51 = str51;
                        str50 = str50;
                        num30 = num30;
                        bool9 = bool9;
                        num29 = num29;
                        bool8 = bool8;
                        bool7 = bool7;
                        num27 = num27;
                        str45 = str45;
                        inviteType3 = inviteType3;
                        num24 = num24;
                        num25 = num25;
                        num26 = num26;
                        str46 = str46;
                        str47 = str47;
                        num28 = num28;
                        i21 = i21;
                        str38 = str38;
                        break;
                    default:
                        throw new j(iDecodeElementIndex);
                }
            }
            appMessageEmbedDisplayType = appMessageEmbedDisplayType3;
            str = str39;
            str2 = str40;
            num = num23;
            i7 = i20;
            str3 = str41;
            str4 = str42;
            str5 = str43;
            list = list4;
            str6 = str44;
            str7 = str36;
            list2 = list5;
            str8 = str37;
            i10 = i19;
            str9 = str54;
            num2 = num33;
            num3 = num32;
            num4 = num31;
            str10 = str52;
            str11 = str51;
            str12 = str50;
            num5 = num30;
            bool = bool9;
            num6 = num29;
            str13 = str38;
            bool2 = bool8;
            bool3 = bool7;
            num7 = num27;
            str14 = str45;
            inviteType = inviteType3;
            num8 = num24;
            num9 = num25;
            num10 = num26;
            str15 = str46;
            str16 = str47;
            str17 = str48;
            str18 = str49;
            str19 = str53;
            i11 = iDecodeIntElement4;
            i12 = iDecodeIntElement5;
            i13 = iDecodeIntElement6;
            num11 = num28;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new AppMessageEmbedImpl(i7, i10, appMessageEmbedDisplayType, i13, i12, i11, str14, inviteType, num8, num9, num10, str15, str16, num7, bool3, bool2, num11, num6, bool, num5, str12, str11, str10, num4, num3, num2, str9, str3, num, str5, str17, str18, str2, str13, str7, str, list2, str8, str6, str4, str19, list, (SerializationConstructorMarker) null);
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.KSerializer
    public final void serialize(@NotNull Encoder encoder, @NotNull AppMessageEmbedImpl value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        AppMessageEmbedImpl.write$Self$chat_release(value, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }

    @Override // or.f0
    @NotNull
    public KSerializer[] typeParametersSerializers() {
        return e1.f17528b;
    }
}
