package com.discord.chat.bridge.codedlinks;

import androidx.recyclerview.widget.RecyclerView;
import com.discord.chat.bridge.structurabletext.AnnotatedStructurableText;
import com.discord.chat.bridge.structurabletext.AnnotatedStructurableTextSerializer;
import com.facebook.imagepipeline.nativecode.b;
import com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem;
import com.facebook.react.uimanager.ViewProps;
import com.facebook.react.uimanager.events.PointerEventHelper;
import java.util.List;
import kotlin.Lazy;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.DeserializationStrategy;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kr.j;
import or.e1;
import or.f0;
import or.g;
import or.g1;
import or.m0;
import or.s1;
import org.jetbrains.annotations.NotNull;
import org.webrtc.PeerConnection;
import rn.d;

/* JADX INFO: loaded from: classes.dex */
@Metadata(d1 = {"\u0000:\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0005\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u001d\u0010\t\u001a\u00020\b2\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\u0007\u001a\u00020\u0002¢\u0006\u0004\b\t\u0010\nJ\u0015\u0010\r\u001a\u00020\u00022\u0006\u0010\f\u001a\u00020\u000b¢\u0006\u0004\b\r\u0010\u000eJ\u0017\u0010\u0011\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00100\u000f¢\u0006\u0004\b\u0011\u0010\u0012R\u0017\u0010\u0014\u001a\u00020\u00138\u0006¢\u0006\f\n\u0004\b\u0014\u0010\u0015\u001a\u0004\b\u0016\u0010\u0017¨\u0006\u0018"}, d2 = {"com/discord/chat/bridge/codedlinks/EmbeddedActivityInviteEmbedImpl.$serializer", "Lor/f0;", "Lcom/discord/chat/bridge/codedlinks/EmbeddedActivityInviteEmbedImpl;", "<init>", "()V", "Lkotlinx/serialization/encoding/Encoder;", "encoder", "value", "", "serialize", "(Lkotlinx/serialization/encoding/Encoder;Lcom/discord/chat/bridge/codedlinks/EmbeddedActivityInviteEmbedImpl;)V", "Lkotlinx/serialization/encoding/Decoder;", "decoder", "deserialize", "(Lkotlinx/serialization/encoding/Decoder;)Lcom/discord/chat/bridge/codedlinks/EmbeddedActivityInviteEmbedImpl;", "", "Lkotlinx/serialization/KSerializer;", "childSerializers", "()[Lkotlinx/serialization/KSerializer;", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "chat_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
@d
public /* synthetic */ class EmbeddedActivityInviteEmbedImpl$$serializer implements f0 {

    @NotNull
    public static final EmbeddedActivityInviteEmbedImpl$$serializer INSTANCE;

    @NotNull
    private static final SerialDescriptor descriptor;

    static {
        EmbeddedActivityInviteEmbedImpl$$serializer embeddedActivityInviteEmbedImpl$$serializer = new EmbeddedActivityInviteEmbedImpl$$serializer();
        INSTANCE = embeddedActivityInviteEmbedImpl$$serializer;
        g1 g1Var = new g1("com.discord.chat.bridge.codedlinks.EmbeddedActivityInviteEmbedImpl", embeddedActivityInviteEmbedImpl$$serializer, 33);
        g1Var.b(ViewProps.BACKGROUND_COLOR, false);
        g1Var.b(ViewProps.BORDER_COLOR, false);
        g1Var.b("headerColor", false);
        g1Var.b("headerText", false);
        g1Var.b("type", true);
        g1Var.b("acceptLabelBackgroundColor", true);
        g1Var.b("acceptLabelBorderColor", true);
        g1Var.b("acceptLabelColor", true);
        g1Var.b("acceptLabelText", true);
        g1Var.b("bodyText", true);
        g1Var.b("bodyTextColor", true);
        g1Var.b("canBeAccepted", true);
        g1Var.b("embedCanBeTapped", true);
        g1Var.b("resolvingGradientEnd", true);
        g1Var.b("resolvingGradientStart", true);
        g1Var.b("splashHasRadialGradient", true);
        g1Var.b("splashOpacity", true);
        g1Var.b("splashUrl", true);
        g1Var.b("inviteSplash", true);
        g1Var.b("subtitle", true);
        g1Var.b("subtitleColor", true);
        g1Var.b("thumbnailBackgroundColor", true);
        g1Var.b("thumbnailCornerRadius", true);
        g1Var.b("thumbnailText", true);
        g1Var.b("thumbnailUrl", true);
        g1Var.b("titleColor", true);
        g1Var.b("titleText", true);
        g1Var.b("channelIcon", true);
        g1Var.b("participantAvatarUris", false);
        g1Var.b("extendedType", false);
        g1Var.b("structurableSubtitleText", true);
        g1Var.b("noParticipantsText", false);
        g1Var.b("ctaEnabled", false);
        descriptor = g1Var;
    }

    private EmbeddedActivityInviteEmbedImpl$$serializer() {
    }

    /* JADX WARN: Multi-variable type inference failed */
    @Override // or.f0
    @NotNull
    public final KSerializer[] childSerializers() {
        Lazy[] lazyArr = EmbeddedActivityInviteEmbedImpl.$childSerializers;
        m0 m0Var = m0.f17573a;
        s1 s1Var = s1.f17602a;
        g gVar = g.f17537a;
        return new KSerializer[]{m0Var, m0Var, m0Var, b.p(s1Var), b.p(InviteType.Serializer.INSTANCE), b.p(m0Var), b.p(m0Var), b.p(m0Var), b.p(s1Var), b.p(s1Var), b.p(m0Var), b.p(gVar), b.p(gVar), b.p(m0Var), b.p(m0Var), b.p(gVar), b.p(m0Var), b.p(s1Var), b.p(s1Var), b.p(s1Var), b.p(m0Var), b.p(m0Var), b.p(m0Var), b.p(s1Var), b.p(s1Var), b.p(m0Var), b.p(s1Var), b.p(s1Var), lazyArr[28].getValue(), CodedLinkExtendedType.Serializer.INSTANCE, b.p(AnnotatedStructurableTextSerializer.INSTANCE), s1Var, gVar};
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public final EmbeddedActivityInviteEmbedImpl deserialize(@NotNull Decoder decoder) {
        int i7;
        Integer num;
        Integer num2;
        Boolean bool;
        Integer num3;
        Integer num4;
        InviteType inviteType;
        String str;
        Boolean bool2;
        Integer num5;
        String str2;
        String str3;
        int i10;
        AnnotatedStructurableText annotatedStructurableText;
        List list;
        String str4;
        String str5;
        Integer num6;
        String str6;
        String str7;
        Integer num7;
        Integer num8;
        Integer num9;
        String str8;
        String str9;
        String str10;
        Integer num10;
        Boolean bool3;
        Integer num11;
        CodedLinkExtendedType codedLinkExtendedType;
        String strDecodeStringElement;
        boolean zDecodeBooleanElement;
        int i11;
        int i12;
        int i13;
        Integer num12;
        Integer num13;
        int i14;
        int i15;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        Lazy[] lazyArr = EmbeddedActivityInviteEmbedImpl.$childSerializers;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            int iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 0);
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 1);
            int iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
            s1 s1Var = s1.f17602a;
            String str11 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, s1Var, null);
            InviteType inviteType2 = (InviteType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, InviteType.Serializer.INSTANCE, null);
            m0 m0Var = m0.f17573a;
            Integer num14 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, m0Var, null);
            Integer num15 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, m0Var, null);
            Integer num16 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, m0Var, null);
            String str12 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, s1Var, null);
            String str13 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, s1Var, null);
            Integer num17 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, m0Var, null);
            g gVar = g.f17537a;
            Boolean bool4 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, gVar, null);
            Boolean bool5 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, gVar, null);
            Integer num18 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, m0Var, null);
            Integer num19 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, m0Var, null);
            Boolean bool6 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, gVar, null);
            Integer num20 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, m0Var, null);
            String str14 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, s1Var, null);
            String str15 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, s1Var, null);
            String str16 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, s1Var, null);
            Integer num21 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, m0Var, null);
            Integer num22 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, m0Var, null);
            Integer num23 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, m0Var, null);
            String str17 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, s1Var, null);
            String str18 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, s1Var, null);
            Integer num24 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, m0Var, null);
            String str19 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, s1Var, null);
            String str20 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, s1Var, null);
            List list2 = (List) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 28, (DeserializationStrategy) lazyArr[28].getValue(), null);
            CodedLinkExtendedType codedLinkExtendedType2 = (CodedLinkExtendedType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 29, CodedLinkExtendedType.Serializer.INSTANCE, null);
            annotatedStructurableText = (AnnotatedStructurableText) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, AnnotatedStructurableTextSerializer.INSTANCE, null);
            num10 = num20;
            str = str11;
            str3 = str12;
            inviteType = inviteType2;
            i13 = iDecodeIntElement3;
            strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 31);
            i10 = iDecodeIntElement2;
            zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 32);
            str5 = str19;
            str2 = str13;
            num3 = num16;
            num2 = num15;
            num4 = num14;
            i7 = -1;
            codedLinkExtendedType = codedLinkExtendedType2;
            str4 = str20;
            num6 = num24;
            list = list2;
            str6 = str18;
            str7 = str17;
            num7 = num23;
            num8 = num22;
            num9 = num21;
            str8 = str16;
            str9 = str15;
            str10 = str14;
            bool3 = bool6;
            num11 = num19;
            num = num18;
            bool2 = bool5;
            bool = bool4;
            num5 = num17;
            i11 = iDecodeIntElement;
            i12 = 1;
        } else {
            int i16 = 0;
            int i17 = 0;
            boolean zDecodeBooleanElement2 = false;
            int i18 = 0;
            int i19 = 0;
            Integer num25 = null;
            Boolean bool7 = null;
            Integer num26 = null;
            Integer num27 = null;
            String str21 = null;
            Boolean bool8 = null;
            Integer num28 = null;
            String str22 = null;
            String str23 = null;
            Integer num29 = null;
            Integer num30 = null;
            Boolean bool9 = null;
            Integer num31 = null;
            String str24 = null;
            String str25 = null;
            String str26 = null;
            Integer num32 = null;
            Integer num33 = null;
            Integer num34 = null;
            String str27 = null;
            String str28 = null;
            Integer num35 = null;
            String str29 = null;
            String str30 = null;
            List list3 = null;
            CodedLinkExtendedType codedLinkExtendedType3 = null;
            AnnotatedStructurableText annotatedStructurableText2 = null;
            String strDecodeStringElement2 = null;
            boolean z5 = true;
            int iDecodeIntElement4 = 0;
            InviteType inviteType3 = null;
            while (z5) {
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        i17 = i17;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        Unit unit = Unit.f14616a;
                        i18 = i18;
                        num12 = num29;
                        i16 = i16;
                        z5 = false;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 0:
                        i17 = i17;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        int iDecodeIntElement5 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 0);
                        i18 |= 1;
                        Unit unit2 = Unit.f14616a;
                        num12 = num29;
                        i16 = iDecodeIntElement5;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 1:
                        i17 = i17;
                        iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 1);
                        Unit unit3 = Unit.f14616a;
                        i18 |= 2;
                        num12 = num29;
                        i16 = i16;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 2:
                        iDecodeIntElement4 = iDecodeIntElement4;
                        int iDecodeIntElement6 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
                        Unit unit4 = Unit.f14616a;
                        i18 |= 4;
                        num12 = num29;
                        i16 = i16;
                        i17 = iDecodeIntElement6;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 3:
                        i17 = i17;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        String str31 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, s1.f17602a, str21);
                        Unit unit5 = Unit.f14616a;
                        i18 |= 8;
                        num12 = num29;
                        i16 = i16;
                        str21 = str31;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 4:
                        i17 = i17;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        InviteType inviteType4 = (InviteType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, InviteType.Serializer.INSTANCE, inviteType3);
                        Unit unit6 = Unit.f14616a;
                        i18 |= 16;
                        num12 = num29;
                        i16 = i16;
                        inviteType3 = inviteType4;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 5:
                        num30 = num30;
                        num13 = num29;
                        num27 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, m0.f17573a, num27);
                        i14 = i18 | 32;
                        Unit unit7 = Unit.f14616a;
                        i18 = i14;
                        num12 = num13;
                        i16 = i16;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 6:
                        num30 = num30;
                        num13 = num29;
                        num25 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, m0.f17573a, num25);
                        i14 = i18 | 64;
                        Unit unit8 = Unit.f14616a;
                        i18 = i14;
                        num12 = num13;
                        i16 = i16;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 7:
                        num30 = num30;
                        num13 = num29;
                        num26 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, m0.f17573a, num26);
                        i14 = i18 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_LAYOUT;
                        Unit unit9 = Unit.f14616a;
                        i18 = i14;
                        num12 = num13;
                        i16 = i16;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 8:
                        i17 = i17;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        String str32 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, s1.f17602a, str23);
                        int i20 = i18 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_EVENT_EMITTER;
                        Unit unit10 = Unit.f14616a;
                        i18 = i20;
                        num12 = num29;
                        i16 = i16;
                        str23 = str32;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 9:
                        i17 = i17;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        String str33 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, s1.f17602a, str22);
                        int i21 = i18 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_PADDING;
                        Unit unit11 = Unit.f14616a;
                        i18 = i21;
                        num12 = num29;
                        i16 = i16;
                        str22 = str33;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 10:
                        i17 = i17;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        Integer num36 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, m0.f17573a, num28);
                        int i22 = i18 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_OVERFLOW_INSET;
                        Unit unit12 = Unit.f14616a;
                        i18 = i22;
                        num12 = num29;
                        i16 = i16;
                        num28 = num36;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 11:
                        num30 = num30;
                        num13 = num29;
                        bool7 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, g.f17537a, bool7);
                        i14 = i18 | RecyclerView.ItemAnimator.FLAG_MOVED;
                        Unit unit13 = Unit.f14616a;
                        i18 = i14;
                        num12 = num13;
                        i16 = i16;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 12:
                        i17 = i17;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        Boolean bool10 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, g.f17537a, bool8);
                        int i23 = i18 | RecyclerView.ItemAnimator.FLAG_APPEARED_IN_PRE_LAYOUT;
                        Unit unit14 = Unit.f14616a;
                        i18 = i23;
                        num12 = num29;
                        i16 = i16;
                        bool8 = bool10;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 13:
                        num30 = num30;
                        num13 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, m0.f17573a, num29);
                        i14 = i18 | 8192;
                        Unit unit15 = Unit.f14616a;
                        i18 = i14;
                        num12 = num13;
                        i16 = i16;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 14:
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        bool9 = bool9;
                        Integer num37 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, m0.f17573a, num30);
                        i15 = i18 | 16384;
                        Unit unit16 = Unit.f14616a;
                        num30 = num37;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 15:
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        num31 = num31;
                        Boolean bool11 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, g.f17537a, bool9);
                        i15 = i18 | PeerConnection.PORTALLOCATOR_ENABLE_ANY_ADDRESS_PORTS;
                        Unit unit17 = Unit.f14616a;
                        bool9 = bool11;
                        num30 = num30;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 16:
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        str24 = str24;
                        Integer num38 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, m0.f17573a, num31);
                        i15 = i18 | 65536;
                        Unit unit18 = Unit.f14616a;
                        num31 = num38;
                        num30 = num30;
                        bool9 = bool9;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 17:
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        str25 = str25;
                        String str34 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, s1.f17602a, str24);
                        i15 = i18 | 131072;
                        Unit unit19 = Unit.f14616a;
                        str24 = str34;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 18:
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        str26 = str26;
                        String str35 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, s1.f17602a, str25);
                        i15 = i18 | 262144;
                        Unit unit20 = Unit.f14616a;
                        str25 = str35;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 19:
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        num32 = num32;
                        String str36 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, s1.f17602a, str26);
                        i15 = i18 | 524288;
                        Unit unit21 = Unit.f14616a;
                        str26 = str36;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 20:
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        num33 = num33;
                        Integer num39 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, m0.f17573a, num32);
                        i15 = i18 | 1048576;
                        Unit unit22 = Unit.f14616a;
                        num32 = num39;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 21:
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        num34 = num34;
                        Integer num40 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, m0.f17573a, num33);
                        i15 = i18 | 2097152;
                        Unit unit23 = Unit.f14616a;
                        num33 = num40;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 22:
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        str27 = str27;
                        Integer num41 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, m0.f17573a, num34);
                        i15 = i18 | 4194304;
                        Unit unit24 = Unit.f14616a;
                        num34 = num41;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 23:
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        str28 = str28;
                        String str37 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, s1.f17602a, str27);
                        i15 = i18 | 8388608;
                        Unit unit25 = Unit.f14616a;
                        str27 = str37;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 24:
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        num35 = num35;
                        String str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, s1.f17602a, str28);
                        i15 = i18 | PointerEventHelper.X_FLAG_SUPPORTS_HOVER;
                        Unit unit26 = Unit.f14616a;
                        str28 = str38;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 25:
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        str29 = str29;
                        Integer num42 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, m0.f17573a, num35);
                        i15 = i18 | 33554432;
                        Unit unit27 = Unit.f14616a;
                        num35 = num42;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 26:
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        str30 = str30;
                        String str39 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, s1.f17602a, str29);
                        i15 = i18 | 67108864;
                        Unit unit28 = Unit.f14616a;
                        str29 = str39;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 27:
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        String str40 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, s1.f17602a, str30);
                        i15 = i18 | 134217728;
                        Unit unit29 = Unit.f14616a;
                        str30 = str40;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 28:
                        annotatedStructurableText2 = annotatedStructurableText2;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        List list4 = (List) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 28, (DeserializationStrategy) lazyArr[28].getValue(), list3);
                        i15 = i18 | 268435456;
                        Unit unit30 = Unit.f14616a;
                        list3 = list4;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 29:
                        annotatedStructurableText2 = annotatedStructurableText2;
                        CodedLinkExtendedType codedLinkExtendedType4 = (CodedLinkExtendedType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 29, CodedLinkExtendedType.Serializer.INSTANCE, codedLinkExtendedType3);
                        i15 = i18 | 536870912;
                        Unit unit31 = Unit.f14616a;
                        codedLinkExtendedType3 = codedLinkExtendedType4;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 30:
                        AnnotatedStructurableText annotatedStructurableText3 = (AnnotatedStructurableText) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, AnnotatedStructurableTextSerializer.INSTANCE, annotatedStructurableText2);
                        i15 = i18 | 1073741824;
                        Unit unit32 = Unit.f14616a;
                        annotatedStructurableText2 = annotatedStructurableText3;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i16 = i16;
                        i18 = i15;
                        num12 = num29;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 31:
                        strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 31);
                        i18 |= Integer.MIN_VALUE;
                        Unit unit33 = Unit.f14616a;
                        i17 = i17;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        num12 = num29;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    case 32:
                        zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 32);
                        Unit unit34 = Unit.f14616a;
                        i17 = i17;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        num12 = num29;
                        num30 = num30;
                        bool9 = bool9;
                        num31 = num31;
                        str24 = str24;
                        str25 = str25;
                        str26 = str26;
                        num32 = num32;
                        num33 = num33;
                        num34 = num34;
                        str27 = str27;
                        str28 = str28;
                        num35 = num35;
                        str29 = str29;
                        str30 = str30;
                        list3 = list3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        i19 = 1;
                        num29 = num12;
                        iDecodeIntElement4 = iDecodeIntElement4;
                        annotatedStructurableText2 = annotatedStructurableText2;
                        list3 = list3;
                        str30 = str30;
                        str29 = str29;
                        num35 = num35;
                        str28 = str28;
                        str27 = str27;
                        num34 = num34;
                        num33 = num33;
                        num32 = num32;
                        str26 = str26;
                        str25 = str25;
                        str24 = str24;
                        num31 = num31;
                        bool9 = bool9;
                        num30 = num30;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i17 = i17;
                        break;
                    default:
                        throw new j(iDecodeElementIndex);
                }
            }
            i7 = i18;
            num = num29;
            num2 = num25;
            bool = bool7;
            num3 = num26;
            num4 = num27;
            inviteType = inviteType3;
            str = str21;
            bool2 = bool8;
            num5 = num28;
            str2 = str22;
            str3 = str23;
            i10 = iDecodeIntElement4;
            annotatedStructurableText = annotatedStructurableText2;
            list = list3;
            str4 = str30;
            str5 = str29;
            num6 = num35;
            str6 = str28;
            str7 = str27;
            num7 = num34;
            num8 = num33;
            num9 = num32;
            str8 = str26;
            str9 = str25;
            str10 = str24;
            num10 = num31;
            bool3 = bool9;
            num11 = num30;
            codedLinkExtendedType = codedLinkExtendedType3;
            strDecodeStringElement = strDecodeStringElement2;
            zDecodeBooleanElement = zDecodeBooleanElement2;
            i11 = i16;
            i12 = i19;
            i13 = i17;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new EmbeddedActivityInviteEmbedImpl(i7, i12, i11, i10, i13, str, inviteType, num4, num2, num3, str3, str2, num5, bool, bool2, num, num11, bool3, num10, str10, str9, str8, num9, num8, num7, str7, str6, num6, str5, str4, list, codedLinkExtendedType, annotatedStructurableText, strDecodeStringElement, zDecodeBooleanElement, (SerializationConstructorMarker) null);
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.KSerializer
    public final void serialize(@NotNull Encoder encoder, @NotNull EmbeddedActivityInviteEmbedImpl value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        EmbeddedActivityInviteEmbedImpl.write$Self$chat_release(value, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }

    @Override // or.f0
    @NotNull
    public KSerializer[] typeParametersSerializers() {
        return e1.f17528b;
    }
}
