package com.discord.chat.bridge.codedlinks;

import androidx.recyclerview.widget.RecyclerView;
import com.facebook.imagepipeline.nativecode.b;
import com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem;
import com.facebook.react.uimanager.ViewProps;
import com.facebook.react.uimanager.events.PointerEventHelper;
import java.util.List;
import kotlin.Lazy;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.DeserializationStrategy;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kr.j;
import or.e1;
import or.f0;
import or.g;
import or.g1;
import or.m0;
import or.s1;
import org.jetbrains.annotations.NotNull;
import org.webrtc.PeerConnection;
import rn.d;

/* JADX INFO: loaded from: classes.dex */
@Metadata(d1 = {"\u0000:\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0005\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u001d\u0010\t\u001a\u00020\b2\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\u0007\u001a\u00020\u0002¢\u0006\u0004\b\t\u0010\nJ\u0015\u0010\r\u001a\u00020\u00022\u0006\u0010\f\u001a\u00020\u000b¢\u0006\u0004\b\r\u0010\u000eJ\u0017\u0010\u0011\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00100\u000f¢\u0006\u0004\b\u0011\u0010\u0012R\u0017\u0010\u0014\u001a\u00020\u00138\u0006¢\u0006\f\n\u0004\b\u0014\u0010\u0015\u001a\u0004\b\u0016\u0010\u0017¨\u0006\u0018"}, d2 = {"com/discord/chat/bridge/codedlinks/GuildProfileInviteEmbedImpl.$serializer", "Lor/f0;", "Lcom/discord/chat/bridge/codedlinks/GuildProfileInviteEmbedImpl;", "<init>", "()V", "Lkotlinx/serialization/encoding/Encoder;", "encoder", "value", "", "serialize", "(Lkotlinx/serialization/encoding/Encoder;Lcom/discord/chat/bridge/codedlinks/GuildProfileInviteEmbedImpl;)V", "Lkotlinx/serialization/encoding/Decoder;", "decoder", "deserialize", "(Lkotlinx/serialization/encoding/Decoder;)Lcom/discord/chat/bridge/codedlinks/GuildProfileInviteEmbedImpl;", "", "Lkotlinx/serialization/KSerializer;", "childSerializers", "()[Lkotlinx/serialization/KSerializer;", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "chat_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
@d
public /* synthetic */ class GuildProfileInviteEmbedImpl$$serializer implements f0 {

    @NotNull
    public static final GuildProfileInviteEmbedImpl$$serializer INSTANCE;

    @NotNull
    private static final SerialDescriptor descriptor;

    static {
        GuildProfileInviteEmbedImpl$$serializer guildProfileInviteEmbedImpl$$serializer = new GuildProfileInviteEmbedImpl$$serializer();
        INSTANCE = guildProfileInviteEmbedImpl$$serializer;
        g1 g1Var = new g1("com.discord.chat.bridge.codedlinks.GuildProfileInviteEmbedImpl", guildProfileInviteEmbedImpl$$serializer, 37);
        g1Var.b("acceptLabelBackgroundColor", true);
        g1Var.b("acceptLabelBorderColor", true);
        g1Var.b("acceptLabelColor", true);
        g1Var.b("acceptLabelText", true);
        g1Var.b("bodyTextColor", true);
        g1Var.b("bodyText", true);
        g1Var.b(ViewProps.BACKGROUND_COLOR, false);
        g1Var.b(ViewProps.BORDER_COLOR, false);
        g1Var.b("canBeAccepted", true);
        g1Var.b("embedCanBeTapped", true);
        g1Var.b("headerColor", false);
        g1Var.b("headerText", false);
        g1Var.b("resolvingGradientEnd", true);
        g1Var.b("resolvingGradientStart", true);
        g1Var.b("splashHasRadialGradient", true);
        g1Var.b("splashOpacity", true);
        g1Var.b("splashUrl", true);
        g1Var.b("inviteSplash", true);
        g1Var.b("subtitle", true);
        g1Var.b("subtitleColor", true);
        g1Var.b("thumbnailBackgroundColor", true);
        g1Var.b("thumbnailCornerRadius", true);
        g1Var.b("thumbnailText", true);
        g1Var.b("thumbnailUrl", true);
        g1Var.b("titleColor", true);
        g1Var.b("titleText", true);
        g1Var.b("type", true);
        g1Var.b("extendedType", true);
        g1Var.b("memberText", true);
        g1Var.b("onlineText", true);
        g1Var.b("bannerColor", false);
        g1Var.b("bannerColorSecondary", false);
        g1Var.b("hasProfileOverflow", false);
        g1Var.b("badgeIconUrl", true);
        g1Var.b("establishedText", true);
        g1Var.b("roles", true);
        g1Var.b("rolesHeadingText", true);
        descriptor = g1Var;
    }

    private GuildProfileInviteEmbedImpl$$serializer() {
    }

    @Override // or.f0
    @NotNull
    public final KSerializer[] childSerializers() {
        Lazy[] lazyArr = GuildProfileInviteEmbedImpl.$childSerializers;
        m0 m0Var = m0.f17573a;
        KSerializer kSerializerP = b.p(m0Var);
        KSerializer kSerializerP2 = b.p(m0Var);
        KSerializer kSerializerP3 = b.p(m0Var);
        s1 s1Var = s1.f17602a;
        KSerializer kSerializerP4 = b.p(s1Var);
        KSerializer kSerializerP5 = b.p(m0Var);
        KSerializer kSerializerP6 = b.p(s1Var);
        g gVar = g.f17537a;
        return new KSerializer[]{kSerializerP, kSerializerP2, kSerializerP3, kSerializerP4, kSerializerP5, kSerializerP6, m0Var, m0Var, b.p(gVar), b.p(gVar), m0Var, b.p(s1Var), b.p(m0Var), b.p(m0Var), b.p(gVar), b.p(m0Var), b.p(s1Var), b.p(s1Var), b.p(s1Var), b.p(m0Var), b.p(m0Var), b.p(m0Var), b.p(s1Var), b.p(s1Var), b.p(m0Var), b.p(s1Var), b.p(InviteType.Serializer.INSTANCE), CodedLinkExtendedType.Serializer.INSTANCE, b.p(s1Var), b.p(s1Var), m0Var, m0Var, gVar, b.p(s1Var), b.p(s1Var), b.p((KSerializer) lazyArr[35].getValue()), b.p(s1Var)};
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public final GuildProfileInviteEmbedImpl deserialize(@NotNull Decoder decoder) {
        Integer num;
        String str;
        String str2;
        int i7;
        String str3;
        Integer num2;
        String str4;
        List list;
        String str5;
        String str6;
        String str7;
        CodedLinkExtendedType codedLinkExtendedType;
        String str8;
        InviteType inviteType;
        Integer num3;
        Integer num4;
        String str9;
        String str10;
        String str11;
        Integer num5;
        Integer num6;
        Integer num7;
        Integer num8;
        String str12;
        Integer num9;
        Integer num10;
        String str13;
        Integer num11;
        String str14;
        Boolean bool;
        Boolean bool2;
        int i10;
        boolean z5;
        int i11;
        int i12;
        Boolean bool3;
        int i13;
        int i14;
        int i15;
        int i16;
        int i17;
        int i18;
        int i19;
        int i20;
        int i21;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        Lazy[] lazyArr = GuildProfileInviteEmbedImpl.$childSerializers;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            m0 m0Var = m0.f17573a;
            Integer num12 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, m0Var, null);
            Integer num13 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, m0Var, null);
            Integer num14 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, m0Var, null);
            s1 s1Var = s1.f17602a;
            String str15 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, s1Var, null);
            Integer num15 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, m0Var, null);
            String str16 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, s1Var, null);
            int iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 6);
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 7);
            g gVar = g.f17537a;
            Boolean bool4 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, gVar, null);
            Boolean bool5 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, gVar, null);
            int iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 10);
            String str17 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, s1Var, null);
            Integer num16 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, m0Var, null);
            Integer num17 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, m0Var, null);
            Boolean bool6 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, gVar, null);
            Integer num18 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, m0Var, null);
            String str18 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, s1Var, null);
            String str19 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, s1Var, null);
            String str20 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, s1Var, null);
            Integer num19 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, m0Var, null);
            Integer num20 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, m0Var, null);
            Integer num21 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, m0Var, null);
            String str21 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, s1Var, null);
            String str22 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, s1Var, null);
            Integer num22 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, m0Var, null);
            String str23 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, s1Var, null);
            InviteType inviteType2 = (InviteType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, InviteType.Serializer.INSTANCE, null);
            CodedLinkExtendedType codedLinkExtendedType2 = (CodedLinkExtendedType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 27, CodedLinkExtendedType.Serializer.INSTANCE, null);
            String str24 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, s1Var, null);
            String str25 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, s1Var, null);
            int iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 30);
            int iDecodeIntElement5 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 31);
            boolean zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 32);
            String str26 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, s1Var, null);
            String str27 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 34, s1Var, null);
            list = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 35, (DeserializationStrategy) lazyArr[35].getValue(), null);
            str4 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 36, s1Var, null);
            i11 = iDecodeIntElement2;
            i12 = iDecodeIntElement;
            str14 = str16;
            str13 = str15;
            bool = bool4;
            num11 = num15;
            num10 = num14;
            num9 = num13;
            i7 = -1;
            i13 = iDecodeIntElement4;
            num5 = num18;
            str5 = str24;
            num = num12;
            str6 = str25;
            i14 = iDecodeIntElement5;
            codedLinkExtendedType = codedLinkExtendedType2;
            z5 = zDecodeBooleanElement;
            inviteType = inviteType2;
            num6 = num22;
            str3 = str23;
            str = str22;
            str2 = str21;
            num2 = num21;
            num3 = num20;
            num4 = num19;
            str9 = str20;
            str10 = str19;
            str7 = str26;
            str11 = str18;
            bool3 = bool6;
            str8 = str27;
            num7 = num17;
            num8 = num16;
            str12 = str17;
            i10 = iDecodeIntElement3;
            bool2 = bool5;
            i15 = 31;
        } else {
            String str28 = null;
            int i22 = 0;
            boolean z6 = false;
            int i23 = 0;
            int i24 = 0;
            int i25 = 0;
            int iDecodeIntElement6 = 0;
            int iDecodeIntElement7 = 0;
            int i26 = 0;
            boolean z7 = true;
            String str29 = null;
            InviteType inviteType3 = null;
            Integer num23 = null;
            String str30 = null;
            String str31 = null;
            Integer num24 = null;
            String str32 = null;
            Integer num25 = null;
            String str33 = null;
            List list2 = null;
            String str34 = null;
            String str35 = null;
            CodedLinkExtendedType codedLinkExtendedType3 = null;
            Integer num26 = null;
            Integer num27 = null;
            Integer num28 = null;
            String str36 = null;
            Integer num29 = null;
            String str37 = null;
            Boolean bool7 = null;
            Boolean bool8 = null;
            String str38 = null;
            Integer num30 = null;
            Integer num31 = null;
            Boolean bool9 = null;
            Integer num32 = null;
            String str39 = null;
            String str40 = null;
            String str41 = null;
            Integer num33 = null;
            while (z7) {
                Integer num34 = num24;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        InviteType inviteType4 = inviteType3;
                        num23 = num23;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        i16 = i25;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num34 = num34;
                        Unit unit = Unit.f14616a;
                        z7 = false;
                        str29 = str29;
                        inviteType3 = inviteType4;
                        i19 = i16;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 0:
                        String str42 = str29;
                        inviteType3 = inviteType3;
                        num23 = num23;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num27 = num27;
                        Integer num35 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 0, m0.f17573a, num26);
                        i17 = i25 | 1;
                        Unit unit2 = Unit.f14616a;
                        num26 = num35;
                        str29 = str42;
                        num24 = num34;
                        i19 = i17;
                        inviteType3 = inviteType3;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 1:
                        InviteType inviteType5 = inviteType3;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        num28 = num28;
                        Integer num36 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, m0.f17573a, num27);
                        i18 = i25 | 2;
                        Unit unit3 = Unit.f14616a;
                        num27 = num36;
                        str29 = str29;
                        inviteType3 = inviteType5;
                        num24 = num34;
                        i19 = i18;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 2:
                        String str43 = str29;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        Integer num37 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, m0.f17573a, num28);
                        i17 = i25 | 4;
                        Unit unit4 = Unit.f14616a;
                        num28 = num37;
                        str29 = str43;
                        num24 = num34;
                        i19 = i17;
                        inviteType3 = inviteType3;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 3:
                        InviteType inviteType6 = inviteType3;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        num29 = num29;
                        String str44 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, s1.f17602a, str36);
                        i18 = i25 | 8;
                        Unit unit5 = Unit.f14616a;
                        str36 = str44;
                        str29 = str29;
                        inviteType3 = inviteType6;
                        num24 = num34;
                        num27 = num27;
                        num28 = num28;
                        i19 = i18;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 4:
                        String str45 = str29;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        str37 = str37;
                        Integer num38 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, m0.f17573a, num29);
                        i17 = i25 | 16;
                        Unit unit6 = Unit.f14616a;
                        num29 = num38;
                        str29 = str45;
                        num24 = num34;
                        num28 = num28;
                        str36 = str36;
                        i19 = i17;
                        inviteType3 = inviteType3;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 5:
                        InviteType inviteType7 = inviteType3;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        bool7 = bool7;
                        String str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, s1.f17602a, str37);
                        i18 = i25 | 32;
                        Unit unit7 = Unit.f14616a;
                        str37 = str46;
                        str29 = str29;
                        inviteType3 = inviteType7;
                        num24 = num34;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        i19 = i18;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 6:
                        int iDecodeIntElement8 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 6);
                        i16 = i25 | 64;
                        Unit unit8 = Unit.f14616a;
                        bool7 = bool7;
                        str29 = str29;
                        inviteType3 = inviteType3;
                        i24 = iDecodeIntElement8;
                        i19 = i16;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 7:
                        int iDecodeIntElement9 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 7);
                        i16 = i25 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_LAYOUT;
                        Unit unit9 = Unit.f14616a;
                        bool7 = bool7;
                        str29 = str29;
                        inviteType3 = inviteType3;
                        i23 = iDecodeIntElement9;
                        i19 = i16;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 8:
                        String str47 = str29;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        bool8 = bool8;
                        Boolean bool10 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, g.f17537a, bool7);
                        i17 = i25 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_EVENT_EMITTER;
                        Unit unit10 = Unit.f14616a;
                        bool7 = bool10;
                        str29 = str47;
                        num24 = num34;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        i19 = i17;
                        inviteType3 = inviteType3;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 9:
                        InviteType inviteType8 = inviteType3;
                        num30 = num30;
                        num31 = num31;
                        str38 = str38;
                        Boolean bool11 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, g.f17537a, bool8);
                        i18 = i25 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_PADDING;
                        Unit unit11 = Unit.f14616a;
                        bool8 = bool11;
                        str29 = str29;
                        inviteType3 = inviteType8;
                        num24 = num34;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        i19 = i18;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 10:
                        num23 = num23;
                        num30 = num30;
                        num31 = num31;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num34 = num34;
                        int iDecodeIntElement10 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 10);
                        i16 = i25 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_OVERFLOW_INSET;
                        Unit unit12 = Unit.f14616a;
                        str38 = str38;
                        str29 = str29;
                        inviteType3 = inviteType3;
                        i22 = iDecodeIntElement10;
                        bool7 = bool7;
                        bool8 = bool8;
                        i19 = i16;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 11:
                        String str48 = str29;
                        num31 = num31;
                        num30 = num30;
                        String str49 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, s1.f17602a, str38);
                        i17 = i25 | RecyclerView.ItemAnimator.FLAG_MOVED;
                        Unit unit13 = Unit.f14616a;
                        str38 = str49;
                        str29 = str48;
                        num24 = num34;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        i19 = i17;
                        inviteType3 = inviteType3;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 12:
                        InviteType inviteType9 = inviteType3;
                        num31 = num31;
                        Integer num39 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, m0.f17573a, num30);
                        i18 = i25 | RecyclerView.ItemAnimator.FLAG_APPEARED_IN_PRE_LAYOUT;
                        Unit unit14 = Unit.f14616a;
                        num30 = num39;
                        str29 = str29;
                        inviteType3 = inviteType9;
                        num24 = num34;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        i19 = i18;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 13:
                        String str50 = str29;
                        Integer num40 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, m0.f17573a, num31);
                        i17 = i25 | 8192;
                        Unit unit15 = Unit.f14616a;
                        num31 = num40;
                        str29 = str50;
                        num24 = num34;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        i19 = i17;
                        inviteType3 = inviteType3;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 14:
                        str39 = str39;
                        num32 = num32;
                        Boolean bool12 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, g.f17537a, bool9);
                        i16 = i25 | 16384;
                        Unit unit16 = Unit.f14616a;
                        bool9 = bool12;
                        num23 = num23;
                        str29 = str29;
                        inviteType3 = inviteType3;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        i19 = i16;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 15:
                        str39 = str39;
                        Integer num41 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, m0.f17573a, num32);
                        i16 = i25 | PeerConnection.PORTALLOCATOR_ENABLE_ANY_ADDRESS_PORTS;
                        Unit unit17 = Unit.f14616a;
                        num32 = num41;
                        num23 = num23;
                        str29 = str29;
                        inviteType3 = inviteType3;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        i19 = i16;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 16:
                        String str51 = str29;
                        str41 = str41;
                        num33 = num33;
                        num34 = num34;
                        str40 = str40;
                        String str52 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, s1.f17602a, str39);
                        i16 = i25 | 65536;
                        Unit unit18 = Unit.f14616a;
                        str39 = str52;
                        num23 = num23;
                        str29 = str51;
                        inviteType3 = inviteType3;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        num32 = num32;
                        i19 = i16;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 17:
                        InviteType inviteType10 = inviteType3;
                        num33 = num33;
                        num34 = num34;
                        str41 = str41;
                        String str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, s1.f17602a, str40);
                        i16 = i25 | 131072;
                        Unit unit19 = Unit.f14616a;
                        str40 = str53;
                        num23 = num23;
                        str29 = str29;
                        inviteType3 = inviteType10;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        num32 = num32;
                        str39 = str39;
                        i19 = i16;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 18:
                        String str54 = str29;
                        num34 = num34;
                        num33 = num33;
                        String str55 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, s1.f17602a, str41);
                        i16 = i25 | 262144;
                        Unit unit20 = Unit.f14616a;
                        str41 = str55;
                        num23 = num23;
                        str29 = str54;
                        inviteType3 = inviteType3;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        i19 = i16;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 19:
                        InviteType inviteType11 = inviteType3;
                        num34 = num34;
                        Integer num42 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, m0.f17573a, num33);
                        i16 = i25 | 524288;
                        Unit unit21 = Unit.f14616a;
                        num33 = num42;
                        num23 = num23;
                        str29 = str29;
                        inviteType3 = inviteType11;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        i19 = i16;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 20:
                        String str56 = str29;
                        Integer num43 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, m0.f17573a, num34);
                        int i27 = i25 | 1048576;
                        Unit unit22 = Unit.f14616a;
                        num24 = num43;
                        str29 = str56;
                        i19 = i27;
                        num23 = num23;
                        inviteType3 = inviteType3;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        str38 = str38;
                        num30 = num30;
                        num31 = num31;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 21:
                        Integer num44 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, m0.f17573a, num25);
                        int i28 = i25 | 2097152;
                        Unit unit23 = Unit.f14616a;
                        str29 = str29;
                        i19 = i28;
                        num25 = num44;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 22:
                        str31 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, s1.f17602a, str31);
                        i20 = i25 | 4194304;
                        Unit unit24 = Unit.f14616a;
                        num23 = num23;
                        i19 = i20;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num24 = num34;
                        num25 = num25;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 23:
                        str30 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, s1.f17602a, str30);
                        i20 = i25 | 8388608;
                        Unit unit25 = Unit.f14616a;
                        num23 = num23;
                        i19 = i20;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num24 = num34;
                        num25 = num25;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 24:
                        num23 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, m0.f17573a, num23);
                        i20 = i25 | PointerEventHelper.X_FLAG_SUPPORTS_HOVER;
                        Unit unit26 = Unit.f14616a;
                        num23 = num23;
                        i19 = i20;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num24 = num34;
                        num25 = num25;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 25:
                        String str57 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, s1.f17602a, str32);
                        Unit unit27 = Unit.f14616a;
                        i19 = i25 | 33554432;
                        num25 = num25;
                        str32 = str57;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 26:
                        inviteType3 = (InviteType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, InviteType.Serializer.INSTANCE, inviteType3);
                        i20 = i25 | 67108864;
                        Unit unit28 = Unit.f14616a;
                        num23 = num23;
                        i19 = i20;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num24 = num34;
                        num25 = num25;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 27:
                        CodedLinkExtendedType codedLinkExtendedType4 = (CodedLinkExtendedType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 27, CodedLinkExtendedType.Serializer.INSTANCE, codedLinkExtendedType3);
                        Unit unit29 = Unit.f14616a;
                        i19 = i25 | 134217728;
                        num25 = num25;
                        codedLinkExtendedType3 = codedLinkExtendedType4;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 28:
                        String str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, s1.f17602a, str28);
                        Unit unit30 = Unit.f14616a;
                        i19 = i25 | 268435456;
                        num25 = num25;
                        str28 = str58;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 29:
                        String str59 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, s1.f17602a, str34);
                        Unit unit31 = Unit.f14616a;
                        i19 = i25 | 536870912;
                        num25 = num25;
                        str34 = str59;
                        num24 = num34;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 30:
                        iDecodeIntElement6 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 30);
                        i21 = i25 | 1073741824;
                        Unit unit32 = Unit.f14616a;
                        num23 = num23;
                        i19 = i21;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num24 = num34;
                        num25 = num25;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 31:
                        iDecodeIntElement7 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 31);
                        i21 = i25 | Integer.MIN_VALUE;
                        Unit unit33 = Unit.f14616a;
                        num23 = num23;
                        i19 = i21;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num24 = num34;
                        num25 = num25;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 32:
                        boolean zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 32);
                        i26 |= 1;
                        Unit unit34 = Unit.f14616a;
                        z6 = zDecodeBooleanElement2;
                        i19 = i25;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num24 = num34;
                        num25 = num25;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 33:
                        String str60 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, s1.f17602a, str35);
                        i26 |= 2;
                        Unit unit35 = Unit.f14616a;
                        str35 = str60;
                        i19 = i25;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num24 = num34;
                        num25 = num25;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 34:
                        str29 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 34, s1.f17602a, str29);
                        i26 |= 4;
                        Unit unit36 = Unit.f14616a;
                        i19 = i25;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num24 = num34;
                        num25 = num25;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 35:
                        List list3 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 35, (DeserializationStrategy) lazyArr[35].getValue(), list2);
                        i26 |= 8;
                        Unit unit37 = Unit.f14616a;
                        list2 = list3;
                        i19 = i25;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num24 = num34;
                        num25 = num25;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    case 36:
                        String str61 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 36, s1.f17602a, str33);
                        i26 |= 16;
                        Unit unit38 = Unit.f14616a;
                        str33 = str61;
                        i19 = i25;
                        num32 = num32;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num24 = num34;
                        num25 = num25;
                        i25 = i19;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str39 = str39;
                        num32 = num32;
                        num23 = num23;
                        num31 = num31;
                        num30 = num30;
                        str38 = str38;
                        num27 = num27;
                        num28 = num28;
                        str36 = str36;
                        num29 = num29;
                        str37 = str37;
                        bool7 = bool7;
                        bool8 = bool8;
                        break;
                    default:
                        throw new j(iDecodeElementIndex);
                }
            }
            num = num26;
            str = str30;
            str2 = str31;
            i7 = i25;
            str3 = str32;
            num2 = num25;
            str4 = str33;
            list = list2;
            str5 = str28;
            str6 = str34;
            str7 = str35;
            codedLinkExtendedType = codedLinkExtendedType3;
            str8 = str29;
            inviteType = inviteType3;
            num3 = num24;
            num4 = num33;
            str9 = str41;
            str10 = str40;
            str11 = str39;
            num5 = num32;
            num6 = num23;
            num7 = num31;
            num8 = num30;
            str12 = str38;
            num9 = num27;
            num10 = num28;
            str13 = str36;
            num11 = num29;
            str14 = str37;
            bool = bool7;
            bool2 = bool8;
            i10 = i22;
            z5 = z6;
            i11 = i23;
            i12 = i24;
            bool3 = bool9;
            i13 = iDecodeIntElement6;
            i14 = iDecodeIntElement7;
            i15 = i26;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new GuildProfileInviteEmbedImpl(i7, i15, num, num9, num10, str13, num11, str14, i12, i11, bool, bool2, i10, str12, num8, num7, bool3, num5, str11, str10, str9, num4, num3, num2, str2, str, num6, str3, inviteType, codedLinkExtendedType, str5, str6, i13, i14, z5, str7, str8, list, str4, (SerializationConstructorMarker) null);
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.KSerializer
    public final void serialize(@NotNull Encoder encoder, @NotNull GuildProfileInviteEmbedImpl value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        GuildProfileInviteEmbedImpl.write$Self$chat_release(value, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }

    @Override // or.f0
    @NotNull
    public KSerializer[] typeParametersSerializers() {
        return e1.f17528b;
    }
}
