package com.discord.chat.bridge.codedlinks;

import androidx.recyclerview.widget.RecyclerView;
import com.discord.notifications.renderer.NotificationRenderer;
import com.facebook.imagepipeline.nativecode.b;
import com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem;
import com.facebook.react.uimanager.ViewProps;
import com.facebook.react.uimanager.events.PointerEventHelper;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kr.j;
import or.e1;
import or.f0;
import or.g;
import or.g1;
import or.m0;
import or.s1;
import org.jetbrains.annotations.NotNull;
import org.webrtc.PeerConnection;
import rn.d;

/* JADX INFO: loaded from: classes.dex */
@Metadata(d1 = {"\u0000:\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0005\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u001d\u0010\t\u001a\u00020\b2\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\u0007\u001a\u00020\u0002¢\u0006\u0004\b\t\u0010\nJ\u0015\u0010\r\u001a\u00020\u00022\u0006\u0010\f\u001a\u00020\u000b¢\u0006\u0004\b\r\u0010\u000eJ\u0017\u0010\u0011\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00100\u000f¢\u0006\u0004\b\u0011\u0010\u0012R\u0017\u0010\u0014\u001a\u00020\u00138\u0006¢\u0006\f\n\u0004\b\u0014\u0010\u0015\u001a\u0004\b\u0016\u0010\u0017¨\u0006\u0018"}, d2 = {"com/discord/chat/bridge/codedlinks/GuildInviteEmbedImpl.$serializer", "Lor/f0;", "Lcom/discord/chat/bridge/codedlinks/GuildInviteEmbedImpl;", "<init>", "()V", "Lkotlinx/serialization/encoding/Encoder;", "encoder", "value", "", "serialize", "(Lkotlinx/serialization/encoding/Encoder;Lcom/discord/chat/bridge/codedlinks/GuildInviteEmbedImpl;)V", "Lkotlinx/serialization/encoding/Decoder;", "decoder", "deserialize", "(Lkotlinx/serialization/encoding/Decoder;)Lcom/discord/chat/bridge/codedlinks/GuildInviteEmbedImpl;", "", "Lkotlinx/serialization/KSerializer;", "childSerializers", "()[Lkotlinx/serialization/KSerializer;", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "chat_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
@d
public /* synthetic */ class GuildInviteEmbedImpl$$serializer implements f0 {

    @NotNull
    public static final GuildInviteEmbedImpl$$serializer INSTANCE;

    @NotNull
    private static final SerialDescriptor descriptor;

    static {
        GuildInviteEmbedImpl$$serializer guildInviteEmbedImpl$$serializer = new GuildInviteEmbedImpl$$serializer();
        INSTANCE = guildInviteEmbedImpl$$serializer;
        g1 g1Var = new g1("com.discord.chat.bridge.codedlinks.GuildInviteEmbedImpl", guildInviteEmbedImpl$$serializer, 32);
        g1Var.b(ViewProps.BACKGROUND_COLOR, false);
        g1Var.b(ViewProps.BORDER_COLOR, false);
        g1Var.b("headerColor", false);
        g1Var.b("headerText", false);
        g1Var.b("type", false);
        g1Var.b("acceptLabelBackgroundColor", true);
        g1Var.b("acceptLabelBorderColor", true);
        g1Var.b("acceptLabelColor", true);
        g1Var.b("acceptLabelText", true);
        g1Var.b("bodyText", true);
        g1Var.b("bodyTextColor", true);
        g1Var.b("canBeAccepted", true);
        g1Var.b("channelIcon", true);
        g1Var.b(NotificationRenderer.CHANNEL_NAME, true);
        g1Var.b("embedCanBeTapped", true);
        g1Var.b("memberText", true);
        g1Var.b("onlineText", true);
        g1Var.b("resolvingGradientEnd", true);
        g1Var.b("resolvingGradientStart", true);
        g1Var.b("splashHasRadialGradient", true);
        g1Var.b("splashOpacity", true);
        g1Var.b("splashUrl", true);
        g1Var.b("inviteSplash", true);
        g1Var.b("subtitle", true);
        g1Var.b("subtitleColor", true);
        g1Var.b("thumbnailBackgroundColor", true);
        g1Var.b("thumbnailCornerRadius", true);
        g1Var.b("thumbnailText", true);
        g1Var.b("thumbnailUrl", true);
        g1Var.b("titleColor", true);
        g1Var.b("titleText", true);
        g1Var.b("badgeIconUrl", true);
        descriptor = g1Var;
    }

    private GuildInviteEmbedImpl$$serializer() {
    }

    @Override // or.f0
    @NotNull
    public final KSerializer[] childSerializers() {
        m0 m0Var = m0.f17573a;
        s1 s1Var = s1.f17602a;
        KSerializer kSerializerP = b.p(s1Var);
        KSerializer kSerializerP2 = b.p(m0Var);
        KSerializer kSerializerP3 = b.p(m0Var);
        KSerializer kSerializerP4 = b.p(m0Var);
        KSerializer kSerializerP5 = b.p(s1Var);
        KSerializer kSerializerP6 = b.p(s1Var);
        KSerializer kSerializerP7 = b.p(m0Var);
        g gVar = g.f17537a;
        return new KSerializer[]{m0Var, m0Var, m0Var, kSerializerP, InviteType.Serializer.INSTANCE, kSerializerP2, kSerializerP3, kSerializerP4, kSerializerP5, kSerializerP6, kSerializerP7, b.p(gVar), b.p(s1Var), b.p(s1Var), b.p(gVar), b.p(s1Var), b.p(s1Var), b.p(m0Var), b.p(m0Var), b.p(gVar), b.p(m0Var), b.p(s1Var), b.p(s1Var), b.p(s1Var), b.p(m0Var), b.p(m0Var), b.p(m0Var), b.p(s1Var), b.p(s1Var), b.p(m0Var), b.p(s1Var), b.p(s1Var)};
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public final GuildInviteEmbedImpl deserialize(@NotNull Decoder decoder) {
        String str;
        String str2;
        String str3;
        String str4;
        String str5;
        Integer num;
        Integer num2;
        Integer num3;
        String str6;
        String str7;
        Integer num4;
        int i7;
        Integer num5;
        Boolean bool;
        Integer num6;
        Integer num7;
        String str8;
        String str9;
        String str10;
        String str11;
        String str12;
        InviteType inviteType;
        Integer num8;
        Integer num9;
        Integer num10;
        String str13;
        String str14;
        Integer num11;
        Boolean bool2;
        int i10;
        int i11;
        int i12;
        Boolean bool3;
        int i13;
        int i14;
        int i15;
        int i16;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        String str15 = null;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            int iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 0);
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 1);
            int iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
            s1 s1Var = s1.f17602a;
            String str16 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, s1Var, null);
            InviteType inviteType2 = (InviteType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 4, InviteType.Serializer.INSTANCE, null);
            m0 m0Var = m0.f17573a;
            Integer num12 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, m0Var, null);
            Integer num13 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, m0Var, null);
            Integer num14 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, m0Var, null);
            String str17 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, s1Var, null);
            String str18 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, s1Var, null);
            Integer num15 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, m0Var, null);
            g gVar = g.f17537a;
            Boolean bool4 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, gVar, null);
            String str19 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, s1Var, null);
            String str20 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, s1Var, null);
            Boolean bool5 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, gVar, null);
            String str21 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, s1Var, null);
            String str22 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, s1Var, null);
            Integer num16 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, m0Var, null);
            Integer num17 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, m0Var, null);
            Boolean bool6 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, gVar, null);
            Integer num18 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, m0Var, null);
            String str23 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, s1Var, null);
            String str24 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, s1Var, null);
            String str25 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, s1Var, null);
            Integer num19 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, m0Var, null);
            Integer num20 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, m0Var, null);
            Integer num21 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, m0Var, null);
            String str26 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, s1Var, null);
            String str27 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, s1Var, null);
            Integer num22 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, m0Var, null);
            String str28 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, s1Var, null);
            str2 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, s1Var, null);
            num4 = num18;
            str13 = str17;
            i11 = iDecodeIntElement3;
            i12 = iDecodeIntElement2;
            i7 = -1;
            str3 = str28;
            num11 = num15;
            str14 = str18;
            num10 = num14;
            num9 = num13;
            num8 = num12;
            str = str16;
            num = num22;
            str5 = str27;
            str4 = str26;
            num5 = num21;
            num2 = num20;
            num3 = num19;
            str10 = str25;
            str6 = str24;
            str7 = str23;
            bool = bool6;
            num6 = num17;
            num7 = num16;
            str8 = str22;
            str9 = str21;
            bool3 = bool5;
            str11 = str20;
            str12 = str19;
            bool2 = bool4;
            i10 = iDecodeIntElement;
            inviteType = inviteType2;
        } else {
            boolean z5 = true;
            int i17 = 0;
            int i18 = 0;
            int i19 = 0;
            int i20 = 0;
            Integer num23 = null;
            Boolean bool7 = null;
            String str29 = null;
            String str30 = null;
            String str31 = null;
            String str32 = null;
            Integer num24 = null;
            Integer num25 = null;
            Integer num26 = null;
            String str33 = null;
            String str34 = null;
            Integer num27 = null;
            Integer num28 = null;
            String str35 = null;
            InviteType inviteType3 = null;
            Integer num29 = null;
            Integer num30 = null;
            Integer num31 = null;
            String str36 = null;
            String str37 = null;
            Integer num32 = null;
            Boolean bool8 = null;
            String str38 = null;
            String str39 = null;
            Boolean bool9 = null;
            String str40 = null;
            String str41 = null;
            Integer num33 = null;
            while (z5) {
                Integer num34 = num28;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        bool7 = bool7;
                        str29 = str29;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        str38 = str38;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        Unit unit = Unit.f14616a;
                        str35 = str35;
                        num23 = num23;
                        i13 = i20;
                        num28 = num34;
                        z5 = false;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 0:
                        bool7 = bool7;
                        str29 = str29;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        str38 = str38;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        int iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 0);
                        Unit unit2 = Unit.f14616a;
                        str35 = str35;
                        num23 = num23;
                        i13 = i20 | 1;
                        num28 = num34;
                        i17 = iDecodeIntElement4;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 1:
                        bool7 = bool7;
                        str29 = str29;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        str38 = str38;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        int iDecodeIntElement5 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 1);
                        Unit unit3 = Unit.f14616a;
                        str35 = str35;
                        num23 = num23;
                        i13 = i20 | 2;
                        num28 = num34;
                        i19 = iDecodeIntElement5;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 2:
                        bool7 = bool7;
                        str29 = str29;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        str38 = str38;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        int iDecodeIntElement6 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
                        Unit unit4 = Unit.f14616a;
                        str35 = str35;
                        num23 = num23;
                        i13 = i20 | 4;
                        num28 = num34;
                        i18 = iDecodeIntElement6;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 3:
                        Integer num35 = num23;
                        bool7 = bool7;
                        str29 = str29;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        str38 = str38;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        inviteType3 = inviteType3;
                        String str42 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, s1.f17602a, str35);
                        i14 = i20 | 8;
                        Unit unit5 = Unit.f14616a;
                        str35 = str42;
                        num23 = num35;
                        num28 = num34;
                        i13 = i14;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 4:
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        str38 = str38;
                        str39 = str39;
                        num29 = num29;
                        InviteType inviteType4 = (InviteType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 4, InviteType.Serializer.INSTANCE, inviteType3);
                        i15 = i20 | 16;
                        Unit unit6 = Unit.f14616a;
                        inviteType3 = inviteType4;
                        num23 = num23;
                        num28 = num34;
                        i13 = i15;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 5:
                        Integer num36 = num23;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        str38 = str38;
                        str39 = str39;
                        num30 = num30;
                        Integer num37 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, m0.f17573a, num29);
                        i14 = i20 | 32;
                        Unit unit7 = Unit.f14616a;
                        num29 = num37;
                        num23 = num36;
                        num28 = num34;
                        i13 = i14;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 6:
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        str38 = str38;
                        str39 = str39;
                        num31 = num31;
                        Integer num38 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, m0.f17573a, num30);
                        i15 = i20 | 64;
                        Unit unit8 = Unit.f14616a;
                        num30 = num38;
                        num23 = num23;
                        num28 = num34;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        i13 = i15;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 7:
                        Integer num39 = num23;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        str38 = str38;
                        str39 = str39;
                        str36 = str36;
                        Integer num40 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, m0.f17573a, num31);
                        i14 = i20 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_LAYOUT;
                        Unit unit9 = Unit.f14616a;
                        num31 = num40;
                        num23 = num39;
                        num28 = num34;
                        num29 = num29;
                        num30 = num30;
                        i13 = i14;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 8:
                        num32 = num32;
                        bool8 = bool8;
                        str38 = str38;
                        str39 = str39;
                        str37 = str37;
                        String str43 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, s1.f17602a, str36);
                        i15 = i20 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_EVENT_EMITTER;
                        Unit unit10 = Unit.f14616a;
                        str36 = str43;
                        num23 = num23;
                        num28 = num34;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        i13 = i15;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 9:
                        Integer num41 = num23;
                        bool8 = bool8;
                        str38 = str38;
                        str39 = str39;
                        num32 = num32;
                        String str44 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, s1.f17602a, str37);
                        i14 = i20 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_PADDING;
                        Unit unit11 = Unit.f14616a;
                        str37 = str44;
                        num23 = num41;
                        num28 = num34;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        i13 = i14;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 10:
                        str38 = str38;
                        str39 = str39;
                        bool8 = bool8;
                        Integer num42 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, m0.f17573a, num32);
                        i15 = i20 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_OVERFLOW_INSET;
                        Unit unit12 = Unit.f14616a;
                        num32 = num42;
                        num23 = num23;
                        num28 = num34;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        i13 = i15;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 11:
                        Integer num43 = num23;
                        str39 = str39;
                        str38 = str38;
                        Boolean bool10 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, g.f17537a, bool8);
                        i14 = i20 | RecyclerView.ItemAnimator.FLAG_MOVED;
                        Unit unit13 = Unit.f14616a;
                        bool8 = bool10;
                        num23 = num43;
                        num28 = num34;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        i13 = i14;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 12:
                        str39 = str39;
                        String str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, s1.f17602a, str38);
                        i15 = i20 | RecyclerView.ItemAnimator.FLAG_APPEARED_IN_PRE_LAYOUT;
                        Unit unit14 = Unit.f14616a;
                        str38 = str45;
                        num23 = num23;
                        num28 = num34;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        i13 = i15;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 13:
                        Integer num44 = num23;
                        String str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, s1.f17602a, str39);
                        i14 = i20 | 8192;
                        Unit unit15 = Unit.f14616a;
                        str39 = str46;
                        num23 = num44;
                        num28 = num34;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        str38 = str38;
                        i13 = i14;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 14:
                        str41 = str41;
                        str40 = str40;
                        Boolean bool11 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, g.f17537a, bool9);
                        int i21 = i20 | 16384;
                        Unit unit16 = Unit.f14616a;
                        i13 = i21;
                        num28 = num34;
                        bool9 = bool11;
                        str29 = str29;
                        num23 = num23;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 15:
                        str41 = str41;
                        String str47 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, s1.f17602a, str40);
                        int i22 = i20 | PeerConnection.PORTALLOCATOR_ENABLE_ANY_ADDRESS_PORTS;
                        Unit unit17 = Unit.f14616a;
                        i13 = i22;
                        num28 = num34;
                        str40 = str47;
                        str29 = str29;
                        num23 = num23;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 16:
                        Integer num45 = num23;
                        bool7 = bool7;
                        num33 = num33;
                        String str48 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, s1.f17602a, str41);
                        int i23 = i20 | 65536;
                        Unit unit18 = Unit.f14616a;
                        i13 = i23;
                        num28 = num34;
                        str41 = str48;
                        str29 = str29;
                        num23 = num45;
                        str40 = str40;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 17:
                        bool7 = bool7;
                        Integer num46 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, m0.f17573a, num33);
                        int i24 = i20 | 131072;
                        Unit unit19 = Unit.f14616a;
                        i13 = i24;
                        num28 = num34;
                        num33 = num46;
                        str29 = str29;
                        num23 = num23;
                        str40 = str40;
                        str41 = str41;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 18:
                        Integer num47 = num23;
                        bool7 = bool7;
                        Integer num48 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, m0.f17573a, num34);
                        int i25 = i20 | 262144;
                        Unit unit20 = Unit.f14616a;
                        str29 = str29;
                        i13 = i25;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        str38 = str38;
                        str39 = str39;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num28 = num48;
                        num23 = num47;
                        str35 = str35;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 19:
                        Boolean bool12 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, g.f17537a, bool7);
                        int i26 = i20 | 524288;
                        Unit unit21 = Unit.f14616a;
                        bool7 = bool12;
                        str29 = str29;
                        i13 = i26;
                        num23 = num23;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num28 = num34;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 20:
                        num27 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, m0.f17573a, num27);
                        i16 = i20 | 1048576;
                        Unit unit22 = Unit.f14616a;
                        str29 = str29;
                        i13 = i16;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num28 = num34;
                        bool7 = bool7;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 21:
                        str34 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, s1.f17602a, str34);
                        i16 = i20 | 2097152;
                        Unit unit23 = Unit.f14616a;
                        str29 = str29;
                        i13 = i16;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num28 = num34;
                        bool7 = bool7;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 22:
                        str33 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, s1.f17602a, str33);
                        i16 = i20 | 4194304;
                        Unit unit24 = Unit.f14616a;
                        str29 = str29;
                        i13 = i16;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num28 = num34;
                        bool7 = bool7;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 23:
                        str29 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, s1.f17602a, str29);
                        i16 = i20 | 8388608;
                        Unit unit25 = Unit.f14616a;
                        str29 = str29;
                        i13 = i16;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num28 = num34;
                        bool7 = bool7;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 24:
                        num26 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, m0.f17573a, num26);
                        i16 = i20 | PointerEventHelper.X_FLAG_SUPPORTS_HOVER;
                        Unit unit26 = Unit.f14616a;
                        str29 = str29;
                        i13 = i16;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num28 = num34;
                        bool7 = bool7;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 25:
                        num25 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, m0.f17573a, num25);
                        i16 = i20 | 33554432;
                        Unit unit27 = Unit.f14616a;
                        str29 = str29;
                        i13 = i16;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num28 = num34;
                        bool7 = bool7;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 26:
                        num23 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, m0.f17573a, num23);
                        i16 = i20 | 67108864;
                        Unit unit28 = Unit.f14616a;
                        str29 = str29;
                        i13 = i16;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num28 = num34;
                        bool7 = bool7;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 27:
                        str32 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, s1.f17602a, str32);
                        i16 = i20 | 134217728;
                        Unit unit29 = Unit.f14616a;
                        str29 = str29;
                        i13 = i16;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num28 = num34;
                        bool7 = bool7;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 28:
                        str15 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, s1.f17602a, str15);
                        i16 = i20 | 268435456;
                        Unit unit30 = Unit.f14616a;
                        str29 = str29;
                        i13 = i16;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num28 = num34;
                        bool7 = bool7;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 29:
                        num24 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, m0.f17573a, num24);
                        i16 = i20 | 536870912;
                        Unit unit31 = Unit.f14616a;
                        str29 = str29;
                        i13 = i16;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num28 = num34;
                        bool7 = bool7;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 30:
                        str31 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, s1.f17602a, str31);
                        i16 = i20 | 1073741824;
                        Unit unit32 = Unit.f14616a;
                        str29 = str29;
                        i13 = i16;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num28 = num34;
                        bool7 = bool7;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    case 31:
                        str30 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, s1.f17602a, str30);
                        i16 = i20 | Integer.MIN_VALUE;
                        Unit unit33 = Unit.f14616a;
                        str29 = str29;
                        i13 = i16;
                        str40 = str40;
                        str41 = str41;
                        num33 = num33;
                        num28 = num34;
                        bool7 = bool7;
                        str35 = str35;
                        bool7 = bool7;
                        i20 = i13;
                        num33 = num33;
                        str41 = str41;
                        str40 = str40;
                        str29 = str29;
                        str39 = str39;
                        str38 = str38;
                        inviteType3 = inviteType3;
                        num29 = num29;
                        num30 = num30;
                        num31 = num31;
                        str36 = str36;
                        str37 = str37;
                        num32 = num32;
                        bool8 = bool8;
                        break;
                    default:
                        throw new j(iDecodeElementIndex);
                }
            }
            str = str35;
            str2 = str30;
            str3 = str31;
            str4 = str32;
            str5 = str15;
            num = num24;
            num2 = num25;
            num3 = num26;
            str6 = str33;
            str7 = str34;
            num4 = num27;
            i7 = i20;
            num5 = num23;
            bool = bool7;
            num6 = num28;
            num7 = num33;
            str8 = str41;
            str9 = str40;
            str10 = str29;
            str11 = str39;
            str12 = str38;
            inviteType = inviteType3;
            num8 = num29;
            num9 = num30;
            num10 = num31;
            str13 = str36;
            str14 = str37;
            num11 = num32;
            bool2 = bool8;
            i10 = i17;
            i11 = i18;
            i12 = i19;
            bool3 = bool9;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new GuildInviteEmbedImpl(i7, 0, i10, i12, i11, str, inviteType, num8, num9, num10, str13, str14, num11, bool2, str12, str11, bool3, str9, str8, num7, num6, bool, num4, str7, str6, str10, num3, num2, num5, str4, str5, num, str3, str2, null);
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.KSerializer
    public final void serialize(@NotNull Encoder encoder, @NotNull GuildInviteEmbedImpl value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        GuildInviteEmbedImpl.write$Self$chat_release(value, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }

    @Override // or.f0
    @NotNull
    public KSerializer[] typeParametersSerializers() {
        return e1.f17528b;
    }
}
