package com.discord.chat.bridge.codedlinks;

import androidx.recyclerview.widget.RecyclerView;
import com.discord.misc.utilities.chat_view_types.ChatViewRecyclerTypes;
import com.discord.notifications.renderer.NotificationRenderer;
import com.facebook.imagepipeline.nativecode.b;
import com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem;
import com.facebook.react.uimanager.ViewProps;
import com.facebook.react.uimanager.events.PointerEventHelper;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kr.j;
import or.e1;
import or.f0;
import or.g;
import or.g1;
import or.m0;
import or.s1;
import org.jetbrains.annotations.NotNull;
import org.webrtc.PeerConnection;
import rn.d;

/* JADX INFO: loaded from: classes.dex */
@Metadata(d1 = {"\u0000:\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0005\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u001d\u0010\t\u001a\u00020\b2\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\u0007\u001a\u00020\u0002¢\u0006\u0004\b\t\u0010\nJ\u0015\u0010\r\u001a\u00020\u00022\u0006\u0010\f\u001a\u00020\u000b¢\u0006\u0004\b\r\u0010\u000eJ\u0017\u0010\u0011\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00100\u000f¢\u0006\u0004\b\u0011\u0010\u0012R\u0017\u0010\u0014\u001a\u00020\u00138\u0006¢\u0006\f\n\u0004\b\u0014\u0010\u0015\u001a\u0004\b\u0016\u0010\u0017¨\u0006\u0018"}, d2 = {"com/discord/chat/bridge/codedlinks/GuildInviteDisabledEmbedImpl.$serializer", "Lor/f0;", "Lcom/discord/chat/bridge/codedlinks/GuildInviteDisabledEmbedImpl;", "<init>", "()V", "Lkotlinx/serialization/encoding/Encoder;", "encoder", "value", "", "serialize", "(Lkotlinx/serialization/encoding/Encoder;Lcom/discord/chat/bridge/codedlinks/GuildInviteDisabledEmbedImpl;)V", "Lkotlinx/serialization/encoding/Decoder;", "decoder", "deserialize", "(Lkotlinx/serialization/encoding/Decoder;)Lcom/discord/chat/bridge/codedlinks/GuildInviteDisabledEmbedImpl;", "", "Lkotlinx/serialization/KSerializer;", "childSerializers", "()[Lkotlinx/serialization/KSerializer;", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "chat_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
@d
public /* synthetic */ class GuildInviteDisabledEmbedImpl$$serializer implements f0 {

    @NotNull
    public static final GuildInviteDisabledEmbedImpl$$serializer INSTANCE;

    @NotNull
    private static final SerialDescriptor descriptor;

    static {
        GuildInviteDisabledEmbedImpl$$serializer guildInviteDisabledEmbedImpl$$serializer = new GuildInviteDisabledEmbedImpl$$serializer();
        INSTANCE = guildInviteDisabledEmbedImpl$$serializer;
        g1 g1Var = new g1("com.discord.chat.bridge.codedlinks.GuildInviteDisabledEmbedImpl", guildInviteDisabledEmbedImpl$$serializer, 38);
        g1Var.b(ViewProps.BACKGROUND_COLOR, false);
        g1Var.b(ViewProps.BORDER_COLOR, false);
        g1Var.b("headerColor", false);
        g1Var.b("headerText", false);
        g1Var.b("type", false);
        g1Var.b("titleText", false);
        g1Var.b("subtitle", false);
        g1Var.b("helpCenterArticleLabel", false);
        g1Var.b("helpCenterArticleURL", false);
        g1Var.b("acceptLabelBackgroundColor", true);
        g1Var.b("acceptLabelBorderColor", true);
        g1Var.b("acceptLabelColor", true);
        g1Var.b("acceptLabelText", true);
        g1Var.b("bodyText", true);
        g1Var.b("bodyTextColor", true);
        g1Var.b("canBeAccepted", true);
        g1Var.b("channelIcon", true);
        g1Var.b(NotificationRenderer.CHANNEL_NAME, true);
        g1Var.b("embedCanBeTapped", true);
        g1Var.b("memberText", true);
        g1Var.b("onlineText", true);
        g1Var.b("resolvingGradientEnd", true);
        g1Var.b("resolvingGradientStart", true);
        g1Var.b("splashHasRadialGradient", true);
        g1Var.b("splashOpacity", true);
        g1Var.b("splashUrl", true);
        g1Var.b("inviteSplash", true);
        g1Var.b("subtitleColor", true);
        g1Var.b("thumbnailBackgroundColor", true);
        g1Var.b("thumbnailCornerRadius", true);
        g1Var.b("thumbnailText", true);
        g1Var.b("thumbnailUrl", true);
        g1Var.b("titleColor", true);
        g1Var.b("extendedType", true);
        g1Var.b("guildName", false);
        g1Var.b("guildIcon", true);
        g1Var.b("headerIcon", true);
        g1Var.b("badgeIconUrl", true);
        descriptor = g1Var;
    }

    private GuildInviteDisabledEmbedImpl$$serializer() {
    }

    @Override // or.f0
    @NotNull
    public final KSerializer[] childSerializers() {
        m0 m0Var = m0.f17573a;
        s1 s1Var = s1.f17602a;
        KSerializer kSerializerP = b.p(m0Var);
        KSerializer kSerializerP2 = b.p(m0Var);
        KSerializer kSerializerP3 = b.p(m0Var);
        KSerializer kSerializerP4 = b.p(s1Var);
        KSerializer kSerializerP5 = b.p(s1Var);
        KSerializer kSerializerP6 = b.p(m0Var);
        g gVar = g.f17537a;
        return new KSerializer[]{m0Var, m0Var, m0Var, s1Var, InviteType.Serializer.INSTANCE, s1Var, s1Var, s1Var, s1Var, kSerializerP, kSerializerP2, kSerializerP3, kSerializerP4, kSerializerP5, kSerializerP6, b.p(gVar), b.p(s1Var), b.p(s1Var), b.p(gVar), b.p(s1Var), b.p(s1Var), b.p(m0Var), b.p(m0Var), b.p(gVar), b.p(m0Var), b.p(s1Var), b.p(s1Var), b.p(m0Var), b.p(m0Var), b.p(m0Var), b.p(s1Var), b.p(s1Var), b.p(m0Var), CodedLinkExtendedType.Serializer.INSTANCE, s1Var, b.p(s1Var), b.p(s1Var), b.p(s1Var)};
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public final GuildInviteDisabledEmbedImpl deserialize(@NotNull Decoder decoder) {
        InviteType inviteType;
        String str;
        String str2;
        int i7;
        Integer num;
        Integer num2;
        String str3;
        String str4;
        Integer num3;
        String str5;
        Integer num4;
        String str6;
        CodedLinkExtendedType codedLinkExtendedType;
        String str7;
        Boolean bool;
        Integer num5;
        Integer num6;
        String str8;
        String str9;
        Boolean bool2;
        String str10;
        String str11;
        Boolean bool3;
        Integer num7;
        String str12;
        int i10;
        int i11;
        String str13;
        String str14;
        String str15;
        String str16;
        String str17;
        Integer num8;
        Integer num9;
        Integer num10;
        String str18;
        int i12;
        int i13;
        Integer num11;
        String str19;
        int i14;
        int i15;
        int i16;
        int i17;
        int i18;
        int i19;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        String str20 = null;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            int iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 0);
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 1);
            int iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
            String strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
            InviteType inviteType2 = (InviteType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 4, InviteType.Serializer.INSTANCE, null);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
            String strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
            m0 m0Var = m0.f17573a;
            Integer num12 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, m0Var, null);
            Integer num13 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, m0Var, null);
            Integer num14 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, m0Var, null);
            s1 s1Var = s1.f17602a;
            String str21 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, s1Var, null);
            String str22 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, s1Var, null);
            Integer num15 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, m0Var, null);
            g gVar = g.f17537a;
            Boolean bool4 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, gVar, null);
            String str23 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, s1Var, null);
            String str24 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, s1Var, null);
            Boolean bool5 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, gVar, null);
            String str25 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, s1Var, null);
            String str26 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, s1Var, null);
            Integer num16 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, m0Var, null);
            Integer num17 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, m0Var, null);
            Boolean bool6 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, gVar, null);
            Integer num18 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, m0Var, null);
            String str27 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, s1Var, null);
            String str28 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, s1Var, null);
            Integer num19 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, m0Var, null);
            Integer num20 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, m0Var, null);
            Integer num21 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, m0Var, null);
            String str29 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, s1Var, null);
            String str30 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, s1Var, null);
            Integer num22 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, m0Var, null);
            CodedLinkExtendedType codedLinkExtendedType2 = (CodedLinkExtendedType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 33, CodedLinkExtendedType.Serializer.INSTANCE, null);
            String strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 34);
            String str31 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 35, s1Var, null);
            String str32 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 36, s1Var, null);
            str3 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 37, s1Var, null);
            i13 = 63;
            num = num18;
            str15 = strDecodeStringElement3;
            str14 = strDecodeStringElement2;
            str13 = strDecodeStringElement;
            inviteType = inviteType2;
            str17 = strDecodeStringElement5;
            i10 = iDecodeIntElement3;
            i11 = iDecodeIntElement2;
            str19 = strDecodeStringElement6;
            i7 = -1;
            num10 = num14;
            num9 = num13;
            str4 = str32;
            str5 = str31;
            codedLinkExtendedType = codedLinkExtendedType2;
            str6 = str30;
            str7 = str29;
            num2 = num21;
            num7 = num20;
            num3 = num19;
            str = str28;
            str2 = str27;
            bool = bool6;
            num4 = num22;
            num5 = num17;
            num6 = num16;
            str8 = str26;
            str9 = str25;
            bool2 = bool5;
            str10 = str24;
            str11 = str23;
            bool3 = bool4;
            num11 = num15;
            str12 = str22;
            str18 = str21;
            i12 = iDecodeIntElement;
            num8 = num12;
            str16 = strDecodeStringElement4;
        } else {
            boolean z5 = true;
            int iDecodeIntElement4 = 0;
            int iDecodeIntElement5 = 0;
            int i20 = 0;
            int i21 = 0;
            int i22 = 0;
            CodedLinkExtendedType codedLinkExtendedType3 = null;
            String str33 = null;
            Integer num23 = null;
            String str34 = null;
            String str35 = null;
            Boolean bool7 = null;
            Integer num24 = null;
            Integer num25 = null;
            String str36 = null;
            String str37 = null;
            Integer num26 = null;
            Integer num27 = null;
            String str38 = null;
            String strDecodeStringElement7 = null;
            String strDecodeStringElement8 = null;
            String strDecodeStringElement9 = null;
            String strDecodeStringElement10 = null;
            String strDecodeStringElement11 = null;
            InviteType inviteType3 = null;
            Integer num28 = null;
            Integer num29 = null;
            Integer num30 = null;
            String str39 = null;
            String str40 = null;
            Integer num31 = null;
            Boolean bool8 = null;
            String str41 = null;
            String str42 = null;
            Boolean bool9 = null;
            String str43 = null;
            String str44 = null;
            String str45 = null;
            Integer num32 = null;
            Integer num33 = null;
            while (z5) {
                Boolean bool10 = bool7;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        num23 = num23;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        str40 = str40;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        bool9 = bool9;
                        str43 = str43;
                        str45 = str45;
                        num32 = num32;
                        num33 = num33;
                        Unit unit = Unit.f14616a;
                        i14 = i22;
                        bool7 = bool10;
                        z5 = false;
                        inviteType3 = inviteType3;
                        num23 = num23;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 0:
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        str40 = str40;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        bool9 = bool9;
                        str43 = str43;
                        str45 = str45;
                        num32 = num32;
                        num33 = num33;
                        int iDecodeIntElement6 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 0);
                        Unit unit2 = Unit.f14616a;
                        i14 = i22 | 1;
                        bool7 = bool10;
                        num23 = num23;
                        i20 = iDecodeIntElement6;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 1:
                        iDecodeIntElement5 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 1);
                        i15 = i22 | 2;
                        Unit unit3 = Unit.f14616a;
                        i14 = i15;
                        bool7 = bool10;
                        num23 = num23;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 2:
                        iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
                        i15 = i22 | 4;
                        Unit unit4 = Unit.f14616a;
                        i14 = i15;
                        bool7 = bool10;
                        num23 = num23;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 3:
                        strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
                        i15 = i22 | 8;
                        Unit unit5 = Unit.f14616a;
                        i14 = i15;
                        bool7 = bool10;
                        num23 = num23;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 4:
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        num23 = num23;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        str40 = str40;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        bool9 = bool9;
                        str43 = str43;
                        str45 = str45;
                        num32 = num32;
                        num33 = num33;
                        num28 = num28;
                        InviteType inviteType4 = (InviteType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 4, InviteType.Serializer.INSTANCE, inviteType3);
                        i16 = i22 | 16;
                        Unit unit6 = Unit.f14616a;
                        inviteType3 = inviteType4;
                        bool7 = bool10;
                        i14 = i16;
                        num23 = num23;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 5:
                        strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 5);
                        i17 = i22 | 32;
                        Unit unit7 = Unit.f14616a;
                        i14 = i17;
                        bool7 = bool10;
                        num28 = num28;
                        num23 = num23;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 6:
                        strDecodeStringElement9 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 6);
                        i17 = i22 | 64;
                        Unit unit8 = Unit.f14616a;
                        i14 = i17;
                        bool7 = bool10;
                        num28 = num28;
                        num23 = num23;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 7:
                        strDecodeStringElement10 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 7);
                        i17 = i22 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_LAYOUT;
                        Unit unit9 = Unit.f14616a;
                        i14 = i17;
                        bool7 = bool10;
                        num28 = num28;
                        num23 = num23;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 8:
                        strDecodeStringElement11 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 8);
                        i17 = i22 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_EVENT_EMITTER;
                        Unit unit10 = Unit.f14616a;
                        i14 = i17;
                        bool7 = bool10;
                        num28 = num28;
                        num23 = num23;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 9:
                        num30 = num30;
                        str39 = str39;
                        str40 = str40;
                        num29 = num29;
                        Integer num34 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, m0.f17573a, num28);
                        i18 = i22 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_PADDING;
                        Unit unit11 = Unit.f14616a;
                        num28 = num34;
                        bool7 = bool10;
                        num23 = num23;
                        i14 = i18;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 10:
                        str39 = str39;
                        str40 = str40;
                        num30 = num30;
                        Integer num35 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, m0.f17573a, num29);
                        i16 = i22 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_OVERFLOW_INSET;
                        Unit unit12 = Unit.f14616a;
                        num29 = num35;
                        bool7 = bool10;
                        i14 = i16;
                        num23 = num23;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 11:
                        str40 = str40;
                        str39 = str39;
                        Integer num36 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, m0.f17573a, num30);
                        i18 = i22 | RecyclerView.ItemAnimator.FLAG_MOVED;
                        Unit unit13 = Unit.f14616a;
                        num30 = num36;
                        bool7 = bool10;
                        num23 = num23;
                        num28 = num28;
                        num29 = num29;
                        i14 = i18;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 12:
                        str40 = str40;
                        String str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, s1.f17602a, str39);
                        i16 = i22 | RecyclerView.ItemAnimator.FLAG_APPEARED_IN_PRE_LAYOUT;
                        Unit unit14 = Unit.f14616a;
                        str39 = str46;
                        bool7 = bool10;
                        num29 = num29;
                        num30 = num30;
                        i14 = i16;
                        num23 = num23;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 13:
                        String str47 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, s1.f17602a, str40);
                        i18 = i22 | 8192;
                        Unit unit15 = Unit.f14616a;
                        str40 = str47;
                        bool7 = bool10;
                        num23 = num23;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        i14 = i18;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 14:
                        str41 = str41;
                        bool8 = bool8;
                        Integer num37 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, m0.f17573a, num31);
                        int i23 = i22 | 16384;
                        Unit unit16 = Unit.f14616a;
                        i14 = i23;
                        bool7 = bool10;
                        num31 = num37;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        str40 = str40;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 15:
                        str41 = str41;
                        Boolean bool11 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, g.f17537a, bool8);
                        int i24 = i22 | PeerConnection.PORTALLOCATOR_ENABLE_ANY_ADDRESS_PORTS;
                        Unit unit17 = Unit.f14616a;
                        i14 = i24;
                        bool7 = bool10;
                        bool8 = bool11;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        str40 = str40;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 16:
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        bool9 = bool9;
                        str43 = str43;
                        str45 = str45;
                        num32 = num32;
                        num33 = num33;
                        str42 = str42;
                        String str48 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, s1.f17602a, str41);
                        int i25 = i22 | 65536;
                        Unit unit18 = Unit.f14616a;
                        i14 = i25;
                        bool7 = bool10;
                        str41 = str48;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        str40 = str40;
                        bool8 = bool8;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 17:
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        str43 = str43;
                        str45 = str45;
                        num32 = num32;
                        num33 = num33;
                        bool9 = bool9;
                        String str49 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, s1.f17602a, str42);
                        int i26 = i22 | 131072;
                        Unit unit19 = Unit.f14616a;
                        i14 = i26;
                        bool7 = bool10;
                        str42 = str49;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        str40 = str40;
                        bool8 = bool8;
                        str41 = str41;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 18:
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        str45 = str45;
                        num32 = num32;
                        num33 = num33;
                        str43 = str43;
                        Boolean bool12 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, g.f17537a, bool9);
                        int i27 = i22 | 262144;
                        Unit unit20 = Unit.f14616a;
                        i14 = i27;
                        bool7 = bool10;
                        bool9 = bool12;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        str40 = str40;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 19:
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        num32 = num32;
                        num33 = num33;
                        str45 = str45;
                        String str50 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, s1.f17602a, str43);
                        int i28 = i22 | 524288;
                        Unit unit21 = Unit.f14616a;
                        i14 = i28;
                        bool7 = bool10;
                        str43 = str50;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        str40 = str40;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        bool9 = bool9;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 20:
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        num33 = num33;
                        num32 = num32;
                        String str51 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, s1.f17602a, str45);
                        int i29 = i22 | 1048576;
                        Unit unit22 = Unit.f14616a;
                        i14 = i29;
                        bool7 = bool10;
                        str45 = str51;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        str40 = str40;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        bool9 = bool9;
                        str43 = str43;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 21:
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        num33 = num33;
                        Integer num38 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, m0.f17573a, num32);
                        int i30 = i22 | 2097152;
                        Unit unit23 = Unit.f14616a;
                        i14 = i30;
                        bool7 = bool10;
                        num32 = num38;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        str40 = str40;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        bool9 = bool9;
                        str43 = str43;
                        str45 = str45;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 22:
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        Integer num39 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, m0.f17573a, num33);
                        int i31 = i22 | 4194304;
                        Unit unit24 = Unit.f14616a;
                        i14 = i31;
                        bool7 = bool10;
                        num33 = num39;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        str40 = str40;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        bool9 = bool9;
                        str43 = str43;
                        str45 = str45;
                        num32 = num32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 23:
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        Boolean bool13 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, g.f17537a, bool10);
                        int i32 = i22 | 8388608;
                        Unit unit25 = Unit.f14616a;
                        i14 = i32;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        str40 = str40;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        bool9 = bool9;
                        str43 = str43;
                        str45 = str45;
                        num32 = num32;
                        num33 = num33;
                        bool7 = bool13;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 24:
                        Integer num40 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, m0.f17573a, num24);
                        int i33 = i22 | PointerEventHelper.X_FLAG_SUPPORTS_HOVER;
                        Unit unit26 = Unit.f14616a;
                        i14 = i33;
                        num24 = num40;
                        bool7 = bool10;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 25:
                        str35 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, s1.f17602a, str35);
                        i19 = i22 | 33554432;
                        Unit unit27 = Unit.f14616a;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i14 = i19;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        bool9 = bool9;
                        str43 = str43;
                        str45 = str45;
                        num32 = num32;
                        num33 = num33;
                        bool7 = bool10;
                        num24 = num24;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 26:
                        str34 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, s1.f17602a, str34);
                        i19 = i22 | 67108864;
                        Unit unit28 = Unit.f14616a;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i14 = i19;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        bool9 = bool9;
                        str43 = str43;
                        str45 = str45;
                        num32 = num32;
                        num33 = num33;
                        bool7 = bool10;
                        num24 = num24;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 27:
                        Integer num41 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, m0.f17573a, num26);
                        Unit unit29 = Unit.f14616a;
                        i14 = i22 | 134217728;
                        num24 = num24;
                        num26 = num41;
                        bool7 = bool10;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 28:
                        num23 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, m0.f17573a, num23);
                        i19 = i22 | 268435456;
                        Unit unit30 = Unit.f14616a;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i14 = i19;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        bool9 = bool9;
                        str43 = str43;
                        str45 = str45;
                        num32 = num32;
                        num33 = num33;
                        bool7 = bool10;
                        num24 = num24;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 29:
                        Integer num42 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, m0.f17573a, num25);
                        Unit unit31 = Unit.f14616a;
                        i14 = i22 | 536870912;
                        num24 = num24;
                        num25 = num42;
                        bool7 = bool10;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 30:
                        str33 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, s1.f17602a, str33);
                        i19 = i22 | 1073741824;
                        Unit unit32 = Unit.f14616a;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i14 = i19;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        bool9 = bool9;
                        str43 = str43;
                        str45 = str45;
                        num32 = num32;
                        num33 = num33;
                        bool7 = bool10;
                        num24 = num24;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 31:
                        String str52 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, s1.f17602a, str38);
                        Unit unit33 = Unit.f14616a;
                        i14 = i22 | Integer.MIN_VALUE;
                        num24 = num24;
                        str38 = str52;
                        bool7 = bool10;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 32:
                        Integer num43 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, m0.f17573a, num27);
                        Unit unit34 = Unit.f14616a;
                        i21 |= 1;
                        i14 = i22;
                        num24 = num24;
                        num27 = num43;
                        bool7 = bool10;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 33:
                        CodedLinkExtendedType codedLinkExtendedType4 = (CodedLinkExtendedType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 33, CodedLinkExtendedType.Serializer.INSTANCE, codedLinkExtendedType3);
                        Unit unit35 = Unit.f14616a;
                        codedLinkExtendedType3 = codedLinkExtendedType4;
                        i21 |= 2;
                        i14 = i22;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        bool9 = bool9;
                        str43 = str43;
                        str45 = str45;
                        num32 = num32;
                        num33 = num33;
                        bool7 = bool10;
                        num24 = num24;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 34:
                        String strDecodeStringElement12 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 34);
                        int i34 = i21 | 4;
                        Unit unit36 = Unit.f14616a;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str44 = strDecodeStringElement12;
                        i21 = i34;
                        i14 = i22;
                        bool8 = bool8;
                        str41 = str41;
                        str42 = str42;
                        bool9 = bool9;
                        str43 = str43;
                        str45 = str45;
                        num32 = num32;
                        num33 = num33;
                        bool7 = bool10;
                        num24 = num24;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 35:
                        String str53 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 35, s1.f17602a, str20);
                        Unit unit37 = Unit.f14616a;
                        i21 |= 8;
                        i14 = i22;
                        num24 = num24;
                        str20 = str53;
                        bool7 = bool10;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case 36:
                        String str54 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 36, s1.f17602a, str37);
                        Unit unit38 = Unit.f14616a;
                        i21 |= 16;
                        i14 = i22;
                        num24 = num24;
                        str37 = str54;
                        bool7 = bool10;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    case ChatViewRecyclerTypes.POLL_TEXT_AND_IMAGE /* 37 */:
                        String str55 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 37, s1.f17602a, str36);
                        int i35 = i21 | 32;
                        Unit unit39 = Unit.f14616a;
                        i21 = i35;
                        i14 = i22;
                        num24 = num24;
                        str36 = str55;
                        bool7 = bool10;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str33 = str33;
                        i22 = i14;
                        num33 = num33;
                        num32 = num32;
                        str45 = str45;
                        str43 = str43;
                        bool9 = bool9;
                        str42 = str42;
                        str41 = str41;
                        bool8 = bool8;
                        str40 = str40;
                        num28 = num28;
                        num29 = num29;
                        num30 = num30;
                        str39 = str39;
                        break;
                    default:
                        throw new j(iDecodeElementIndex);
                }
            }
            inviteType = inviteType3;
            str = str34;
            str2 = str35;
            i7 = i22;
            num = num24;
            num2 = num25;
            str3 = str36;
            str4 = str37;
            num3 = num26;
            str5 = str20;
            num4 = num27;
            str6 = str38;
            codedLinkExtendedType = codedLinkExtendedType3;
            str7 = str33;
            bool = bool7;
            num5 = num33;
            num6 = num32;
            str8 = str45;
            str9 = str43;
            bool2 = bool9;
            str10 = str42;
            str11 = str41;
            bool3 = bool8;
            num7 = num23;
            str12 = str40;
            i10 = iDecodeIntElement4;
            i11 = iDecodeIntElement5;
            str13 = strDecodeStringElement7;
            str14 = strDecodeStringElement8;
            str15 = strDecodeStringElement9;
            str16 = strDecodeStringElement10;
            str17 = strDecodeStringElement11;
            num8 = num28;
            num9 = num29;
            num10 = num30;
            str18 = str39;
            i12 = i20;
            i13 = i21;
            num11 = num31;
            str19 = str44;
        }
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new GuildInviteDisabledEmbedImpl(i7, i13, i12, i11, i10, str13, inviteType, str14, str15, str16, str17, num8, num9, num10, str18, str12, num11, bool3, str11, str10, bool2, str9, str8, num6, num5, bool, num, str2, str, num3, num7, num2, str7, str6, num4, codedLinkExtendedType, str19, str5, str4, str3, (SerializationConstructorMarker) null);
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.KSerializer
    public final void serialize(@NotNull Encoder encoder, @NotNull GuildInviteDisabledEmbedImpl value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        GuildInviteDisabledEmbedImpl.write$Self$chat_release(value, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }

    @Override // or.f0
    @NotNull
    public KSerializer[] typeParametersSerializers() {
        return e1.f17528b;
    }
}
