package com.discord.chat.bridge.codedlinks;

import androidx.recyclerview.widget.RecyclerView;
import com.discord.misc.utilities.chat_view_types.ChatViewRecyclerTypes;
import com.facebook.imagepipeline.nativecode.b;
import com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem;
import com.facebook.react.uimanager.ViewProps;
import com.facebook.react.uimanager.events.PointerEventHelper;
import java.util.List;
import kotlin.Lazy;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.DeserializationStrategy;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kr.j;
import or.e1;
import or.f0;
import or.g;
import or.g1;
import or.m0;
import or.r0;
import or.s1;
import org.jetbrains.annotations.NotNull;
import org.webrtc.PeerConnection;
import rn.d;

/* JADX INFO: loaded from: classes.dex */
@Metadata(d1 = {"\u0000:\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0005\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u001d\u0010\t\u001a\u00020\b2\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\u0007\u001a\u00020\u0002¢\u0006\u0004\b\t\u0010\nJ\u0015\u0010\r\u001a\u00020\u00022\u0006\u0010\f\u001a\u00020\u000b¢\u0006\u0004\b\r\u0010\u000eJ\u0017\u0010\u0011\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00100\u000f¢\u0006\u0004\b\u0011\u0010\u0012R\u0017\u0010\u0014\u001a\u00020\u00138\u0006¢\u0006\f\n\u0004\b\u0014\u0010\u0015\u001a\u0004\b\u0016\u0010\u0017¨\u0006\u0018"}, d2 = {"com/discord/chat/bridge/codedlinks/VoiceChannelListInviteEmbedImpl.$serializer", "Lor/f0;", "Lcom/discord/chat/bridge/codedlinks/VoiceChannelListInviteEmbedImpl;", "<init>", "()V", "Lkotlinx/serialization/encoding/Encoder;", "encoder", "value", "", "serialize", "(Lkotlinx/serialization/encoding/Encoder;Lcom/discord/chat/bridge/codedlinks/VoiceChannelListInviteEmbedImpl;)V", "Lkotlinx/serialization/encoding/Decoder;", "decoder", "deserialize", "(Lkotlinx/serialization/encoding/Decoder;)Lcom/discord/chat/bridge/codedlinks/VoiceChannelListInviteEmbedImpl;", "", "Lkotlinx/serialization/KSerializer;", "childSerializers", "()[Lkotlinx/serialization/KSerializer;", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "chat_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
@d
public /* synthetic */ class VoiceChannelListInviteEmbedImpl$$serializer implements f0 {

    @NotNull
    public static final VoiceChannelListInviteEmbedImpl$$serializer INSTANCE;

    @NotNull
    private static final SerialDescriptor descriptor;

    static {
        VoiceChannelListInviteEmbedImpl$$serializer voiceChannelListInviteEmbedImpl$$serializer = new VoiceChannelListInviteEmbedImpl$$serializer();
        INSTANCE = voiceChannelListInviteEmbedImpl$$serializer;
        g1 g1Var = new g1("com.discord.chat.bridge.codedlinks.VoiceChannelListInviteEmbedImpl", voiceChannelListInviteEmbedImpl$$serializer, 38);
        g1Var.b("acceptLabelBackgroundColor", false);
        g1Var.b("acceptLabelBorderColor", true);
        g1Var.b("acceptLabelColor", false);
        g1Var.b("acceptLabelText", false);
        g1Var.b("bodyTextColor", true);
        g1Var.b("bodyText", true);
        g1Var.b(ViewProps.BACKGROUND_COLOR, false);
        g1Var.b(ViewProps.BORDER_COLOR, false);
        g1Var.b("canBeAccepted", true);
        g1Var.b("embedCanBeTapped", true);
        g1Var.b("headerColor", false);
        g1Var.b("headerText", false);
        g1Var.b("resolvingGradientEnd", true);
        g1Var.b("resolvingGradientStart", true);
        g1Var.b("splashHasRadialGradient", true);
        g1Var.b("splashOpacity", true);
        g1Var.b("splashUrl", true);
        g1Var.b("inviteSplash", true);
        g1Var.b("subtitle", true);
        g1Var.b("subtitleColor", true);
        g1Var.b("thumbnailBackgroundColor", true);
        g1Var.b("thumbnailCornerRadius", true);
        g1Var.b("thumbnailText", true);
        g1Var.b("thumbnailUrl", true);
        g1Var.b("titleColor", false);
        g1Var.b("titleText", true);
        g1Var.b("type", true);
        g1Var.b("extendedType", true);
        g1Var.b("guildIcon", true);
        g1Var.b("guildName", true);
        g1Var.b("voiceUsers", true);
        g1Var.b("voiceStartTimestamp", true);
        g1Var.b("emptyStateText", false);
        g1Var.b("streamingLabel", false);
        g1Var.b("voiceHeaderBackgroundColor", false);
        g1Var.b("reducedMotion", true);
        g1Var.b("isConnected", true);
        g1Var.b("privacyHintText", false);
        descriptor = g1Var;
    }

    private VoiceChannelListInviteEmbedImpl$$serializer() {
    }

    @Override // or.f0
    @NotNull
    public final KSerializer[] childSerializers() {
        Lazy[] lazyArr = VoiceChannelListInviteEmbedImpl.$childSerializers;
        m0 m0Var = m0.f17573a;
        KSerializer kSerializerP = b.p(m0Var);
        s1 s1Var = s1.f17602a;
        KSerializer kSerializerP2 = b.p(m0Var);
        KSerializer kSerializerP3 = b.p(s1Var);
        g gVar = g.f17537a;
        return new KSerializer[]{m0Var, kSerializerP, m0Var, s1Var, kSerializerP2, kSerializerP3, m0Var, m0Var, b.p(gVar), b.p(gVar), m0Var, b.p(s1Var), b.p(m0Var), b.p(m0Var), b.p(gVar), b.p(m0Var), b.p(s1Var), b.p(s1Var), b.p(s1Var), b.p(m0Var), b.p(m0Var), b.p(m0Var), b.p(s1Var), b.p(s1Var), m0Var, b.p(s1Var), b.p(InviteType.Serializer.INSTANCE), CodedLinkExtendedType.Serializer.INSTANCE, b.p(s1Var), b.p(s1Var), b.p((KSerializer) lazyArr[30].getValue()), b.p(r0.f17595a), s1Var, s1Var, m0Var, gVar, gVar, s1Var};
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public final VoiceChannelListInviteEmbedImpl deserialize(@NotNull Decoder decoder) {
        Integer num;
        Integer num2;
        int i7;
        Integer num3;
        Integer num4;
        String str;
        Boolean bool;
        Boolean bool2;
        Boolean bool3;
        String str2;
        Integer num5;
        boolean z5;
        int i10;
        int i11;
        List list;
        String str3;
        String str4;
        CodedLinkExtendedType codedLinkExtendedType;
        InviteType inviteType;
        String str5;
        String str6;
        String str7;
        Integer num6;
        Integer num7;
        Integer num8;
        String str8;
        int i12;
        String str9;
        String str10;
        boolean zDecodeBooleanElement;
        int i13;
        int i14;
        int i15;
        int i16;
        String str11;
        String str12;
        String str13;
        String strDecodeStringElement;
        int i17;
        Long l6;
        int i18;
        int iDecodeIntElement;
        int i19;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        Lazy[] lazyArr = VoiceChannelListInviteEmbedImpl.$childSerializers;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 0);
            m0 m0Var = m0.f17573a;
            Integer num9 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, m0Var, null);
            int iDecodeIntElement3 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
            String strDecodeStringElement2 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
            Integer num10 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, m0Var, null);
            s1 s1Var = s1.f17602a;
            String str14 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, s1Var, null);
            int iDecodeIntElement4 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 6);
            int iDecodeIntElement5 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 7);
            g gVar = g.f17537a;
            Boolean bool4 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, gVar, null);
            Boolean bool5 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, gVar, null);
            int iDecodeIntElement6 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 10);
            String str15 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, s1Var, null);
            Integer num11 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, m0Var, null);
            Integer num12 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, m0Var, null);
            Boolean bool6 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, gVar, null);
            num = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, m0Var, null);
            String str16 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, s1Var, null);
            String str17 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, s1Var, null);
            String str18 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, s1Var, null);
            Integer num13 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, m0Var, null);
            Integer num14 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, m0Var, null);
            Integer num15 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, m0Var, null);
            String str19 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, s1Var, null);
            String str20 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, s1Var, null);
            int iDecodeIntElement7 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 24);
            String str21 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, s1Var, null);
            InviteType inviteType2 = (InviteType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, InviteType.Serializer.INSTANCE, null);
            CodedLinkExtendedType codedLinkExtendedType2 = (CodedLinkExtendedType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 27, CodedLinkExtendedType.Serializer.INSTANCE, null);
            String str22 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, s1Var, null);
            String str23 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, s1Var, null);
            List list2 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, (DeserializationStrategy) lazyArr[30].getValue(), null);
            Long l7 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, r0.f17595a, null);
            String strDecodeStringElement3 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 32);
            String strDecodeStringElement4 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 33);
            int iDecodeIntElement8 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 34);
            boolean zDecodeBooleanElement2 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 35);
            zDecodeBooleanElement = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 36);
            str4 = str22;
            str12 = strDecodeStringElement3;
            i14 = iDecodeIntElement5;
            i15 = iDecodeIntElement4;
            str2 = str14;
            str11 = strDecodeStringElement2;
            bool = bool4;
            num5 = num10;
            i16 = iDecodeIntElement3;
            num2 = num9;
            strDecodeStringElement = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 37);
            str13 = strDecodeStringElement4;
            str7 = str19;
            z5 = zDecodeBooleanElement2;
            i12 = iDecodeIntElement8;
            l6 = l7;
            i17 = 63;
            str3 = str23;
            codedLinkExtendedType = codedLinkExtendedType2;
            list = list2;
            inviteType = inviteType2;
            str5 = str21;
            i11 = iDecodeIntElement7;
            str6 = str20;
            num6 = num15;
            i13 = iDecodeIntElement2;
            num7 = num14;
            num8 = num13;
            str8 = str18;
            str9 = str17;
            i7 = -1;
            str10 = str16;
            bool2 = bool6;
            num3 = num12;
            num4 = num11;
            str = str15;
            i10 = iDecodeIntElement6;
            bool3 = bool5;
        } else {
            int iDecodeIntElement9 = 0;
            int i20 = 0;
            int i21 = 0;
            boolean zDecodeBooleanElement3 = false;
            int iDecodeIntElement10 = 0;
            int iDecodeIntElement11 = 0;
            int iDecodeIntElement12 = 0;
            int iDecodeIntElement13 = 0;
            int i22 = 0;
            int i23 = 0;
            boolean z6 = true;
            Integer num16 = null;
            Integer num17 = null;
            String str24 = null;
            Boolean bool7 = null;
            Boolean bool8 = null;
            Boolean bool9 = null;
            String str25 = null;
            Integer num18 = null;
            String strDecodeStringElement5 = null;
            Integer num19 = null;
            String str26 = null;
            String str27 = null;
            String str28 = null;
            Integer num20 = null;
            Integer num21 = null;
            Integer num22 = null;
            String str29 = null;
            String str30 = null;
            String str31 = null;
            InviteType inviteType3 = null;
            CodedLinkExtendedType codedLinkExtendedType3 = null;
            String str32 = null;
            String str33 = null;
            List list3 = null;
            Long l10 = null;
            String str34 = null;
            String str35 = null;
            String strDecodeStringElement6 = null;
            boolean z7 = false;
            Integer num23 = null;
            while (z6) {
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        int i24 = i20;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i25 = i23;
                        l10 = l10;
                        Unit unit = Unit.f14616a;
                        i23 = i25;
                        i20 = i24;
                        num19 = num19;
                        i21 = i21;
                        z6 = false;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 0:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        int i26 = i20;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i27 = i23;
                        l10 = l10;
                        iDecodeIntElement10 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 0);
                        Unit unit2 = Unit.f14616a;
                        i23 = i27 | 1;
                        i20 = i26;
                        num19 = num19;
                        i21 = i21;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 1:
                        int i28 = i20;
                        str26 = str26;
                        int i29 = i23;
                        l10 = l10;
                        num23 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, m0.f17573a, num23);
                        int i30 = i29 | 2;
                        Unit unit3 = Unit.f14616a;
                        i20 = i28;
                        num19 = num19;
                        i21 = i21;
                        i23 = i30;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 2:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement13 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 2);
                        i18 = i23 | 4;
                        Unit unit4 = Unit.f14616a;
                        i23 = i18;
                        i20 = i20;
                        num19 = num19;
                        i21 = i21;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 3:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        strDecodeStringElement5 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 3);
                        i18 = i23 | 8;
                        Unit unit5 = Unit.f14616a;
                        i23 = i18;
                        i20 = i20;
                        num19 = num19;
                        i21 = i21;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 4:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        int i31 = i20;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i32 = i23;
                        l10 = l10;
                        Integer num24 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, m0.f17573a, num18);
                        Unit unit6 = Unit.f14616a;
                        i23 = i32 | 16;
                        i20 = i31;
                        num19 = num19;
                        i21 = i21;
                        num18 = num24;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 5:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        int i33 = i20;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i34 = i23;
                        l10 = l10;
                        String str36 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, s1.f17602a, str25);
                        Unit unit7 = Unit.f14616a;
                        i23 = i34 | 32;
                        i20 = i33;
                        num19 = num19;
                        i21 = i21;
                        str25 = str36;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 6:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement12 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 6);
                        i18 = i23 | 64;
                        Unit unit8 = Unit.f14616a;
                        i23 = i18;
                        i20 = i20;
                        num19 = num19;
                        i21 = i21;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 7:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement11 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 7);
                        i18 = i23 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_LAYOUT;
                        Unit unit9 = Unit.f14616a;
                        i23 = i18;
                        i20 = i20;
                        num19 = num19;
                        i21 = i21;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 8:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        int i35 = i20;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i36 = i23;
                        l10 = l10;
                        Boolean bool10 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, g.f17537a, bool7);
                        int i37 = i36 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_EVENT_EMITTER;
                        Unit unit10 = Unit.f14616a;
                        i23 = i37;
                        i20 = i35;
                        num19 = num19;
                        i21 = i21;
                        bool7 = bool10;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 9:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        int i38 = i20;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i39 = i23;
                        l10 = l10;
                        Boolean bool11 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, g.f17537a, bool9);
                        int i40 = i39 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_PADDING;
                        Unit unit11 = Unit.f14616a;
                        i23 = i40;
                        i20 = i38;
                        num19 = num19;
                        i21 = i21;
                        bool9 = bool11;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 10:
                        iDecodeIntElement9 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 10);
                        i18 = i23 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_OVERFLOW_INSET;
                        Unit unit12 = Unit.f14616a;
                        i23 = i18;
                        i20 = i20;
                        num19 = num19;
                        i21 = i21;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 11:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        int i41 = i20;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i42 = i23;
                        l10 = l10;
                        String str37 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, s1.f17602a, str24);
                        int i43 = i42 | RecyclerView.ItemAnimator.FLAG_MOVED;
                        Unit unit13 = Unit.f14616a;
                        i23 = i43;
                        i20 = i41;
                        num19 = num19;
                        i21 = i21;
                        str24 = str37;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 12:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        int i44 = i20;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i45 = i23;
                        l10 = l10;
                        Integer num25 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, m0.f17573a, num17);
                        int i46 = i45 | RecyclerView.ItemAnimator.FLAG_APPEARED_IN_PRE_LAYOUT;
                        Unit unit14 = Unit.f14616a;
                        i23 = i46;
                        i20 = i44;
                        num19 = num19;
                        i21 = i21;
                        num17 = num25;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 13:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        int i47 = i20;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i48 = i23;
                        l10 = l10;
                        Integer num26 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, m0.f17573a, num16);
                        Unit unit15 = Unit.f14616a;
                        i23 = i48 | 8192;
                        i20 = i47;
                        num19 = num19;
                        i21 = i21;
                        num16 = num26;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 14:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        int i49 = i20;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i50 = i23;
                        l10 = l10;
                        Boolean bool12 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, g.f17537a, bool8);
                        Unit unit16 = Unit.f14616a;
                        i23 = i50 | 16384;
                        i20 = i49;
                        num19 = num19;
                        i21 = i21;
                        bool8 = bool12;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 15:
                        int i51 = i20;
                        int i52 = i21;
                        int i53 = i23;
                        l10 = l10;
                        str26 = str26;
                        Integer num27 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, m0.f17573a, num19);
                        int i54 = i53 | PeerConnection.PORTALLOCATOR_ENABLE_ANY_ADDRESS_PORTS;
                        Unit unit17 = Unit.f14616a;
                        i21 = i52;
                        i23 = i54;
                        i20 = i51;
                        num19 = num27;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 16:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement = i20;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i55 = i23;
                        l10 = l10;
                        str27 = str27;
                        String str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, s1.f17602a, str26);
                        i19 = i55 | 65536;
                        Unit unit18 = Unit.f14616a;
                        str26 = str38;
                        i21 = i21;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 17:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement = i20;
                        int i56 = i21;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i57 = i23;
                        l10 = l10;
                        str28 = str28;
                        String str39 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, s1.f17602a, str27);
                        i19 = i57 | 131072;
                        Unit unit19 = Unit.f14616a;
                        str27 = str39;
                        i21 = i56;
                        str26 = str26;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 18:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement = i20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i58 = i23;
                        l10 = l10;
                        num20 = num20;
                        String str40 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, s1.f17602a, str28);
                        i19 = i58 | 262144;
                        Unit unit20 = Unit.f14616a;
                        str28 = str40;
                        i21 = i21;
                        str26 = str26;
                        str27 = str27;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 19:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement = i20;
                        int i59 = i21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i60 = i23;
                        l10 = l10;
                        num21 = num21;
                        Integer num28 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, m0.f17573a, num20);
                        i19 = i60 | 524288;
                        Unit unit21 = Unit.f14616a;
                        num20 = num28;
                        i21 = i59;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 20:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement = i20;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i61 = i23;
                        l10 = l10;
                        num22 = num22;
                        Integer num29 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, m0.f17573a, num21);
                        i19 = i61 | 1048576;
                        Unit unit22 = Unit.f14616a;
                        num21 = num29;
                        i21 = i21;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 21:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement = i20;
                        int i62 = i21;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i63 = i23;
                        l10 = l10;
                        str29 = str29;
                        Integer num30 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, m0.f17573a, num22);
                        i19 = i63 | 2097152;
                        Unit unit23 = Unit.f14616a;
                        num22 = num30;
                        i21 = i62;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 22:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement = i20;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i64 = i23;
                        l10 = l10;
                        str30 = str30;
                        String str41 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, s1.f17602a, str29);
                        i19 = i64 | 4194304;
                        Unit unit24 = Unit.f14616a;
                        str29 = str41;
                        i21 = i21;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 23:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement = i20;
                        int i65 = i21;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i66 = i23;
                        l10 = l10;
                        str31 = str31;
                        String str42 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, s1.f17602a, str30);
                        i19 = i66 | 8388608;
                        Unit unit25 = Unit.f14616a;
                        str30 = str42;
                        i21 = i65;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 24:
                        inviteType3 = inviteType3;
                        iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 24);
                        i19 = i23 | PointerEventHelper.X_FLAG_SUPPORTS_HOVER;
                        Unit unit26 = Unit.f14616a;
                        str31 = str31;
                        i21 = i21;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 25:
                        iDecodeIntElement = i20;
                        inviteType3 = inviteType3;
                        String str43 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, s1.f17602a, str31);
                        i19 = i23 | 33554432;
                        Unit unit27 = Unit.f14616a;
                        str31 = str43;
                        i21 = i21;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 26:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement = i20;
                        int i67 = i21;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        int i68 = i23;
                        l10 = l10;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        InviteType inviteType4 = (InviteType) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, InviteType.Serializer.INSTANCE, inviteType3);
                        i19 = i68 | 67108864;
                        Unit unit28 = Unit.f14616a;
                        inviteType3 = inviteType4;
                        i21 = i67;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 27:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement = i20;
                        str33 = str33;
                        list3 = list3;
                        int i69 = i23;
                        l10 = l10;
                        str32 = str32;
                        CodedLinkExtendedType codedLinkExtendedType4 = (CodedLinkExtendedType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 27, CodedLinkExtendedType.Serializer.INSTANCE, codedLinkExtendedType3);
                        i19 = i69 | 134217728;
                        Unit unit29 = Unit.f14616a;
                        codedLinkExtendedType3 = codedLinkExtendedType4;
                        i21 = i21;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 28:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement = i20;
                        int i70 = i21;
                        list3 = list3;
                        int i71 = i23;
                        l10 = l10;
                        str33 = str33;
                        String str44 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, s1.f17602a, str32);
                        i19 = i71 | 268435456;
                        Unit unit30 = Unit.f14616a;
                        str32 = str44;
                        i21 = i70;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 29:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement = i20;
                        int i72 = i23;
                        l10 = l10;
                        list3 = list3;
                        String str45 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, s1.f17602a, str33);
                        i19 = i72 | 536870912;
                        Unit unit31 = Unit.f14616a;
                        str33 = str45;
                        i21 = i21;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 30:
                        iDecodeIntElement9 = iDecodeIntElement9;
                        iDecodeIntElement = i20;
                        int i73 = i23;
                        l10 = l10;
                        int i74 = i21;
                        List list4 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, (DeserializationStrategy) lazyArr[30].getValue(), list3);
                        i19 = i73 | 1073741824;
                        Unit unit32 = Unit.f14616a;
                        list3 = list4;
                        i21 = i74;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        i23 = i19;
                        i20 = iDecodeIntElement;
                        num19 = num19;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 31:
                        int i75 = i20;
                        Long l11 = (Long) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 31, r0.f17595a, l10);
                        Unit unit33 = Unit.f14616a;
                        i20 = i75;
                        num19 = num19;
                        str26 = str26;
                        i23 |= Integer.MIN_VALUE;
                        l10 = l11;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 32:
                        String strDecodeStringElement7 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 32);
                        i22 |= 1;
                        Unit unit34 = Unit.f14616a;
                        str34 = strDecodeStringElement7;
                        num19 = num19;
                        str26 = str26;
                        i23 = i23;
                        l10 = l10;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 33:
                        String strDecodeStringElement8 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 33);
                        i22 |= 2;
                        Unit unit35 = Unit.f14616a;
                        str35 = strDecodeStringElement8;
                        num19 = num19;
                        str26 = str26;
                        i23 = i23;
                        l10 = l10;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 34:
                        int iDecodeIntElement14 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 34);
                        i22 |= 4;
                        Unit unit36 = Unit.f14616a;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        i21 = iDecodeIntElement14;
                        num19 = num19;
                        str26 = str26;
                        str27 = str27;
                        str28 = str28;
                        num20 = num20;
                        num21 = num21;
                        num22 = num22;
                        str29 = str29;
                        str30 = str30;
                        str31 = str31;
                        inviteType3 = inviteType3;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        str32 = str32;
                        str33 = str33;
                        list3 = list3;
                        i23 = i23;
                        l10 = l10;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 35:
                        boolean zDecodeBooleanElement4 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 35);
                        i22 |= 8;
                        Unit unit37 = Unit.f14616a;
                        z7 = zDecodeBooleanElement4;
                        l10 = l10;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case 36:
                        zDecodeBooleanElement3 = compositeDecoderBeginStructure.decodeBooleanElement(serialDescriptor, 36);
                        i22 |= 16;
                        Unit unit38 = Unit.f14616a;
                        l10 = l10;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    case ChatViewRecyclerTypes.POLL_TEXT_AND_IMAGE /* 37 */:
                        strDecodeStringElement6 = compositeDecoderBeginStructure.decodeStringElement(serialDescriptor, 37);
                        i22 |= 32;
                        Unit unit39 = Unit.f14616a;
                        l10 = l10;
                        iDecodeIntElement9 = iDecodeIntElement9;
                        num19 = num19;
                        list3 = list3;
                        str33 = str33;
                        str32 = str32;
                        codedLinkExtendedType3 = codedLinkExtendedType3;
                        inviteType3 = inviteType3;
                        str31 = str31;
                        str30 = str30;
                        str29 = str29;
                        num22 = num22;
                        num21 = num21;
                        num20 = num20;
                        str28 = str28;
                        str27 = str27;
                        str26 = str26;
                        l10 = l10;
                        i23 = i23;
                        break;
                    default:
                        throw new j(iDecodeElementIndex);
                }
            }
            int i76 = i21;
            num = num19;
            num2 = num23;
            i7 = i23;
            num3 = num16;
            num4 = num17;
            str = str24;
            bool = bool7;
            bool2 = bool8;
            bool3 = bool9;
            str2 = str25;
            num5 = num18;
            z5 = z7;
            i10 = iDecodeIntElement9;
            i11 = i20;
            list = list3;
            str3 = str33;
            str4 = str32;
            codedLinkExtendedType = codedLinkExtendedType3;
            inviteType = inviteType3;
            str5 = str31;
            str6 = str30;
            str7 = str29;
            num6 = num22;
            num7 = num21;
            num8 = num20;
            str8 = str28;
            i12 = i76;
            str9 = str27;
            str10 = str26;
            zDecodeBooleanElement = zDecodeBooleanElement3;
            i13 = iDecodeIntElement10;
            i14 = iDecodeIntElement11;
            i15 = iDecodeIntElement12;
            i16 = iDecodeIntElement13;
            str11 = strDecodeStringElement5;
            str12 = str34;
            str13 = str35;
            strDecodeStringElement = strDecodeStringElement6;
            i17 = i22;
            l6 = l10;
        }
        Integer num31 = num;
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new VoiceChannelListInviteEmbedImpl(i7, i17, i13, num2, i16, str11, num5, str2, i15, i14, bool, bool3, i10, str, num4, num3, bool2, num31, str10, str9, str8, num8, num7, num6, str7, str6, i11, str5, inviteType, codedLinkExtendedType, str4, str3, list, l6, str12, str13, i12, z5, zDecodeBooleanElement, strDecodeStringElement, (SerializationConstructorMarker) null);
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.KSerializer
    public final void serialize(@NotNull Encoder encoder, @NotNull VoiceChannelListInviteEmbedImpl value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        VoiceChannelListInviteEmbedImpl.write$Self$chat_release(value, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }

    @Override // or.f0
    @NotNull
    public KSerializer[] typeParametersSerializers() {
        return e1.f17528b;
    }
}
