package com.discord.chat.bridge.embed;

import androidx.recyclerview.widget.RecyclerView;
import com.discord.chat.bridge.structurabletext.StructurableText;
import com.discord.chat.bridge.structurabletext.StructurableTextSerializer;
import com.facebook.react.devsupport.StackTraceHelper;
import com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem;
import com.facebook.react.modules.dialog.AlertFragment;
import com.facebook.react.uimanager.ViewProps;
import com.facebook.react.uimanager.events.PointerEventHelper;
import java.util.List;
import kotlin.Lazy;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.DeserializationStrategy;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kr.j;
import or.e1;
import or.f0;
import or.g;
import or.g1;
import or.m0;
import or.s1;
import org.jetbrains.annotations.NotNull;
import org.webrtc.MediaStreamTrack;
import org.webrtc.PeerConnection;
import rn.d;

/* JADX INFO: loaded from: classes.dex */
@Metadata(d1 = {"\u0000:\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0005\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u001d\u0010\t\u001a\u00020\b2\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\u0007\u001a\u00020\u0002¢\u0006\u0004\b\t\u0010\nJ\u0015\u0010\r\u001a\u00020\u00022\u0006\u0010\f\u001a\u00020\u000b¢\u0006\u0004\b\r\u0010\u000eJ\u0017\u0010\u0011\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00100\u000f¢\u0006\u0004\b\u0011\u0010\u0012R\u0017\u0010\u0014\u001a\u00020\u00138\u0006¢\u0006\f\n\u0004\b\u0014\u0010\u0015\u001a\u0004\b\u0016\u0010\u0017¨\u0006\u0018"}, d2 = {"com/discord/chat/bridge/embed/Embed.$serializer", "Lor/f0;", "Lcom/discord/chat/bridge/embed/Embed;", "<init>", "()V", "Lkotlinx/serialization/encoding/Encoder;", "encoder", "value", "", "serialize", "(Lkotlinx/serialization/encoding/Encoder;Lcom/discord/chat/bridge/embed/Embed;)V", "Lkotlinx/serialization/encoding/Decoder;", "decoder", "deserialize", "(Lkotlinx/serialization/encoding/Decoder;)Lcom/discord/chat/bridge/embed/Embed;", "", "Lkotlinx/serialization/KSerializer;", "childSerializers", "()[Lkotlinx/serialization/KSerializer;", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "chat_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
@d
public /* synthetic */ class Embed$$serializer implements f0 {

    @NotNull
    public static final Embed$$serializer INSTANCE;

    @NotNull
    private static final SerialDescriptor descriptor;

    static {
        Embed$$serializer embed$$serializer = new Embed$$serializer();
        INSTANCE = embed$$serializer;
        g1 g1Var = new g1("com.discord.chat.bridge.embed.Embed", embed$$serializer, 35);
        g1Var.b("type", false);
        g1Var.b(StackTraceHelper.ID_KEY, true);
        g1Var.b("author", true);
        g1Var.b("provider", true);
        g1Var.b("rawTitle", true);
        g1Var.b(AlertFragment.ARG_TITLE, true);
        g1Var.b("fields", true);
        g1Var.b("url", true);
        g1Var.b("rawDescription", true);
        g1Var.b("description", true);
        g1Var.b("image", true);
        g1Var.b("images", true);
        g1Var.b(MediaStreamTrack.VIDEO_TRACK_KIND, true);
        g1Var.b("thumbnail", true);
        g1Var.b("numAttachments", true);
        g1Var.b("attachmentsSize", true);
        g1Var.b("messageSendError", true);
        g1Var.b("disableBackgroundColor", true);
        g1Var.b("footer", true);
        g1Var.b("spoiler", true);
        g1Var.b("obscure", true);
        g1Var.b("obscureAwaitingScan", true);
        g1Var.b("obscureHideControls", true);
        g1Var.b("obscureIsOpaque", true);
        g1Var.b("verifyAge", true);
        g1Var.b("iconURL", true);
        g1Var.b("components", true);
        g1Var.b("failureState", true);
        g1Var.b("providerColor", true);
        g1Var.b(ViewProps.BORDER_LEFT_COLOR, true);
        g1Var.b("headerTextColor", true);
        g1Var.b("bodyTextColor", false);
        g1Var.b(ViewProps.BACKGROUND_COLOR, true);
        g1Var.b("spoilerOrNull", true);
        g1Var.b("obscureOrNull", true);
        descriptor = g1Var;
    }

    private Embed$$serializer() {
    }

    /* JADX WARN: Multi-variable type inference failed */
    @Override // or.f0
    @NotNull
    public final KSerializer[] childSerializers() {
        Lazy[] lazyArr = Embed.$childSerializers;
        s1 s1Var = s1.f17602a;
        StructurableTextSerializer structurableTextSerializer = StructurableTextSerializer.INSTANCE;
        EmbedMedia$$serializer embedMedia$$serializer = EmbedMedia$$serializer.INSTANCE;
        g gVar = g.f17537a;
        m0 m0Var = m0.f17573a;
        return new KSerializer[]{lazyArr[0].getValue(), com.facebook.imagepipeline.nativecode.b.p(s1Var), com.facebook.imagepipeline.nativecode.b.p(EmbedAuthor$$serializer.INSTANCE), com.facebook.imagepipeline.nativecode.b.p(EmbedProvider$$serializer.INSTANCE), com.facebook.imagepipeline.nativecode.b.p(s1Var), com.facebook.imagepipeline.nativecode.b.p(structurableTextSerializer), com.facebook.imagepipeline.nativecode.b.p((KSerializer) lazyArr[6].getValue()), com.facebook.imagepipeline.nativecode.b.p(s1Var), com.facebook.imagepipeline.nativecode.b.p(s1Var), com.facebook.imagepipeline.nativecode.b.p(structurableTextSerializer), com.facebook.imagepipeline.nativecode.b.p(embedMedia$$serializer), com.facebook.imagepipeline.nativecode.b.p((KSerializer) lazyArr[11].getValue()), com.facebook.imagepipeline.nativecode.b.p(embedMedia$$serializer), com.facebook.imagepipeline.nativecode.b.p(EmbedThumbnail$$serializer.INSTANCE), com.facebook.imagepipeline.nativecode.b.p(s1Var), com.facebook.imagepipeline.nativecode.b.p(s1Var), com.facebook.imagepipeline.nativecode.b.p(s1Var), com.facebook.imagepipeline.nativecode.b.p(gVar), com.facebook.imagepipeline.nativecode.b.p(EmbedFooter$$serializer.INSTANCE), com.facebook.imagepipeline.nativecode.b.p(s1Var), com.facebook.imagepipeline.nativecode.b.p(s1Var), com.facebook.imagepipeline.nativecode.b.p(s1Var), com.facebook.imagepipeline.nativecode.b.p(gVar), com.facebook.imagepipeline.nativecode.b.p(gVar), com.facebook.imagepipeline.nativecode.b.p(gVar), com.facebook.imagepipeline.nativecode.b.p(s1Var), com.facebook.imagepipeline.nativecode.b.p((KSerializer) lazyArr[26].getValue()), com.facebook.imagepipeline.nativecode.b.p(EmbedFailureState.Serializer.INSTANCE), com.facebook.imagepipeline.nativecode.b.p(m0Var), com.facebook.imagepipeline.nativecode.b.p(m0Var), com.facebook.imagepipeline.nativecode.b.p(m0Var), m0Var, com.facebook.imagepipeline.nativecode.b.p(m0Var), com.facebook.imagepipeline.nativecode.b.p(s1Var), com.facebook.imagepipeline.nativecode.b.p(s1Var)};
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public final Embed deserialize(@NotNull Decoder decoder) {
        EmbedMedia embedMedia;
        EmbedType embedType;
        Boolean bool;
        Integer num;
        EmbedFailureState embedFailureState;
        String str;
        String str2;
        String str3;
        Integer num2;
        Integer num3;
        Integer num4;
        Boolean bool2;
        int i7;
        String str4;
        List list;
        String str5;
        String str6;
        EmbedFooter embedFooter;
        Boolean bool3;
        String str7;
        String str8;
        Boolean bool4;
        EmbedThumbnail embedThumbnail;
        EmbedMedia embedMedia2;
        List list2;
        String str9;
        String str10;
        EmbedAuthor embedAuthor;
        EmbedProvider embedProvider;
        String str11;
        StructurableText structurableText;
        List list3;
        String str12;
        StructurableText structurableText2;
        int i10;
        String str13;
        int i11;
        int i12;
        int i13;
        int i14;
        int i15;
        int i16;
        int i17;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeDecoder compositeDecoderBeginStructure = decoder.beginStructure(serialDescriptor);
        Lazy[] lazyArr = Embed.$childSerializers;
        EmbedFailureState embedFailureState2 = null;
        if (compositeDecoderBeginStructure.decodeSequentially()) {
            EmbedType embedType2 = (EmbedType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, 0, (DeserializationStrategy) lazyArr[0].getValue(), null);
            s1 s1Var = s1.f17602a;
            String str14 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, s1Var, null);
            EmbedAuthor embedAuthor2 = (EmbedAuthor) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, EmbedAuthor$$serializer.INSTANCE, null);
            EmbedProvider embedProvider2 = (EmbedProvider) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, EmbedProvider$$serializer.INSTANCE, null);
            String str15 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, s1Var, null);
            StructurableTextSerializer structurableTextSerializer = StructurableTextSerializer.INSTANCE;
            StructurableText structurableText3 = (StructurableText) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, structurableTextSerializer, null);
            List list4 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 6, (DeserializationStrategy) lazyArr[6].getValue(), null);
            String str16 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, s1Var, null);
            String str17 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, s1Var, null);
            StructurableText structurableText4 = (StructurableText) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, structurableTextSerializer, null);
            EmbedMedia$$serializer embedMedia$$serializer = EmbedMedia$$serializer.INSTANCE;
            embedMedia = (EmbedMedia) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, embedMedia$$serializer, null);
            List list5 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, (DeserializationStrategy) lazyArr[11].getValue(), null);
            EmbedMedia embedMedia3 = (EmbedMedia) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, embedMedia$$serializer, null);
            EmbedThumbnail embedThumbnail2 = (EmbedThumbnail) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, EmbedThumbnail$$serializer.INSTANCE, null);
            String str18 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, s1Var, null);
            String str19 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, s1Var, null);
            String str20 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, s1Var, null);
            g gVar = g.f17537a;
            Boolean bool5 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, gVar, null);
            EmbedFooter embedFooter2 = (EmbedFooter) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, EmbedFooter$$serializer.INSTANCE, null);
            String str21 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, s1Var, null);
            String str22 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, s1Var, null);
            String str23 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, s1Var, null);
            Boolean bool6 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, gVar, null);
            Boolean bool7 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, gVar, null);
            Boolean bool8 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, gVar, null);
            String str24 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, s1Var, null);
            List list6 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, (DeserializationStrategy) lazyArr[26].getValue(), null);
            EmbedFailureState embedFailureState3 = (EmbedFailureState) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, EmbedFailureState.Serializer.INSTANCE, null);
            m0 m0Var = m0.f17573a;
            Integer num5 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, m0Var, null);
            Integer num6 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, m0Var, null);
            Integer num7 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, m0Var, null);
            int iDecodeIntElement = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 31);
            Integer num8 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, m0Var, null);
            String str25 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, s1Var, null);
            str2 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 34, s1Var, null);
            str3 = str25;
            str6 = str21;
            str9 = str17;
            structurableText2 = structurableText4;
            i7 = -1;
            str11 = str15;
            embedAuthor = embedAuthor2;
            str10 = str14;
            embedProvider = embedProvider2;
            str12 = str16;
            structurableText = structurableText3;
            str13 = str18;
            num2 = num8;
            i10 = iDecodeIntElement;
            num4 = num7;
            num3 = num6;
            num = num5;
            embedFailureState = embedFailureState3;
            str4 = str24;
            bool = bool8;
            bool4 = bool7;
            bool2 = bool6;
            str = str23;
            str5 = str22;
            embedFooter = embedFooter2;
            list = list6;
            bool3 = bool5;
            str7 = str20;
            str8 = str19;
            embedThumbnail = embedThumbnail2;
            embedMedia2 = embedMedia3;
            list2 = list5;
            list3 = list4;
            embedType = embedType2;
            i11 = 7;
        } else {
            int i18 = 6;
            String str26 = null;
            List list7 = null;
            Boolean bool9 = null;
            Boolean bool10 = null;
            Integer num9 = null;
            String str27 = null;
            String str28 = null;
            Integer num10 = null;
            Integer num11 = null;
            Boolean bool11 = null;
            String str29 = null;
            EmbedType embedType3 = null;
            String str30 = null;
            EmbedAuthor embedAuthor3 = null;
            EmbedProvider embedProvider3 = null;
            String str31 = null;
            StructurableText structurableText5 = null;
            List list8 = null;
            String str32 = null;
            String str33 = null;
            StructurableText structurableText6 = null;
            EmbedMedia embedMedia4 = null;
            List list9 = null;
            EmbedMedia embedMedia5 = null;
            EmbedThumbnail embedThumbnail3 = null;
            String str34 = null;
            String str35 = null;
            String str36 = null;
            Boolean bool12 = null;
            EmbedFooter embedFooter3 = null;
            String str37 = null;
            int i19 = 1;
            int i20 = 0;
            int i21 = 0;
            int i22 = 0;
            int i23 = 0;
            String str38 = null;
            Integer num12 = null;
            while (i19 != 0) {
                str29 = str29;
                int iDecodeElementIndex = compositeDecoderBeginStructure.decodeElementIndex(serialDescriptor);
                switch (iDecodeElementIndex) {
                    case -1:
                        String str39 = str26;
                        i20 = i20;
                        i12 = i22;
                        str35 = str35;
                        str36 = str36;
                        bool12 = bool12;
                        embedFooter3 = embedFooter3;
                        str37 = str37;
                        str29 = str29;
                        Unit unit = Unit.f14616a;
                        i19 = i20;
                        str26 = str39;
                        list7 = list7;
                        i14 = i12;
                        str29 = str29;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 0:
                        String str40 = str26;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        embedThumbnail3 = embedThumbnail3;
                        DeserializationStrategy deserializationStrategy = (DeserializationStrategy) lazyArr[i20].getValue();
                        int i24 = i20;
                        str30 = str30;
                        i20 = i24;
                        EmbedType embedType4 = (EmbedType) compositeDecoderBeginStructure.decodeSerializableElement(serialDescriptor, i20, deserializationStrategy, embedType3);
                        i13 = i22 | 1;
                        Unit unit2 = Unit.f14616a;
                        embedType3 = embedType4;
                        str26 = str40;
                        str29 = str29;
                        i14 = i13;
                        list7 = list7;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 1:
                        String str41 = str26;
                        List list10 = list7;
                        bool9 = bool9;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        embedMedia5 = embedMedia5;
                        embedThumbnail3 = embedThumbnail3;
                        str35 = str35;
                        str36 = str36;
                        bool12 = bool12;
                        embedFooter3 = embedFooter3;
                        str37 = str37;
                        str29 = str29;
                        embedAuthor3 = embedAuthor3;
                        String str42 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 1, s1.f17602a, str30);
                        Unit unit3 = Unit.f14616a;
                        int i25 = i20;
                        str30 = str42;
                        str26 = str41;
                        i14 = i22 | 2;
                        i20 = i25;
                        list7 = list10;
                        str29 = str29;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 2:
                        String str43 = str26;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        embedThumbnail3 = embedThumbnail3;
                        embedProvider3 = embedProvider3;
                        EmbedAuthor embedAuthor4 = (EmbedAuthor) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 2, EmbedAuthor$$serializer.INSTANCE, embedAuthor3);
                        i13 = i22 | 4;
                        Unit unit4 = Unit.f14616a;
                        embedAuthor3 = embedAuthor4;
                        str26 = str43;
                        str29 = str29;
                        i20 = i20;
                        str30 = str30;
                        i14 = i13;
                        list7 = list7;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 3:
                        String str44 = str26;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        embedMedia5 = embedMedia5;
                        embedThumbnail3 = embedThumbnail3;
                        str31 = str31;
                        EmbedProvider embedProvider4 = (EmbedProvider) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 3, EmbedProvider$$serializer.INSTANCE, embedProvider3);
                        i15 = i22 | 8;
                        Unit unit5 = Unit.f14616a;
                        embedProvider3 = embedProvider4;
                        str26 = str44;
                        list7 = list7;
                        str29 = str29;
                        i14 = i15;
                        i20 = i20;
                        str30 = str30;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 4:
                        String str45 = str26;
                        list8 = list8;
                        str32 = str32;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        embedThumbnail3 = embedThumbnail3;
                        structurableText5 = structurableText5;
                        String str46 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 4, s1.f17602a, str31);
                        i13 = i22 | 16;
                        Unit unit6 = Unit.f14616a;
                        str31 = str46;
                        str26 = str45;
                        str29 = str29;
                        i20 = i20;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        i14 = i13;
                        list7 = list7;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 5:
                        String str47 = str26;
                        str32 = str32;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        embedMedia5 = embedMedia5;
                        embedThumbnail3 = embedThumbnail3;
                        list8 = list8;
                        StructurableText structurableText7 = (StructurableText) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 5, StructurableTextSerializer.INSTANCE, structurableText5);
                        i15 = i22 | 32;
                        Unit unit7 = Unit.f14616a;
                        structurableText5 = structurableText7;
                        str26 = str47;
                        list7 = list7;
                        str29 = str29;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        i14 = i15;
                        i20 = i20;
                        str30 = str30;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 6:
                        String str48 = str26;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        embedThumbnail3 = embedThumbnail3;
                        DeserializationStrategy deserializationStrategy2 = (DeserializationStrategy) lazyArr[i18].getValue();
                        int i26 = i18;
                        str32 = str32;
                        List list11 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, i26, deserializationStrategy2, list8);
                        i13 = i22 | 64;
                        Unit unit8 = Unit.f14616a;
                        list8 = list11;
                        str26 = str48;
                        str29 = str29;
                        i20 = i20;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        i14 = i13;
                        list7 = list7;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 7:
                        String str49 = str26;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        embedMedia5 = embedMedia5;
                        embedThumbnail3 = embedThumbnail3;
                        str33 = str33;
                        String str50 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 7, s1.f17602a, str32);
                        i15 = i22 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_LAYOUT;
                        Unit unit9 = Unit.f14616a;
                        str32 = str50;
                        str26 = str49;
                        list7 = list7;
                        str29 = str29;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        i14 = i15;
                        i20 = i20;
                        str30 = str30;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 8:
                        String str51 = str26;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        embedThumbnail3 = embedThumbnail3;
                        structurableText6 = structurableText6;
                        String str52 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 8, s1.f17602a, str33);
                        i13 = i22 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_EVENT_EMITTER;
                        Unit unit10 = Unit.f14616a;
                        str33 = str52;
                        str26 = str51;
                        str29 = str29;
                        i20 = i20;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        i14 = i13;
                        list7 = list7;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 9:
                        String str53 = str26;
                        list9 = list9;
                        embedMedia5 = embedMedia5;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia4 = embedMedia4;
                        StructurableText structurableText8 = (StructurableText) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 9, StructurableTextSerializer.INSTANCE, structurableText6);
                        i15 = i22 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_PADDING;
                        Unit unit11 = Unit.f14616a;
                        structurableText6 = structurableText8;
                        str26 = str53;
                        list7 = list7;
                        str29 = str29;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        str33 = str33;
                        i14 = i15;
                        i20 = i20;
                        str30 = str30;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 10:
                        String str54 = str26;
                        embedThumbnail3 = embedThumbnail3;
                        list9 = list9;
                        EmbedMedia embedMedia6 = (EmbedMedia) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 10, EmbedMedia$$serializer.INSTANCE, embedMedia4);
                        i13 = i22 | IntBufferBatchMountItem.INSTRUCTION_UPDATE_OVERFLOW_INSET;
                        Unit unit12 = Unit.f14616a;
                        embedMedia4 = embedMedia6;
                        str26 = str54;
                        str29 = str29;
                        i20 = i20;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        i14 = i13;
                        list7 = list7;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 11:
                        String str55 = str26;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        List list12 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 11, (DeserializationStrategy) lazyArr[11].getValue(), list9);
                        i15 = i22 | RecyclerView.ItemAnimator.FLAG_MOVED;
                        Unit unit13 = Unit.f14616a;
                        list9 = list12;
                        str26 = str55;
                        list7 = list7;
                        str29 = str29;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        i14 = i15;
                        i20 = i20;
                        str30 = str30;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 12:
                        List list13 = list7;
                        embedThumbnail3 = embedThumbnail3;
                        EmbedMedia embedMedia7 = (EmbedMedia) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 12, EmbedMedia$$serializer.INSTANCE, embedMedia5);
                        i15 = i22 | RecyclerView.ItemAnimator.FLAG_APPEARED_IN_PRE_LAYOUT;
                        Unit unit14 = Unit.f14616a;
                        embedMedia5 = embedMedia7;
                        str26 = str26;
                        list7 = list13;
                        str29 = str29;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        i14 = i15;
                        i20 = i20;
                        str30 = str30;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 13:
                        String str56 = str26;
                        EmbedThumbnail embedThumbnail4 = (EmbedThumbnail) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 13, EmbedThumbnail$$serializer.INSTANCE, embedThumbnail3);
                        i13 = i22 | 8192;
                        Unit unit15 = Unit.f14616a;
                        embedThumbnail3 = embedThumbnail4;
                        str26 = str56;
                        str29 = str29;
                        i20 = i20;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        i14 = i13;
                        list7 = list7;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 14:
                        str36 = str36;
                        str35 = str35;
                        String str57 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 14, s1.f17602a, str34);
                        i12 = i22 | 16384;
                        Unit unit16 = Unit.f14616a;
                        str34 = str57;
                        str26 = str26;
                        list7 = list7;
                        i20 = i20;
                        i14 = i12;
                        str29 = str29;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 15:
                        str36 = str36;
                        String str58 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 15, s1.f17602a, str35);
                        i12 = i22 | PeerConnection.PORTALLOCATOR_ENABLE_ANY_ADDRESS_PORTS;
                        Unit unit17 = Unit.f14616a;
                        str35 = str58;
                        str26 = str26;
                        list7 = list7;
                        i20 = i20;
                        i14 = i12;
                        str29 = str29;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 16:
                        String str59 = str26;
                        embedFooter3 = embedFooter3;
                        str37 = str37;
                        str29 = str29;
                        bool12 = bool12;
                        String str60 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 16, s1.f17602a, str36);
                        i12 = i22 | 65536;
                        Unit unit18 = Unit.f14616a;
                        str36 = str60;
                        str26 = str59;
                        list7 = list7;
                        i20 = i20;
                        str35 = str35;
                        i14 = i12;
                        str29 = str29;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 17:
                        List list14 = list7;
                        str37 = str37;
                        str29 = str29;
                        embedFooter3 = embedFooter3;
                        Boolean bool13 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 17, g.f17537a, bool12);
                        i12 = i22 | 131072;
                        Unit unit19 = Unit.f14616a;
                        bool12 = bool13;
                        str26 = str26;
                        list7 = list14;
                        i20 = i20;
                        str35 = str35;
                        str36 = str36;
                        i14 = i12;
                        str29 = str29;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 18:
                        String str61 = str26;
                        str29 = str29;
                        str37 = str37;
                        EmbedFooter embedFooter4 = (EmbedFooter) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 18, EmbedFooter$$serializer.INSTANCE, embedFooter3);
                        i12 = i22 | 262144;
                        Unit unit20 = Unit.f14616a;
                        embedFooter3 = embedFooter4;
                        str26 = str61;
                        list7 = list7;
                        i20 = i20;
                        str35 = str35;
                        str36 = str36;
                        bool12 = bool12;
                        i14 = i12;
                        str29 = str29;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 19:
                        List list15 = list7;
                        str29 = str29;
                        String str62 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 19, s1.f17602a, str37);
                        i12 = i22 | 524288;
                        Unit unit21 = Unit.f14616a;
                        str37 = str62;
                        str26 = str26;
                        list7 = list15;
                        i20 = i20;
                        str35 = str35;
                        str36 = str36;
                        bool12 = bool12;
                        embedFooter3 = embedFooter3;
                        i14 = i12;
                        str29 = str29;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 20:
                        String str63 = str26;
                        String str64 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 20, s1.f17602a, str29);
                        int i27 = i22 | 1048576;
                        Unit unit22 = Unit.f14616a;
                        str29 = str64;
                        str26 = str63;
                        i14 = i27;
                        bool9 = bool9;
                        list7 = list7;
                        i20 = i20;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        embedMedia5 = embedMedia5;
                        embedThumbnail3 = embedThumbnail3;
                        str35 = str35;
                        str36 = str36;
                        bool12 = bool12;
                        embedFooter3 = embedFooter3;
                        str37 = str37;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 21:
                        str27 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 21, s1.f17602a, str27);
                        int i28 = i22 | 2097152;
                        Unit unit23 = Unit.f14616a;
                        bool9 = bool9;
                        str26 = str26;
                        i20 = i20;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        embedMedia5 = embedMedia5;
                        embedThumbnail3 = embedThumbnail3;
                        str35 = str35;
                        str36 = str36;
                        bool12 = bool12;
                        embedFooter3 = embedFooter3;
                        str37 = str37;
                        i14 = i28;
                        str29 = str29;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 22:
                        bool11 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 22, g.f17537a, bool11);
                        i16 = i22 | 4194304;
                        Unit unit24 = Unit.f14616a;
                        bool9 = bool9;
                        i14 = i16;
                        str27 = str27;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 23:
                        bool9 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 23, g.f17537a, bool9);
                        i16 = i22 | 8388608;
                        Unit unit25 = Unit.f14616a;
                        bool9 = bool9;
                        i14 = i16;
                        str27 = str27;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 24:
                        bool10 = (Boolean) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 24, g.f17537a, bool10);
                        i16 = i22 | PointerEventHelper.X_FLAG_SUPPORTS_HOVER;
                        Unit unit26 = Unit.f14616a;
                        bool9 = bool9;
                        i14 = i16;
                        str27 = str27;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 25:
                        str26 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 25, s1.f17602a, str26);
                        i16 = i22 | 33554432;
                        Unit unit27 = Unit.f14616a;
                        bool9 = bool9;
                        i14 = i16;
                        str27 = str27;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 26:
                        list7 = (List) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 26, (DeserializationStrategy) lazyArr[26].getValue(), list7);
                        i16 = i22 | 67108864;
                        Unit unit28 = Unit.f14616a;
                        bool9 = bool9;
                        i14 = i16;
                        str27 = str27;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 27:
                        embedFailureState2 = (EmbedFailureState) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 27, EmbedFailureState.Serializer.INSTANCE, embedFailureState2);
                        i17 = i22 | 134217728;
                        Unit unit29 = Unit.f14616a;
                        bool9 = bool9;
                        i14 = i17;
                        str27 = str27;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 28:
                        num9 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 28, m0.f17573a, num9);
                        i17 = i22 | 268435456;
                        Unit unit30 = Unit.f14616a;
                        bool9 = bool9;
                        i14 = i17;
                        str27 = str27;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 29:
                        str27 = str27;
                        Integer num13 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 29, m0.f17573a, num10);
                        Unit unit31 = Unit.f14616a;
                        bool9 = bool9;
                        i14 = i22 | 536870912;
                        i20 = i20;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        embedMedia5 = embedMedia5;
                        embedThumbnail3 = embedThumbnail3;
                        num10 = num13;
                        str27 = str27;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 30:
                        str27 = str27;
                        Integer num14 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 30, m0.f17573a, num11);
                        Unit unit32 = Unit.f14616a;
                        bool9 = bool9;
                        i14 = i22 | 1073741824;
                        i20 = i20;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        str33 = str33;
                        structurableText6 = structurableText6;
                        embedMedia4 = embedMedia4;
                        list9 = list9;
                        embedMedia5 = embedMedia5;
                        embedThumbnail3 = embedThumbnail3;
                        num11 = num14;
                        str27 = str27;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 31:
                        str27 = str27;
                        int iDecodeIntElement2 = compositeDecoderBeginStructure.decodeIntElement(serialDescriptor, 31);
                        Unit unit33 = Unit.f14616a;
                        bool9 = bool9;
                        i21 = iDecodeIntElement2;
                        i14 = i22 | Integer.MIN_VALUE;
                        str27 = str27;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 32:
                        num12 = (Integer) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 32, m0.f17573a, num12);
                        i23 |= 1;
                        Unit unit34 = Unit.f14616a;
                        bool9 = bool9;
                        i14 = i22;
                        str27 = str27;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 33:
                        str38 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 33, s1.f17602a, str38);
                        i23 |= 2;
                        Unit unit35 = Unit.f14616a;
                        bool9 = bool9;
                        i14 = i22;
                        str27 = str27;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    case 34:
                        str28 = (String) compositeDecoderBeginStructure.decodeNullableSerializableElement(serialDescriptor, 34, s1.f17602a, str28);
                        i23 |= 4;
                        Unit unit36 = Unit.f14616a;
                        bool9 = bool9;
                        i14 = i22;
                        str27 = str27;
                        i22 = i14;
                        str37 = str37;
                        embedFooter3 = embedFooter3;
                        bool12 = bool12;
                        str36 = str36;
                        str35 = str35;
                        embedThumbnail3 = embedThumbnail3;
                        embedMedia5 = embedMedia5;
                        list9 = list9;
                        str33 = str33;
                        embedMedia4 = embedMedia4;
                        str30 = str30;
                        embedAuthor3 = embedAuthor3;
                        embedProvider3 = embedProvider3;
                        str31 = str31;
                        structurableText5 = structurableText5;
                        list8 = list8;
                        str32 = str32;
                        structurableText6 = structurableText6;
                        i18 = 6;
                        i20 = i20;
                        bool9 = bool9;
                        break;
                    default:
                        throw new j(iDecodeElementIndex);
                }
            }
            embedMedia = embedMedia4;
            embedType = embedType3;
            bool = bool10;
            num = num9;
            embedFailureState = embedFailureState2;
            str = str27;
            str2 = str28;
            str3 = str38;
            num2 = num12;
            num3 = num10;
            num4 = num11;
            bool2 = bool11;
            i7 = i22;
            str4 = str26;
            list = list7;
            str5 = str29;
            str6 = str37;
            embedFooter = embedFooter3;
            bool3 = bool12;
            str7 = str36;
            str8 = str35;
            bool4 = bool9;
            embedThumbnail = embedThumbnail3;
            embedMedia2 = embedMedia5;
            list2 = list9;
            str9 = str33;
            str10 = str30;
            embedAuthor = embedAuthor3;
            embedProvider = embedProvider3;
            str11 = str31;
            structurableText = structurableText5;
            list3 = list8;
            str12 = str32;
            structurableText2 = structurableText6;
            i10 = i21;
            str13 = str34;
            i11 = i23;
        }
        EmbedMedia embedMedia8 = embedMedia;
        compositeDecoderBeginStructure.endStructure(serialDescriptor);
        return new Embed(i7, i11, embedType, str10, embedAuthor, embedProvider, str11, structurableText, list3, str12, str9, structurableText2, embedMedia8, list2, embedMedia2, embedThumbnail, str13, str8, str7, bool3, embedFooter, str6, str5, str, bool2, bool4, bool, str4, list, embedFailureState, num, num3, num4, i10, num2, str3, str2, null);
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.KSerializer
    public final void serialize(@NotNull Encoder encoder, @NotNull Embed value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor serialDescriptor = descriptor;
        CompositeEncoder compositeEncoderBeginStructure = encoder.beginStructure(serialDescriptor);
        Embed.write$Self$chat_release(value, compositeEncoderBeginStructure, serialDescriptor);
        compositeEncoderBeginStructure.endStructure(serialDescriptor);
    }

    @Override // or.f0
    @NotNull
    public KSerializer[] typeParametersSerializers() {
        return e1.f17528b;
    }
}
