package chat.stoat.api.routes.account

import android.util.Log
import chat.stoat.api.StoatJson
import chat.stoat.discord.DISCORD_API
import chat.stoat.discord.DiscordHttp
import chat.stoat.discord.DiscordJson
import io.ktor.client.request.delete
import io.ktor.client.request.get
import io.ktor.client.request.post
import io.ktor.client.request.setBody
import io.ktor.client.statement.HttpResponse
import io.ktor.client.statement.bodyAsText
import io.ktor.http.ContentType
import io.ktor.http.contentType
import io.ktor.http.isSuccess
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.builtins.ListSerializer
import java.security.SecureRandom

const val MFA_TICKET_HEADER_NAME = "x-mfa-ticket"

@Serializable
data class MfaTicket(
    @SerialName("_id") val id: String,
    @SerialName("account_id") val accountId: String,
    val token: String,
    val validated: Boolean = false,
    val authorised: Boolean = false,
    @SerialName("last_totp_code") val lastTotpCode: String? = null
)

@Serializable
private data class TotpEnableBody(val secret: String, val code: String, val name: String = "Stoat")

@Serializable
private data class TotpDisableBody(val code: String)

@Serializable
private data class MfaCodesResponse(val codes: List<String> = emptyList())

private suspend fun HttpResponse.ensureSuccess(what: String) {
    if (status.isSuccess()) return
    val body = bodyAsText()
    throw Exception("Failed to $what: HTTP ${status.value}: ${body.take(200)}")
}

/**
 * The last TOTP secret generated by [generateTotpSecret]; Discord's enable
 * endpoint requires the client-generated secret alongside the first code.
 */
@Volatile
private var pendingTotpSecret: String? = null

private const val BASE32_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"

suspend fun fetchMfaMethods(): List<String> {
    // Discord user accounts use TOTP only (plus backup codes).
    return listOf("Totp")
}

/**
 * Discord authorises MFA changes with the TOTP code itself (or the account
 * password); there is no ticket concept, so we hand back a synthetic ticket.
 */
suspend fun createMfaTicket(response: MfaResponse): MfaTicket {
    return MfaTicket(
        id = "discord",
        accountId = "",
        token = "discord",
        validated = true,
        authorised = true,
    )
}

/** Generates a client-side base32 TOTP secret (as the official client does). */
suspend fun generateTotpSecret(mfaTicketToken: String): String {
    val random = SecureRandom()
    val secret = buildString {
        repeat(32) { append(BASE32_ALPHABET[random.nextInt(BASE32_ALPHABET.length)]) }
    }
    pendingTotpSecret = secret
    return secret
}

/** Enables TOTP: `POST /users/@me/mfa/totp/enable`. */
suspend fun enableTotp(totpCode: String) {
    val secret = pendingTotpSecret
        ?: throw Exception("No TOTP secret was generated; call generateTotpSecret first")
    val res = DiscordHttp.post("$DISCORD_API/users/@me/mfa/totp/enable") {
        contentType(ContentType.Application.Json)
        setBody(TotpEnableBody(secret = secret, code = totpCode))
    }
    res.ensureSuccess("enable TOTP")
    pendingTotpSecret = null
}

/** Disables TOTP: `DELETE /users/@me/mfa/totp`. */
suspend fun disableTotp(mfaTicketToken: String) {
    // The Revolt flow passes an MFA ticket token here; Discord instead expects
    // the TOTP code, which the settings UI supplies via this same parameter.
    val res = DiscordHttp.delete("$DISCORD_API/users/@me/mfa/totp") {
        contentType(ContentType.Application.Json)
        setBody(TotpDisableBody(code = mfaTicketToken))
    }
    res.ensureSuccess("disable TOTP")
}

/** Views the current recovery codes: `GET /users/@me/mfa/codes`. */
suspend fun fetchRecoveryCodes(mfaTicketToken: String): List<String> {
    val res = DiscordHttp.get("$DISCORD_API/users/@me/mfa/codes")
    res.ensureSuccess("fetch recovery codes")
    return runCatching {
        DiscordJson.decodeFromString(MfaCodesResponse.serializer(), res.bodyAsText()).codes
    }.getOrElse { emptyList() }
}

/** Regenerates the recovery codes: `POST /users/@me/mfa/codes-regeneration`. */
suspend fun regenerateRecoveryCodes(mfaTicketToken: String): List<String> {
    val res = DiscordHttp.post("$DISCORD_API/users/@me/mfa/codes-regeneration")
    res.ensureSuccess("regenerate recovery codes")
    return runCatching {
        DiscordJson.decodeFromString(MfaCodesResponse.serializer(), res.bodyAsText()).codes
    }.getOrElse { emptyList() }
}
