package com.discord.chat.presentation.events;

import com.discord.chat.reactevents.ChatScrollPositionEvent;
import com.discord.chat.reactevents.CompleteFirstLayoutData;
import com.discord.chat.reactevents.DoubleTapMessageEvent;
import com.discord.chat.reactevents.FirstLayoutData;
import com.discord.chat.reactevents.GiftIntentCardViewedData;
import com.discord.chat.reactevents.GiftIntentPrimaryCtaData;
import com.discord.chat.reactevents.GiftIntentSecondaryCtaData;
import com.discord.chat.reactevents.InitiateEditData;
import com.discord.chat.reactevents.InitiateReplyData;
import com.discord.chat.reactevents.InitiateThreadData;
import com.discord.chat.reactevents.LongPressAttachmentLinkData;
import com.discord.chat.reactevents.LongPressAvatarData;
import com.discord.chat.reactevents.LongPressChannelData;
import com.discord.chat.reactevents.LongPressCommandData;
import com.discord.chat.reactevents.LongPressLinkData;
import com.discord.chat.reactevents.LongPressMessageEvent;
import com.discord.chat.reactevents.LongPressPollImageData;
import com.discord.chat.reactevents.LongPressReactionData;
import com.discord.chat.reactevents.LongPressStickerData;
import com.discord.chat.reactevents.LongPressUsernameData;
import com.discord.chat.reactevents.MediaAttachmentPlaybackEndedData;
import com.discord.chat.reactevents.MediaAttachmentPlaybackStartedData;
import com.discord.chat.reactevents.SharedClientThemeViewedData;
import com.discord.chat.reactevents.TapAppMessageEmbedData;
import com.discord.chat.reactevents.TapAttachmentLinkData;
import com.discord.chat.reactevents.TapAutoModerationActionsData;
import com.discord.chat.reactevents.TapAutoModerationFeedbackData;
import com.discord.chat.reactevents.TapAvatarData;
import com.discord.chat.reactevents.TapButtonActionComponent;
import com.discord.chat.reactevents.TapCallData;
import com.discord.chat.reactevents.TapCancelUploadItemData;
import com.discord.chat.reactevents.TapChannelData;
import com.discord.chat.reactevents.TapChannelPromptButtonData;
import com.discord.chat.reactevents.TapCheckpointCardData;
import com.discord.chat.reactevents.TapClanTagChipletData;
import com.discord.chat.reactevents.TapCommandData;
import com.discord.chat.reactevents.TapConnectionsRoleTagData;
import com.discord.chat.reactevents.TapContentInventoryEntryEmbedData;
import com.discord.chat.reactevents.TapCopyText;
import com.discord.chat.reactevents.TapCtaButton;
import com.discord.chat.reactevents.TapDismissMediaPostSharePromptData;
import com.discord.chat.reactevents.TapEmojiData;
import com.discord.chat.reactevents.TapFollowForumPost;
import com.discord.chat.reactevents.TapForwardFooterData;
import com.discord.chat.reactevents.TapGameIconData;
import com.discord.chat.reactevents.TapGameMentionData;
import com.discord.chat.reactevents.TapGiftCodeAcceptData;
import com.discord.chat.reactevents.TapGiftCodeEmbedData;
import com.discord.chat.reactevents.TapImageData;
import com.discord.chat.reactevents.TapInlineCodeEvent;
import com.discord.chat.reactevents.TapInlineForwardData;
import com.discord.chat.reactevents.TapInviteAcceptEvent;
import com.discord.chat.reactevents.TapInviteEvent;
import com.discord.chat.reactevents.TapInviteToSpeakData;
import com.discord.chat.reactevents.TapJoinActivityData;
import com.discord.chat.reactevents.TapJoinRichPresenceData;
import com.discord.chat.reactevents.TapLinkData;
import com.discord.chat.reactevents.TapMentionData;
import com.discord.chat.reactevents.TapMessageData;
import com.discord.chat.reactevents.TapMessageReplyData;
import com.discord.chat.reactevents.TapObscuredMediaLearnMoreData;
import com.discord.chat.reactevents.TapObscuredMediaToggleData;
import com.discord.chat.reactevents.TapOpTagData;
import com.discord.chat.reactevents.TapPollAction;
import com.discord.chat.reactevents.TapPollAnswer;
import com.discord.chat.reactevents.TapPollSubmitVote;
import com.discord.chat.reactevents.TapPostPreviewEmbedData;
import com.discord.chat.reactevents.TapPreviewSharedClientThemeData;
import com.discord.chat.reactevents.TapReactionData;
import com.discord.chat.reactevents.TapReferralRedeemData;
import com.discord.chat.reactevents.TapRoleIconData;
import com.discord.chat.reactevents.TapSafetyPolicyNoticeEmbed;
import com.discord.chat.reactevents.TapSafetySystemNotificationCta;
import com.discord.chat.reactevents.TapSeeMoreData;
import com.discord.chat.reactevents.TapSelectActionComponent;
import com.discord.chat.reactevents.TapSeparatorData;
import com.discord.chat.reactevents.TapShareForumPost;
import com.discord.chat.reactevents.TapShowAltTextData;
import com.discord.chat.reactevents.TapSoundmojiData;
import com.discord.chat.reactevents.TapStickerData;
import com.discord.chat.reactevents.TapSummaryData;
import com.discord.chat.reactevents.TapSummaryJumpData;
import com.discord.chat.reactevents.TapSuppressNotificationsIconData;
import com.discord.chat.reactevents.TapTagData;
import com.discord.chat.reactevents.TapThreadEmbedEvent;
import com.discord.chat.reactevents.TapTimeoutIconData;
import com.discord.chat.reactevents.TapTimestampEvent;
import com.discord.chat.reactevents.TapUsernameData;
import com.discord.chat.reactevents.TapVoiceChannelBadgeData;
import com.discord.chat.reactevents.TapWelcomeReplyData;
import com.discord.chat.reactevents.VoiceMessagePlaybackFailedData;
import com.discord.media_player.reactevents.MediaPlayFinishedAnalytics;
import com.discord.reactevents.ReactEvents;
import kotlin.Metadata;
import kotlin.Pair;
import kotlin.jvm.internal.Reflection;
import org.jetbrains.annotations.NotNull;

/* JADX INFO: loaded from: classes.dex */
@Metadata(d1 = {"\u0000\b\n\u0000\n\u0002\u0018\u0002\n\u0000\u001a\b\u0010\u0000\u001a\u00020\u0001H\u0000¨\u0006\u0002"}, d2 = {"createChatReactEvents", "Lcom/discord/reactevents/ReactEvents;", "chat_release"}, k = 2, mv = {2, 1, 0}, xi = 48)
public final class CreateChatReactEventsKt {
    @NotNull
    public static final ReactEvents createChatReactEvents() {
        return new ReactEvents(new Pair("onChatScrollPosition", Reflection.getOrCreateKotlinClass(ChatScrollPositionEvent.class)), new Pair("onLongPressAttachmentLink", Reflection.getOrCreateKotlinClass(LongPressAttachmentLinkData.class)), new Pair("onLongPressAvatar", Reflection.getOrCreateKotlinClass(LongPressAvatarData.class)), new Pair("onLongPressMessage", Reflection.getOrCreateKotlinClass(LongPressMessageEvent.class)), new Pair("onLongPressReaction", Reflection.getOrCreateKotlinClass(LongPressReactionData.class)), new Pair("onLongPressSticker", Reflection.getOrCreateKotlinClass(LongPressStickerData.class)), new Pair("onLongPressUsername", Reflection.getOrCreateKotlinClass(LongPressUsernameData.class)), new Pair("onLongPressCommandMention", Reflection.getOrCreateKotlinClass(LongPressCommandData.class)), new Pair("onLongPressChannel", Reflection.getOrCreateKotlinClass(LongPressChannelData.class)), new Pair("onTapAttachmentLink", Reflection.getOrCreateKotlinClass(TapAttachmentLinkData.class)), new Pair("onTapAvatar", Reflection.getOrCreateKotlinClass(TapAvatarData.class)), new Pair("onTapButtonActionComponent", Reflection.getOrCreateKotlinClass(TapButtonActionComponent.class)), new Pair("onTapCall", Reflection.getOrCreateKotlinClass(TapCallData.class)), new Pair("onTapChannel", Reflection.getOrCreateKotlinClass(TapChannelData.class)), new Pair("onTapCopyText", Reflection.getOrCreateKotlinClass(TapCopyText.class)), new Pair("onTapGiftCodeAccept", Reflection.getOrCreateKotlinClass(TapGiftCodeAcceptData.class)), new Pair("onTapGiftCodeEmbed", Reflection.getOrCreateKotlinClass(TapGiftCodeEmbedData.class)), new Pair("onTapReferralRedeem", Reflection.getOrCreateKotlinClass(TapReferralRedeemData.class)), new Pair("onTapImage", Reflection.getOrCreateKotlinClass(TapImageData.class)), new Pair("onTapInviteEmbed", Reflection.getOrCreateKotlinClass(TapInviteEvent.class)), new Pair("onTapInviteEmbedAccept", Reflection.getOrCreateKotlinClass(TapInviteAcceptEvent.class)), new Pair("onTapJoinActivity", Reflection.getOrCreateKotlinClass(TapJoinActivityData.class)), new Pair("onTapJoinRichPresence", Reflection.getOrCreateKotlinClass(TapJoinRichPresenceData.class)), new Pair("onTapLink", Reflection.getOrCreateKotlinClass(TapLinkData.class)), new Pair("onLongPressLink", Reflection.getOrCreateKotlinClass(LongPressLinkData.class)), new Pair("onTapMention", Reflection.getOrCreateKotlinClass(TapMentionData.class)), new Pair("onTapCommandMention", Reflection.getOrCreateKotlinClass(TapCommandData.class)), new Pair("onTapGameMention", Reflection.getOrCreateKotlinClass(TapGameMentionData.class)), new Pair("onTapMessage", Reflection.getOrCreateKotlinClass(TapMessageData.class)), new Pair("onDoubleTapMessage", Reflection.getOrCreateKotlinClass(DoubleTapMessageEvent.class)), new Pair("onTapMessageReply", Reflection.getOrCreateKotlinClass(TapMessageReplyData.class)), new Pair("onTapSummary", Reflection.getOrCreateKotlinClass(TapSummaryData.class)), new Pair("onTapSummaryJump", Reflection.getOrCreateKotlinClass(TapSummaryJumpData.class)), new Pair("onTapReaction", Reflection.getOrCreateKotlinClass(TapReactionData.class)), new Pair("onTapRoleIcon", Reflection.getOrCreateKotlinClass(TapRoleIconData.class)), new Pair("onTapVoiceChannelBadge", Reflection.getOrCreateKotlinClass(TapVoiceChannelBadgeData.class)), new Pair("onTapGameIcon", Reflection.getOrCreateKotlinClass(TapGameIconData.class)), new Pair("onTapSuppressNotificationsIcon", Reflection.getOrCreateKotlinClass(TapSuppressNotificationsIconData.class)), new Pair("onTapTimeoutIcon", Reflection.getOrCreateKotlinClass(TapTimeoutIconData.class)), new Pair("onTapSeeMore", Reflection.getOrCreateKotlinClass(TapSeeMoreData.class)), new Pair("onInitiateReply", Reflection.getOrCreateKotlinClass(InitiateReplyData.class)), new Pair("onInitiateThread", Reflection.getOrCreateKotlinClass(InitiateThreadData.class)), new Pair("onInitiateEdit", Reflection.getOrCreateKotlinClass(InitiateEditData.class)), new Pair("onTapConnectionsRoleTag", Reflection.getOrCreateKotlinClass(TapConnectionsRoleTagData.class)), new Pair("onTapSelectActionComponent", Reflection.getOrCreateKotlinClass(TapSelectActionComponent.class)), new Pair("onTapSeparator", Reflection.getOrCreateKotlinClass(TapSeparatorData.class)), new Pair("onTapSticker", Reflection.getOrCreateKotlinClass(TapStickerData.class)), new Pair("onTapTimestamp", Reflection.getOrCreateKotlinClass(TapTimestampEvent.class)), new Pair("onTapInlineCode", Reflection.getOrCreateKotlinClass(TapInlineCodeEvent.class)), new Pair("onTapThreadEmbed", Reflection.getOrCreateKotlinClass(TapThreadEmbedEvent.class)), new Pair("onTapUsername", Reflection.getOrCreateKotlinClass(TapUsernameData.class)), new Pair("onTapCancelUploadItem", Reflection.getOrCreateKotlinClass(TapCancelUploadItemData.class)), new Pair("onTapWelcomeReply", Reflection.getOrCreateKotlinClass(TapWelcomeReplyData.class)), new Pair("onTapInviteToSpeak", Reflection.getOrCreateKotlinClass(TapInviteToSpeakData.class)), new Pair("onTapEmoji", Reflection.getOrCreateKotlinClass(TapEmojiData.class)), new Pair("onTapFollowForumPost", Reflection.getOrCreateKotlinClass(TapFollowForumPost.class)), new Pair("onTapShareForumPost", Reflection.getOrCreateKotlinClass(TapShareForumPost.class)), new Pair("onTapReactionOverflow", Reflection.getOrCreateKotlinClass(TapReactionOverflow.class)), new Pair("onTapAutoModerationActions", Reflection.getOrCreateKotlinClass(TapAutoModerationActionsData.class)), new Pair("onTapAutoModerationFeedback", Reflection.getOrCreateKotlinClass(TapAutoModerationFeedbackData.class)), new Pair("onTapOpTag", Reflection.getOrCreateKotlinClass(TapOpTagData.class)), new Pair("onTapShowAltText", Reflection.getOrCreateKotlinClass(TapShowAltTextData.class)), new Pair("onMediaAttachmentPlaybackEnded", Reflection.getOrCreateKotlinClass(MediaAttachmentPlaybackEndedData.class)), new Pair("onVoiceMessagePlaybackFailed", Reflection.getOrCreateKotlinClass(VoiceMessagePlaybackFailedData.class)), new Pair("onMediaAttachmentPlaybackStarted", Reflection.getOrCreateKotlinClass(MediaAttachmentPlaybackStartedData.class)), new Pair("onTapAppMessageEmbed", Reflection.getOrCreateKotlinClass(TapAppMessageEmbedData.class)), new Pair("onTapPostPreviewEmbed", Reflection.getOrCreateKotlinClass(TapPostPreviewEmbedData.class)), new Pair("onTapDismissMediaPostSharePrompt", Reflection.getOrCreateKotlinClass(TapDismissMediaPostSharePromptData.class)), new Pair("onTapTag", Reflection.getOrCreateKotlinClass(TapTagData.class)), new Pair("onTapChannelPromptButton", Reflection.getOrCreateKotlinClass(TapChannelPromptButtonData.class)), new Pair("onTapObscuredMediaLearnMore", Reflection.getOrCreateKotlinClass(TapObscuredMediaLearnMoreData.class)), new Pair("onTapObscuredMediaToggle", Reflection.getOrCreateKotlinClass(TapObscuredMediaToggleData.class)), new Pair("onTapSafetyPolicyNoticeEmbed", Reflection.getOrCreateKotlinClass(TapSafetyPolicyNoticeEmbed.class)), new Pair("onTapSafetySystemNotificationCta", Reflection.getOrCreateKotlinClass(TapSafetySystemNotificationCta.class)), new Pair("onTapPollAnswer", Reflection.getOrCreateKotlinClass(TapPollAnswer.class)), new Pair("onTapPollSubmitVote", Reflection.getOrCreateKotlinClass(TapPollSubmitVote.class)), new Pair("onTapPollAction", Reflection.getOrCreateKotlinClass(TapPollAction.class)), new Pair("onLongPressPollImage", Reflection.getOrCreateKotlinClass(LongPressPollImageData.class)), new Pair("onTapCtaButton", Reflection.getOrCreateKotlinClass(TapCtaButton.class)), new Pair("onFirstLayout", Reflection.getOrCreateKotlinClass(FirstLayoutData.class)), new Pair("onCompleteFirstLayout", Reflection.getOrCreateKotlinClass(CompleteFirstLayoutData.class)), new Pair("onMediaPlayFinishedAnalytics", Reflection.getOrCreateKotlinClass(MediaPlayFinishedAnalytics.class)), new Pair("onTapForwardFooter", Reflection.getOrCreateKotlinClass(TapForwardFooterData.class)), new Pair("onTapInlineForward", Reflection.getOrCreateKotlinClass(TapInlineForwardData.class)), new Pair("onTapClanTagChiplet", Reflection.getOrCreateKotlinClass(TapClanTagChipletData.class)), new Pair("onTapContentInventoryEntryEmbed", Reflection.getOrCreateKotlinClass(TapContentInventoryEntryEmbedData.class)), new Pair("onTapCheckpointCard", Reflection.getOrCreateKotlinClass(TapCheckpointCardData.class)), new Pair("onTapSoundmoji", Reflection.getOrCreateKotlinClass(TapSoundmojiData.class)), new Pair("onTapPreviewSharedClientTheme", Reflection.getOrCreateKotlinClass(TapPreviewSharedClientThemeData.class)), new Pair("onSharedClientThemeViewed", Reflection.getOrCreateKotlinClass(SharedClientThemeViewedData.class)), new Pair("onGiftIntentCardViewed", Reflection.getOrCreateKotlinClass(GiftIntentCardViewedData.class)), new Pair("onTapGiftIntentPrimaryCta", Reflection.getOrCreateKotlinClass(GiftIntentPrimaryCtaData.class)), new Pair("onTapGiftIntentSecondaryCta", Reflection.getOrCreateKotlinClass(GiftIntentSecondaryCtaData.class)));
    }
}
